"""dinkster_api.v1 - the frozen extension surface, version 1.

THE door for pack authors: everything a pack needs to author nodes,
register value types and codecs, declare memory policy, and extend the
asset system, re-exported from the internal packages in one place.

The compat promise (DESIGN 3.6, enforced by tests/test_api_v1.py):

- Within v1 this surface only ever GROWS. Nothing here is renamed,
  removed, or changed incompatibly; breaking changes mean a ``v2``
  module next to this one, never edits to this one.
- Every name below is the internal object itself, not a wrapper - zero
  overhead, and ``isinstance``/identity checks agree across the door.
- Internal modules stay reachable (this is Python) but carry no promise:
  a pack that imports them works until it doesn't, visibly, in dev
  (isolation-by-default makes that breakage loud - DESIGN 3.6).

Grouped by concern:

- *Extension declarations*: scope-separated entry-point metadata, closed
  composition modes, and immutable behavior snapshots/sha256 identity. These
  are RPC-clean data contracts; runtime activation and enforcement are host
  responsibilities.
- *Node authoring*: subclass ``Node``, return ``define_schema()`` built
  from the spec dataclasses, implement ``execute()`` over plain Python
  values. Envelopes, workers, and caching stay invisible (hazard H9).
- *Reporting*: ``report_progress``/``report_preview``/``report_log``/
  ``report_event`` from inside ``execute()`` - the worker shim routes them;
  no server or engine import needed.
- *Logging*: ``pack_logger("mypack")`` returns a stdlib logger named
  ``dinkster.pack.mypack`` - origin-tagged, host-controlled verbosity.
  Logs are for humans; anything a frontend renders goes through
  ``report_*``. Packs never install handlers or configure output.
- *Value types and codecs*: register pack types in the ``TypeRegistry``
  with a ``TypeSpec`` (codec, fingerprint, meta). Resource-backed types
  (models that live in a worker) go through ``ResourceHandle``.
- *Memory policy*: a ``ReservationPlanner`` declares what invocations
  materialize; ``Shedder``/``ConsumerItem`` surface a pack's governed
  memory consumers to the host governor.
- *Assets*: ``AssetRef`` inputs resolve through the host's catalog;
  packs may register custom ``AssetResolver`` implementations.
  ``declared_asset("id")`` resolves the pack's own ``[[pack.assets]]``
  declaration to a readable ref - acquired-or-loud-error, never a
  download during execution.
- *Golden-file testing*: ``schema_to_wire`` encodes a ``NodeSchema`` to
  its wire form (the exact shape ``/api/nodes`` serves, self-describing
  via ``schemaVersion``) so pack tests can pin schemas against committed
  JSON without importing host machinery.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from dinkster_assets import (
    ASSET_TYPE,
    SAVE_TARGET_TYPE,
    AssetEntry,
    AssetError,
    AssetIntegrityError,
    AssetRef,
    AssetResolver,
    AssetVault,
    AssetWriter,
    FolderListing,
    IndexedAssetResolver,
    MountSnapshotWriter,
    SaveTarget,
    bind_video_value,
    declared_asset,
    digest_bytes,
    digest_file,
    is_digest,
    register_asset_type,
    register_audio_value_type,
    register_save_target_type,
    register_video_value_type,
    resolver_from_env,
)
from dinkster_memory import (
    ConsumerItem,
    FullReleaseResult,
    InvocationView,
    MeasuredMemory,
    PressureSignal,
    ReleaseCandidate,
    ReservationPlanner,
    ReservationRequest,
    Shedder,
)
from dinkster_protocol import (
    EXTENSION_CAPABILITIES,
    EXTENSION_SCOPES,
    ActiveExtension,
    BehaviorValue,
    CompositionMode,
    ContributionSurfaceDescriptor,
    ExtensionDeclaration,
    ExtensionEntryPoints,
    ExtensionScope,
    ExtensionSnapshot,
    GuidancePhase,
    GuidancePhaseParticipation,
    GuidanceRegistrySnapshot,
    TrainingSessionHandle,
    canonical_extension_snapshot,
    extension_behavior_hash,
)
from dinkster_protocol.frontend_modules import FrontendContribution, FrontendModule
from dinkster_protocol.pack_surfaces import (
    JsonField,
    JsonObjectSchema,
    PackEvent,
    PackRoute,
    report_pack_event,
)
from dinkster_schema import (
    ABSENT,
    LOG_EVENT,
    PREVIEW_EVENT,
    PROGRESS_EVENT,
    SCHEMA_WIRE_VERSION,
    AbsentOutput,
    AbsentPolicy,
    AssetWidget,
    BooleanWidget,
    ColorWidget,
    ComboOption,
    ComboWidget,
    CompositorWidget,
    ConditionalWidgetCondition,
    ConditionalWidgetGroup,
    ControlAfterGenerate,
    CurveWidget,
    Deprecation,
    DynamicComboOption,
    DynamicComboSpec,
    DynamicSlotSpec,
    InputFamilyMapping,
    InputFamilyMember,
    InputFamilyOptionSource,
    InputFamilySpec,
    InputSpec,
    MappingSource,
    MirrorSpec,
    MirrorTolerance,
    MultiComboWidget,
    Node,
    NodeOutputError,
    NodeSchema,
    NumberWidget,
    OutputCountSpec,
    OutputDescriptorsSpec,
    OutputFamilyMapping,
    OutputFamilyMember,
    OutputFamilySpec,
    OutputInterface,
    OutputKnownValue,
    OutputProbeSpec,
    OutputRepresents,
    OutputSpec,
    ReplacementCase,
    ReplacementLink,
    ReplacementMigration,
    ReplacementNode,
    ReplacementPredicate,
    ReplacementRule,
    SaveTargetWidget,
    SearchVisibility,
    SelectorSpec,
    SlotValue,
    SlotVariant,
    SourceFilenameSpec,
    StringWidget,
    TextCompletionItem,
    TextCompletionKind,
    TextCompletions,
    TypeExpr,
    ValueTransform,
    WidgetRepresentation,
    WidgetRepresentations,
    output_descriptor_entries,
    pack_logger,
    report_event,
    report_log,
    report_preview,
    report_progress,
    report_value_diagnostic,
    schema_from_wire,
    schema_signature,
    schema_to_wire,
)
from dinkster_values import (
    CORE_BOOLEAN,
    CORE_COMBO,
    CORE_FLOAT,
    CORE_INT,
    CORE_STRING,
    COST_META_KEY,
    CURVE_TYPE,
    DETECTION_TYPE,
    IMAGE_BATCH_MERGER_ID,
    INLINE_STRING_CAP,
    LENGTH_META_KEY,
    MAX_CURVE_POINTS,
    MODEL3D_FILE_DECODER_ID,
    PNG_CONTAINER_VERSION,
    REGION_TYPE,
    RESOURCE_ID_META_KEY,
    RESOURCES_META_KEY,
    SPLAT_FILE_DECODER_ID,
    SPLAT_PLY_MIME,
    BufferEncoding,
    Curve,
    CustomWidgetDescriptor,
    Detection,
    Region,
    Rendition,
    RenditionSpec,
    ResourceHandle,
    TypeId,
    TypeRegistry,
    TypeSpec,
    annotate_image,
    annotate_mask,
    audio_fingerprint,
    audio_meta,
    coerce_detection,
    coerce_region,
    coerce_video,
    copy_media_semantics,
    curve,
    decode_audio,
    decode_detection,
    decode_image_array,
    decode_model3d,
    decode_model3d_file,
    decode_region,
    decode_splat,
    decode_splat_file,
    decode_video,
    detection_meta,
    edit_video,
    effective_video_facts,
    encode_audio,
    encode_detection,
    encode_image_array,
    encode_model3d,
    encode_region,
    encode_splat,
    encode_video,
    image_array_fingerprint,
    image_array_meta,
    mask_array_meta,
    media_semantics,
    merge_image_batches,
    model3d_fingerprint,
    model3d_format,
    model3d_meta,
    parse_ply_splat,
    prepare_image_array_encoding,
    region_meta,
    register_curve_type,
    register_model3d_type,
    register_resource_handle_type,
    render_audio_wav,
    render_image_png,
    render_mask_png,
    render_model3d_original,
    render_splat_ply,
    render_video_original,
    splat_fingerprint,
    splat_meta,
    stable_hash,
    timeline_video,
    validate_image_encoded,
    validate_model3d_encoded,
    validate_splat_encoded,
    validate_video_encoded,
    video_document,
    video_fingerprint,
    video_from_source,
    video_meta,
    video_rendition_mime,
)
from dinkster_values.audio_codec import (
    AudioWindowReader,
    append_audio_edit,
    audio_from_source,
    audio_window,
    effective_audio_facts,
)
from dinkster_values.audio_lazy import channel_layout as audio_channel_layout
from dinkster_video import (
    DITHERS,
    FRAME_FORMATS,
    assemble_video,
    disassemble_video,
    read_video_metadata,
    save_frame_records,
    save_video_frames,
    save_video_stream,
)

if TYPE_CHECKING:
    from dinkster_inference import (
        AIMDO_DISTRIBUTION,
        ATTENTION_BACKEND_SURFACE,
        ATTENTION_OUTPUT_SURFACE,
        ATTENTION_QKV_SURFACE,
        ATTENTION_WRAPPER_SURFACE,
        BLOCK_INJECTION_SURFACE,
        FLOAT32,
        TORCH_DISTRIBUTION,
        AssemblyRegistration,
        AttentionBackendDescriptor,
        AttentionCallContext,
        AttentionContribution,
        AttentionGuidanceDescriptor,
        AttentionKernelFn,
        AttentionOutputDescriptor,
        AttentionOutputTransform,
        AttentionPinError,
        AttentionQKVDescriptor,
        AttentionQKVTransform,
        AttentionSelector,
        AttentionTokenSpan,
        AttentionWrapperDescriptor,
        AttentionWrapperFn,
        AttentionWrapperNext,
        BlockInjectionDescriptor,
        BlockInjectionTransform,
        CancellationToken,
        CompilerEmission,
        ComponentDescriptor,
        ComponentWiring,
        ConditionScaleVector,
        ContextDenoiser,
        ContextSolverFn,
        ControlApplication,
        DetectionEvidence,
        EngineProperties,
        GraphCompilerDescriptor,
        GuidanceCondition,
        GuidanceContribution,
        GuidanceEvaluationPlan,
        GuidanceEvaluationRequest,
        GuidanceEvaluationWrapperDescriptor,
        GuidancePlanAugmentationDescriptor,
        GuidancePlanContext,
        GuidancePostCFGContext,
        GuidancePostCFGDescriptor,
        GuidancePreCFGContext,
        GuidancePreCFGDescriptor,
        GuidancePrediction,
        GuidancePredictions,
        GuidancePredictionSource,
        GuidanceReduceContext,
        GuidanceResult,
        GuidanceRole,
        GuidanceScaleDescriptor,
        GuidanceStrategyDescriptor,
        InferenceContribution,
        InputRewrite,
        LatentDescriptor,
        ModelEvaluation,
        ModelFamily,
        NoiseKind,
        NoiseSampler,
        OptionKind,
        OptionSpec,
        OptionValue,
        Parameterization,
        ProgressScope,
        SamplerContribution,
        SamplerDescriptor,
        SamplerInfo,
        SamplingCancelled,
        SamplingDescriptor,
        SamplingExecutionContext,
        SchedulerDescriptor,
        SolverFn,
        StepCallback,
        StepEvent,
        attention_declarations,
    )

# Node-only packs do not need to initialize the inference package.
_INFERENCE_EXPORTS = frozenset(
    {
        "AIMDO_DISTRIBUTION",
        "ATTENTION_BACKEND_SURFACE",
        "ATTENTION_OUTPUT_SURFACE",
        "ATTENTION_QKV_SURFACE",
        "ATTENTION_WRAPPER_SURFACE",
        "AssemblyRegistration",
        "AttentionBackendDescriptor",
        "AttentionCallContext",
        "AttentionContribution",
        "AttentionGuidanceDescriptor",
        "AttentionKernelFn",
        "AttentionOutputDescriptor",
        "AttentionOutputTransform",
        "AttentionPinError",
        "AttentionQKVDescriptor",
        "AttentionQKVTransform",
        "AttentionSelector",
        "AttentionTokenSpan",
        "AttentionWrapperDescriptor",
        "AttentionWrapperFn",
        "AttentionWrapperNext",
        "BLOCK_INJECTION_SURFACE",
        "BlockInjectionDescriptor",
        "BlockInjectionTransform",
        "CancellationToken",
        "CompilerEmission",
        "ConditionScaleVector",
        "ComponentDescriptor",
        "ComponentWiring",
        "ContextDenoiser",
        "ContextSolverFn",
        "ControlApplication",
        "DetectionEvidence",
        "EngineProperties",
        "FLOAT32",
        "GraphCompilerDescriptor",
        "GuidanceCondition",
        "GuidanceContribution",
        "GuidanceEvaluationPlan",
        "GuidanceEvaluationRequest",
        "GuidanceEvaluationWrapperDescriptor",
        "GuidancePlanAugmentationDescriptor",
        "GuidancePlanContext",
        "GuidancePostCFGContext",
        "GuidancePostCFGDescriptor",
        "GuidancePreCFGContext",
        "GuidancePreCFGDescriptor",
        "GuidancePrediction",
        "GuidancePredictions",
        "GuidancePredictionSource",
        "GuidanceReduceContext",
        "GuidanceResult",
        "GuidanceRole",
        "GuidanceScaleDescriptor",
        "GuidanceStrategyDescriptor",
        "InferenceContribution",
        "InputRewrite",
        "ModelEvaluation",
        "ModelFamily",
        "NoiseKind",
        "NoiseSampler",
        "OptionKind",
        "OptionSpec",
        "OptionValue",
        "Parameterization",
        "ProgressScope",
        "SamplerContribution",
        "SamplerDescriptor",
        "SamplerInfo",
        "SchedulerDescriptor",
        "SamplingCancelled",
        "SamplingExecutionContext",
        "SamplingDescriptor",
        "LatentDescriptor",
        "SolverFn",
        "StepCallback",
        "StepEvent",
        "TORCH_DISTRIBUTION",
        "attention_declarations",
    }
)

# Reloaded modules must resolve current authoritative objects on the next access.
for _name in _INFERENCE_EXPORTS:
    globals().pop(_name, None)


_VIDEO_MODULE_EXPORTS = frozenset(
    {"image_math", "timeline_document", "timeline_render", "timeline_runtime"}
)


def __getattr__(name: str) -> object:
    if name in _INFERENCE_EXPORTS:
        import dinkster_inference

        value = getattr(dinkster_inference, name)
    elif name in _VIDEO_MODULE_EXPORTS:
        import dinkster_video

        value = getattr(dinkster_video, name)
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | _INFERENCE_EXPORTS | _VIDEO_MODULE_EXPORTS)


if TYPE_CHECKING:
    from dinkster_video import document as timeline_document
    from dinkster_video import image_math, timeline_runtime
    from dinkster_video import timeline as timeline_render

__all__ = [
    "FrontendContribution",
    "FrontendModule",
    "JsonField",
    "JsonObjectSchema",
    "PackEvent",
    "PackRoute",
    "report_pack_event",
    "DITHERS",
    "FRAME_FORMATS",
    "read_video_metadata",
    "save_video_frames",
    "curve",
    "timeline_video",
    "video_document",
    "image_math",
    "timeline_document",
    "timeline_render",
    "timeline_runtime",
    "assemble_video",
    "disassemble_video",
    "save_frame_records",
    "save_video_stream",
    # -- extension declarations and behavior identity (dinkster-protocol)
    "EXTENSION_CAPABILITIES",
    "EXTENSION_SCOPES",
    "ActiveExtension",
    "BehaviorValue",
    "CompositionMode",
    "ContributionSurfaceDescriptor",
    "ExtensionDeclaration",
    "ExtensionEntryPoints",
    "ExtensionScope",
    "ExtensionSnapshot",
    "GuidancePhase",
    "GuidancePhaseParticipation",
    "GuidanceRegistrySnapshot",
    "canonical_extension_snapshot",
    "extension_behavior_hash",
    # -- training session boundary values (dinkster-protocol)
    "TrainingSessionHandle",
    # -- sampling extension authoring (dinkster-inference)
    "CancellationToken",
    "AssemblyRegistration",
    "AIMDO_DISTRIBUTION",
    "ATTENTION_BACKEND_SURFACE",
    "ATTENTION_OUTPUT_SURFACE",
    "ATTENTION_QKV_SURFACE",
    "ATTENTION_WRAPPER_SURFACE",
    "AttentionBackendDescriptor",
    "AttentionCallContext",
    "AttentionContribution",
    "AttentionGuidanceDescriptor",
    "AttentionKernelFn",
    "AttentionOutputDescriptor",
    "AttentionOutputTransform",
    "AttentionPinError",
    "AttentionQKVDescriptor",
    "AttentionQKVTransform",
    "AttentionSelector",
    "AttentionTokenSpan",
    "AttentionWrapperDescriptor",
    "AttentionWrapperFn",
    "AttentionWrapperNext",
    "BLOCK_INJECTION_SURFACE",
    "BlockInjectionDescriptor",
    "BlockInjectionTransform",
    "TORCH_DISTRIBUTION",
    "attention_declarations",
    "CompilerEmission",
    "ConditionScaleVector",
    "ComponentDescriptor",
    "ComponentWiring",
    "ControlApplication",
    "DetectionEvidence",
    "EngineProperties",
    "FLOAT32",
    "GuidanceCondition",
    "GuidanceContribution",
    "GuidanceEvaluationPlan",
    "GuidanceEvaluationRequest",
    "GuidanceEvaluationWrapperDescriptor",
    "GuidancePlanAugmentationDescriptor",
    "GuidancePlanContext",
    "GuidancePostCFGContext",
    "GuidancePostCFGDescriptor",
    "GuidancePreCFGContext",
    "GuidancePreCFGDescriptor",
    "GuidancePrediction",
    "GuidancePredictionSource",
    "GuidancePredictions",
    "GuidanceReduceContext",
    "GuidanceResult",
    "GuidanceRole",
    "GuidanceScaleDescriptor",
    "GuidanceStrategyDescriptor",
    "GraphCompilerDescriptor",
    "InferenceContribution",
    "InputRewrite",
    "ContextDenoiser",
    "ContextSolverFn",
    "ModelEvaluation",
    "ModelFamily",
    "NoiseKind",
    "NoiseSampler",
    "OptionKind",
    "OptionSpec",
    "OptionValue",
    "Parameterization",
    "ProgressScope",
    "SamplerContribution",
    "SamplerDescriptor",
    "SamplerInfo",
    "SchedulerDescriptor",
    "SamplingCancelled",
    "SamplingExecutionContext",
    "SamplingDescriptor",
    "LatentDescriptor",
    "SolverFn",
    "StepCallback",
    "StepEvent",
    # -- node authoring (dinkster-schema)
    "ABSENT",
    "AbsentOutput",
    "AbsentPolicy",
    "BooleanWidget",
    "ColorWidget",
    "CompositorWidget",
    "ConditionalWidgetCondition",
    "ConditionalWidgetGroup",
    "CurveWidget",
    "ComboOption",
    "ComboWidget",
    "ControlAfterGenerate",
    "CustomWidgetDescriptor",
    "Deprecation",
    "DynamicComboOption",
    "DynamicComboSpec",
    "DynamicSlotSpec",
    "InputFamilyOptionSource",
    "InputFamilyMapping",
    "InputFamilyMember",
    "InputFamilySpec",
    "InputSpec",
    "MirrorSpec",
    "MirrorTolerance",
    "MultiComboWidget",
    "MappingSource",
    "Node",
    "NodeOutputError",
    "NodeSchema",
    "NumberWidget",
    "OutputCountSpec",
    "OutputDescriptorsSpec",
    "OutputFamilyMapping",
    "OutputFamilyMember",
    "OutputFamilySpec",
    "OutputInterface",
    "OutputKnownValue",
    "OutputProbeSpec",
    "OutputRepresents",
    "OutputSpec",
    "ReplacementCase",
    "ReplacementLink",
    "ReplacementMigration",
    "ReplacementNode",
    "ReplacementPredicate",
    "ReplacementRule",
    "SearchVisibility",
    "SelectorSpec",
    "SlotValue",
    "SlotVariant",
    "SourceFilenameSpec",
    "StringWidget",
    "TextCompletionItem",
    "TextCompletionKind",
    "TextCompletions",
    "TypeExpr",
    "ValueTransform",
    "WidgetRepresentation",
    "WidgetRepresentations",
    "SCHEMA_WIRE_VERSION",
    "output_descriptor_entries",
    "schema_from_wire",
    "schema_signature",
    "schema_to_wire",
    # -- reporting and logging (dinkster-schema)
    "LOG_EVENT",
    "PREVIEW_EVENT",
    "PROGRESS_EVENT",
    "pack_logger",
    "report_event",
    "report_log",
    "report_preview",
    "report_progress",
    "report_value_diagnostic",
    # -- value types and codecs (dinkster-values)
    "CORE_BOOLEAN",
    "CORE_COMBO",
    "CORE_FLOAT",
    "CORE_INT",
    "CORE_STRING",
    "COST_META_KEY",
    "CURVE_TYPE",
    "DETECTION_TYPE",
    "IMAGE_BATCH_MERGER_ID",
    "INLINE_STRING_CAP",
    "LENGTH_META_KEY",
    "MAX_CURVE_POINTS",
    "MODEL3D_FILE_DECODER_ID",
    "PNG_CONTAINER_VERSION",
    "REGION_TYPE",
    "RESOURCES_META_KEY",
    "RESOURCE_ID_META_KEY",
    "SPLAT_FILE_DECODER_ID",
    "SPLAT_PLY_MIME",
    "BufferEncoding",
    "Curve",
    "Detection",
    "Region",
    "Rendition",
    "RenditionSpec",
    "ResourceHandle",
    "TypeId",
    "TypeRegistry",
    "TypeSpec",
    "register_curve_type",
    "AudioWindowReader",
    "append_audio_edit",
    "audio_channel_layout",
    "audio_fingerprint",
    "audio_from_source",
    "audio_meta",
    "audio_window",
    "effective_audio_facts",
    "coerce_detection",
    "coerce_region",
    "coerce_video",
    "decode_audio",
    "decode_detection",
    "decode_image_array",
    "decode_model3d",
    "decode_model3d_file",
    "decode_region",
    "decode_splat",
    "decode_splat_file",
    "decode_video",
    "detection_meta",
    "edit_video",
    "effective_video_facts",
    "encode_audio",
    "encode_detection",
    "encode_image_array",
    "encode_model3d",
    "encode_region",
    "encode_splat",
    "encode_video",
    "image_array_fingerprint",
    "image_array_meta",
    "annotate_image",
    "annotate_mask",
    "copy_media_semantics",
    "mask_array_meta",
    "media_semantics",
    "validate_image_encoded",
    "merge_image_batches",
    "model3d_fingerprint",
    "model3d_format",
    "model3d_meta",
    "parse_ply_splat",
    "prepare_image_array_encoding",
    "region_meta",
    "register_model3d_type",
    "register_resource_handle_type",
    "render_audio_wav",
    "render_image_png",
    "render_mask_png",
    "render_model3d_original",
    "render_splat_ply",
    "render_video_original",
    "splat_fingerprint",
    "splat_meta",
    "stable_hash",
    "validate_model3d_encoded",
    "validate_splat_encoded",
    "validate_video_encoded",
    "video_fingerprint",
    "video_from_source",
    "video_meta",
    "video_rendition_mime",
    # -- memory policy (dinkster-memory)
    "ConsumerItem",
    "FullReleaseResult",
    "InvocationView",
    "MeasuredMemory",
    "PressureSignal",
    "ReleaseCandidate",
    "ReservationPlanner",
    "ReservationRequest",
    "Shedder",
    # -- assets (dinkster-assets)
    "ASSET_TYPE",
    "SAVE_TARGET_TYPE",
    "AssetEntry",
    "AssetError",
    "AssetIntegrityError",
    "AssetRef",
    "AssetResolver",
    "AssetVault",
    "AssetWidget",
    "AssetWriter",
    "bind_video_value",
    "FolderListing",
    "IndexedAssetResolver",
    "MountSnapshotWriter",
    "SaveTarget",
    "SaveTargetWidget",
    "declared_asset",
    "digest_bytes",
    "digest_file",
    "is_digest",
    "register_asset_type",
    "register_save_target_type",
    "register_audio_value_type",
    "register_video_value_type",
    "resolver_from_env",
]
