"""Dinkster's deterministic first-party image and mask operation nodes."""

from .adjust import ADJUST_NODES, ImageAdjust
from .batch import (
    BATCH_NODES,
    ImageBatchCombine,
    ImageBatchEdit,
    ImageBatchToList,
    ImageListToBatch,
    ImageRebatch,
    MaskBatchCombine,
    MaskBatchEdit,
)
from .channels import (
    CHANNEL_NODES,
    ImageAlphaJoin,
    ImageAlphaPremultiply,
    ImageAlphaUnpremultiply,
    ImageChannelMerge,
    ImageChannelSplit,
)
from .compare import ImageCompare
from .composition import (
    COMPOSITION_NODES,
    ImageComposite,
    PorterDuffComposite,
)
from .compositor import (
    COMPOSITOR_NODES,
    AddLayer,
    CreateLayeredImage,
    LayersFromBoundingBoxes,
)
from .compositor_types import (
    BLEND_MODES as COMPOSITOR_BLEND_MODES,
)
from .compositor_types import (
    COMPOSITOR_TYPE,
    LAYERS_TYPE,
    CompositorLayer,
    CompositorRecipe,
    CompositorSourceLayer,
    CompositorTransform,
    LayerStack,
)
from .detection import (
    DETECTION_NODES,
    DetectionFilter,
    DetectionInfo,
    DetectionSort,
    DetectionsToMasks,
    MakeDetection,
)
from .drawing import DRAWING_NODES, DrawMask, DrawRegion, DrawText, MakeImage
from .filters import FILTER_NODES, ImageFilter
from .geometry import (
    GEOMETRY_NODES,
    ImageCrop,
    ImageInfo,
    ImageResize,
    ImageTransform,
    ImageUncrop,
    MakeRegion,
    RegionInfo,
)
from .glsl import DEFAULT_FRAGMENT_SHADER, GLSL_NODES, GlslShader
from .layer_document import LAYER_DOCUMENT_NODES, EditLayers, FlattenLayers, SplitLayers
from .layer_io import LoadLayers, SaveLayers
from .layout import LAYOUT_NODES, ImageGridCompose, ImageGridDecompose, ImageStitch
from .mask import (
    MASK_NODES,
    ImageToMask,
    MakeMask,
    MaskCombine,
    MaskInfo,
    MaskMorphology,
    MaskPolarity,
    MaskToImage,
    TextMask,
)
from .pose import POSE_NODES, ExportPoseJson, ImportPoseJson, RenderPose
from .preprocess import (
    MODEL_DEPTH_PROVIDER_CHOICE,
    MODEL_EDGE_PROVIDER_CHOICE,
    MODEL_EDGE_PROVIDER_CHOICES,
    PREPROCESSOR_NODES,
    AnimeLineartPreprocessor,
    AnyLinePreprocessor,
    BinaryPreprocessor,
    ColorHintPreprocessor,
    ContentShufflePreprocessor,
    EdgePreprocessor,
    HintImageResize,
    HintResolution,
    InpaintHintPreprocessor,
    LineartPreprocessor,
    MangaLineartPreprocessor,
    MLSDPreprocessor,
    ModelDepthPreprocessor,
    ModelEdgePreprocessor,
    RealisticLineartPreprocessor,
    ScribblePreprocessor,
    TEEDPreprocessor,
    TileHintPreprocessor,
    preprocessor_choices,
)
from .refine import REFINE_NODES, TileBlendMask, TileRefinePlan
from .tiles import TILE_NODES, ImageTileMerge, ImageTileSplit
from .tracking import TRACKING_NODES, TrackedCrop, TrackedUncrop
from .transition import TRANSITION_NODES, ImageTransition
from .types import (
    DETECTION_TYPE,
    POSE_TYPE,
    REGION_TYPE,
    RESERVED_TYPE_IDS,
    SEGMENTATION_TYPE,
    VECTOR_TYPE,
    Detection,
    Pose,
    PoseKeypoint,
    PoseSkeleton,
    Region,
    register_image_types,
)
from .upscale import (
    UPSCALE_MODEL_PROVIDER_CHOICE,
    UPSCALE_NODES,
    UpscaleWithModel,
    upscale_choices,
)
from .vision import (
    DETECT_PROVIDER_CHOICE,
    MATTE_PROVIDER_CHOICE,
    SEGMENT_PROVIDER_CHOICE,
    TEXT_SEGMENT_PROVIDER_CHOICE,
    TRACK_PROVIDER_CHOICE,
    VISION_NODES,
    DetectObjects,
    ImageMatte,
    SegmentByText,
    SegmentDetections,
    TrackObjects,
    vision_choices,
)

IMAGE_NODES = [
    ImageCompare,
    *GEOMETRY_NODES,
    *COMPOSITION_NODES,
    *COMPOSITOR_NODES,
    *LAYER_DOCUMENT_NODES,
    LoadLayers,
    SaveLayers,
    *GLSL_NODES,
    *ADJUST_NODES,
    *FILTER_NODES,
    *PREPROCESSOR_NODES,
    *POSE_NODES,
    *CHANNEL_NODES,
    *MASK_NODES,
    *DETECTION_NODES,
    *DRAWING_NODES,
    *BATCH_NODES,
    *LAYOUT_NODES,
    *TILE_NODES,
    *TRACKING_NODES,
    *REFINE_NODES,
    *TRANSITION_NODES,
    *UPSCALE_NODES,
    *VISION_NODES,
]


def image_choices() -> dict[str, tuple[str, ...]]:
    """Every static remote choice this pack owns."""
    return {**preprocessor_choices(), **upscale_choices(), **vision_choices()}


__all__ = [
    "ADJUST_NODES",
    "AnimeLineartPreprocessor",
    "AnyLinePreprocessor",
    "BATCH_NODES",
    "CHANNEL_NODES",
    "COMPOSITION_NODES",
    "COMPOSITOR_BLEND_MODES",
    "COMPOSITOR_NODES",
    "COMPOSITOR_TYPE",
    "DETECTION_NODES",
    "DETECTION_TYPE",
    "DETECT_PROVIDER_CHOICE",
    "DRAWING_NODES",
    "FILTER_NODES",
    "GEOMETRY_NODES",
    "GLSL_NODES",
    "IMAGE_NODES",
    "EditLayers",
    "FlattenLayers",
    "LoadLayers",
    "SaveLayers",
    "SplitLayers",
    "LAYERS_TYPE",
    "LAYOUT_NODES",
    "MASK_NODES",
    "MATTE_PROVIDER_CHOICE",
    "MODEL_DEPTH_PROVIDER_CHOICE",
    "MODEL_EDGE_PROVIDER_CHOICE",
    "MODEL_EDGE_PROVIDER_CHOICES",
    "POSE_NODES",
    "POSE_TYPE",
    "PREPROCESSOR_NODES",
    "REFINE_NODES",
    "REGION_TYPE",
    "RESERVED_TYPE_IDS",
    "SEGMENTATION_TYPE",
    "SEGMENT_PROVIDER_CHOICE",
    "TEXT_SEGMENT_PROVIDER_CHOICE",
    "TILE_NODES",
    "TRACKING_NODES",
    "TRACK_PROVIDER_CHOICE",
    "TRANSITION_NODES",
    "UPSCALE_MODEL_PROVIDER_CHOICE",
    "UPSCALE_NODES",
    "VECTOR_TYPE",
    "VISION_NODES",
    "BinaryPreprocessor",
    "ColorHintPreprocessor",
    "ContentShufflePreprocessor",
    "CompositorLayer",
    "CompositorRecipe",
    "CompositorSourceLayer",
    "CompositorTransform",
    "CreateLayeredImage",
    "DEFAULT_FRAGMENT_SHADER",
    "DetectObjects",
    "Detection",
    "DetectionFilter",
    "DetectionInfo",
    "DetectionSort",
    "DetectionsToMasks",
    "EdgePreprocessor",
    "HintImageResize",
    "HintResolution",
    "ImageAdjust",
    "ImageAlphaJoin",
    "ImageAlphaPremultiply",
    "ImageAlphaUnpremultiply",
    "AddLayer",
    "ImageChannelMerge",
    "ImageChannelSplit",
    "ImageCompare",
    "ImageComposite",
    "ImageCrop",
    "ImageBatchCombine",
    "ImageBatchEdit",
    "ImageBatchToList",
    "ImageGridCompose",
    "ImageGridDecompose",
    "GlslShader",
    "ImageListToBatch",
    "ImageMatte",
    "ImageRebatch",
    "ImageStitch",
    "ImageTileMerge",
    "ImageTileSplit",
    "ImageToMask",
    "ImageTransition",
    "DrawMask",
    "DrawRegion",
    "DrawText",
    "ImageFilter",
    "ImageInfo",
    "ImageResize",
    "ImageTransform",
    "ImageUncrop",
    "InpaintHintPreprocessor",
    "LineartPreprocessor",
    "LayerStack",
    "LayersFromBoundingBoxes",
    "MLSDPreprocessor",
    "MangaLineartPreprocessor",
    "MakeDetection",
    "MakeRegion",
    "RegionInfo",
    "MakeImage",
    "MakeMask",
    "MaskCombine",
    "MaskBatchCombine",
    "MaskBatchEdit",
    "MaskInfo",
    "MaskMorphology",
    "MaskPolarity",
    "MaskToImage",
    "ModelDepthPreprocessor",
    "ModelEdgePreprocessor",
    "RealisticLineartPreprocessor",
    "PorterDuffComposite",
    "Pose",
    "PoseKeypoint",
    "PoseSkeleton",
    "Region",
    "RenderPose",
    "ScribblePreprocessor",
    "TEEDPreprocessor",
    "SegmentByText",
    "SegmentDetections",
    "TextMask",
    "TileBlendMask",
    "TileHintPreprocessor",
    "TileRefinePlan",
    "TrackObjects",
    "TrackedCrop",
    "TrackedUncrop",
    "ExportPoseJson",
    "ImportPoseJson",
    "UpscaleWithModel",
    "image_choices",
    "preprocessor_choices",
    "register_image_types",
    "upscale_choices",
    "vision_choices",
]
