"""Replay pinned ComfyUI e20d433a audio goldens through the native audio nodes.

The fixture (tests/goldens/audio_io_e20d433a.json, generated by
tools/gen_audio_io_goldens.py) stores the exact bytes fed to the pinned code
plus its outputs, so these tests replay identical inputs: the WAV load case
proves bit-exact decoder parity, FLAC and MP3 saves must decode to identical
samples, and Opus saves stay within a measured lossy-encoder tolerance.
"""

from __future__ import annotations

import base64
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, cast

import numpy as np
import pytest
from dinkster_assets import AssetRef, AssetVault, digest_bytes
from dinkster_nodes_media_io import EmptyAudio, LoadAudio, SaveAudio, SaveAudioMP3, SaveAudioOpus

_GOLDENS = cast(
    "dict[str, Any]",
    json.loads((Path(__file__).parent / "goldens" / "audio_io_e20d433a.json").read_text("utf-8")),
)
_CASES = cast("dict[str, Any]", _GOLDENS["cases"])
_MEDIA_TYPES = {"wav": "audio/wav", "flac": "audio/flac", "mp3": "audio/mpeg", "opus": "audio/ogg"}

# Decoded Opus differs from the pinned encoder by two lossy mechanisms with no
# effect on shape or rate: libopus version delta (measured max abs diff 0.0127
# at a native 16 kHz rate) and resampler choice for coerced rates, torchaudio
# upstream versus av.AudioResampler here (measured 0.0439 at 44.1 kHz -> 48 kHz).
OPUS_MAX_ABS_DIFF = 0.05

# The av 16.0.1 darwin arm64 wheel bundles a different FFmpeg build of the same
# library versions (libavcodec 62.11.100), so lossy codec byte streams differ
# from the Linux/Windows wheels while staying deterministic. All values below
# were observed dual-run bit-stable on Apple M4 (darwin, Python 3.12.11,
# numpy 2.5.1, av 16.0.1). Mechanisms per case:
# - FLAC: decoding the pinned bytes is bit-exact (no digest override); only the
#   encoder's float -> s16 conversion resolves 6 rounding ties differently
#   (every nonzero roundtrip delta is exactly 2**-15, one 16-bit LSB).
# - MP3: decoder and LAME encoder both differ (roundtrip max abs diff vs the
#   pinned encode decoded on darwin: 7.01e-05 for V0 mono, 1.54e-03 for 320k
#   stereo), so the roundtrip pins the darwin decode digest instead.
# - Opus: only the decoder digest differs; the roundtrip stays within
#   OPUS_MAX_ABS_DIFF (measured 0.0429 stereo, 0.0143 mono).
_DARWIN_DECODED_SHA256 = {
    "save_mp3_v0_mono_44100": ("1f5de7dce2ca445b1ea9f0ac95076521123c8e252748ed71453249b1b68c4519"),
    "save_mp3_320k_stereo_48000": (
        "3fca5b6b16243e369b8ba51cd3cfef525da911a1d90d1473a0363529af268bc2"
    ),
    "save_opus_128k_stereo_44100": (
        "5121787f451351eb0ec3246e4fcbecb3bd043400c44be61c45c7a744d477c2a0"
    ),
    "save_opus_64k_mono_16000": (
        "6a6353e8cbadcb006531dfa7c3c55a1ac5009889319733c0d6a62a9328b487dd"
    ),
}
_DARWIN_ROUNDTRIP_SHA256 = {
    "save_flac_stereo_44100": ("9e9b4e2123b1ba515fd2911a843bc753873af20808f51b2e5f7b9af47f314237"),
    "save_mp3_v0_mono_44100": ("ef3eb820dcb59945a81d31ad6b7e2b01cec80d3589ca2df5bfb4dc83df7d19eb"),
    "save_mp3_320k_stereo_48000": (
        "1eb8b81cba35319730a95a2faa1d607f1711a359f8304cda3d1e75b6bbf83b2d"
    ),
}


def _load(tmp_path: Path, data: bytes, name: str) -> tuple[np.ndarray, int]:
    vault = AssetVault(tmp_path / "vault")
    digest = digest_bytes(data)
    with vault.writer(digest) as writer:
        writer.write(data)
        writer.commit()
    media_type = _MEDIA_TYPES[name.rsplit(".", 1)[1]]
    ref = AssetRef(digest, name, len(data), media_type, resolver=vault)
    loaded = cast("dict[str, Any]", LoadAudio.execute(audio=ref)["audio"])
    return cast(np.ndarray, loaded["waveform"])[0], int(cast(int, loaded["sample_rate"]))


def _digest(waveform: np.ndarray) -> str:
    return hashlib.sha256(np.ascontiguousarray(waveform, dtype=np.float32).tobytes()).hexdigest()


def _golden_audio(case: dict[str, Any]) -> dict[str, object]:
    flat = np.frombuffer(base64.b64decode(case["waveformB64"]), dtype=np.float32)
    waveform = flat.reshape(case["waveformShape"])[None, ...]
    return {"waveform": np.ascontiguousarray(waveform), "sample_rate": case["sampleRate"]}


def _save_and_reload(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    node: type[Any],
    case: dict[str, Any],
    kwargs: dict[str, str],
    suffix: str,
) -> tuple[np.ndarray, int]:
    root = tmp_path / "out"
    root.mkdir()
    index = root / ".dinkster-asset-index.json"
    index.write_text("{}", "utf-8")
    snapshot = tmp_path / "mounts.json"
    snapshot.write_text(
        json.dumps(
            {
                "mounts": [
                    {
                        "id": "comfy-output",
                        "root": str(root),
                        "index": str(index),
                        "mode": "readwrite",
                    }
                ]
            }
        ),
        "utf-8",
    )
    monkeypatch.setenv("DINKSTER_MOUNTS_SNAPSHOT", str(snapshot))
    result = node.execute(
        audio=_golden_audio(case),
        target={"mount": "comfy-output", "prefix": "audio/golden"},
        **kwargs,
    )
    refs = cast("list[AssetRef]", result["audios"])
    assert len(refs) == 1
    return _load(tmp_path, (root / "audio" / refs[0].name).read_bytes(), f"dinkster{suffix}")


def _pinned_decode(
    tmp_path: Path, name: str, case: dict[str, Any], suffix: str
) -> tuple[np.ndarray, int]:
    """Decode the pinned encoder's exact bytes and prove decoder parity."""
    decoded, rate = _load(tmp_path, base64.b64decode(case["encodedB64"]), f"pinned{suffix}")
    assert rate == case["decodedRate"]
    assert list(decoded.shape) == case["decodedShape"]
    expected = case["decodedSha256"]
    if sys.platform == "darwin":
        expected = _DARWIN_DECODED_SHA256.get(name, expected)
    assert _digest(decoded) == expected
    return decoded, rate


def test_load_wav_decodes_bit_exactly_to_pinned_loader(tmp_path: Path) -> None:
    case = _CASES["load_wav_stereo_44100"]
    waveform, rate = _load(tmp_path, base64.b64decode(case["wavB64"]), "golden.wav")
    assert rate == case["decodedRate"]
    assert list(waveform.shape) == case["decodedShape"]
    assert _digest(waveform) == case["decodedSha256"]


@pytest.mark.parametrize(
    ("name", "node", "kwargs", "suffix"),
    [
        ("save_flac_stereo_44100", SaveAudio, {}, ".flac"),
        ("save_mp3_v0_mono_44100", SaveAudioMP3, {"quality": "V0"}, ".mp3"),
        ("save_mp3_320k_stereo_48000", SaveAudioMP3, {"quality": "320k"}, ".mp3"),
    ],
)
def test_flac_and_mp3_saves_decode_identically_to_pinned_encodes(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    name: str,
    node: type[Any],
    kwargs: dict[str, str],
    suffix: str,
) -> None:
    case = _CASES[name]
    pinned, pinned_rate = _pinned_decode(tmp_path, name, case, suffix)
    ours, our_rate = _save_and_reload(tmp_path, monkeypatch, node, case, kwargs, suffix)
    assert our_rate == pinned_rate
    assert ours.shape == pinned.shape
    if sys.platform == "darwin":
        assert _digest(ours) == _DARWIN_ROUNDTRIP_SHA256[name]
    else:
        assert float(np.abs(ours - pinned).max()) == 0.0


@pytest.mark.parametrize("name", ["save_opus_128k_stereo_44100", "save_opus_64k_mono_16000"])
def test_opus_saves_decode_within_measured_tolerance(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, name: str
) -> None:
    case = _CASES[name]
    pinned, pinned_rate = _pinned_decode(tmp_path, name, case, ".opus")
    ours, our_rate = _save_and_reload(
        tmp_path, monkeypatch, SaveAudioOpus, case, {"quality": case["quality"]}, ".opus"
    )
    assert our_rate == pinned_rate == 48_000
    assert ours.shape == pinned.shape
    assert float(np.abs(ours - pinned).max()) <= OPUS_MAX_ABS_DIFF


def test_empty_audio_matches_pinned_shapes_and_rates() -> None:
    for case in cast("list[dict[str, Any]]", _CASES["empty_audio"]):
        result = EmptyAudio.execute(
            duration=case["duration"],
            sample_rate=case["sampleRate"],
            channels=case["channels"],
        )
        value = cast("dict[str, Any]", result["audio"])
        waveform = cast(np.ndarray, value["waveform"])
        assert list(waveform.shape) == case["shape"]
        assert value["sample_rate"] == case["outputRate"]
        assert not bool(waveform.any())
