"""Golden parity for AlignYourSteps, GITS, and OptimalSteps schedulers.

Goldens were generated by tools/gen_model_aware_scheduler_goldens.py running
the reference comfy_extras node code at the pinned ComfyUI commit; the node
outputs here must match bit for bit.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import pytest
from dinkster_native import native_arm as arm

_GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "model_aware_scheduler_goldens.json").read_text()
)


def _values(output: Mapping[str, object]) -> tuple[float, ...]:
    value = output["sigmas"]
    assert type(value) is arm._CustomSigmasValue
    return value.values


def test_goldens_come_from_pinned_reference() -> None:
    assert _GOLDENS["provenance"]["comfyui_commit"] == "b78cec879b9460d5cb25228a83a942fb78d2cd24"


@pytest.mark.parametrize("case", _GOLDENS["align_your_steps"], ids=str)
def test_align_your_steps_matches_reference(case: Mapping[str, Any]) -> None:
    output = arm.GenerationAlignYourStepsScheduler.execute(
        model_type=case["model_type"],
        steps=case["steps"],
        denoise=case["denoise"],
    )
    assert _values(output) == tuple(case["sigmas"])


@pytest.mark.parametrize("case", _GOLDENS["gits"], ids=str)
def test_gits_matches_reference(case: Mapping[str, Any]) -> None:
    output = arm.GenerationGITSScheduler.execute(
        coeff=case["coeff"],
        steps=case["steps"],
        denoise=case["denoise"],
    )
    assert _values(output) == tuple(case["sigmas"])


@pytest.mark.parametrize("case", _GOLDENS["optimal_steps"], ids=str)
def test_optimal_steps_matches_reference(case: Mapping[str, Any]) -> None:
    output = arm.GenerationOptimalStepsScheduler.execute(
        model_type=case["model_type"],
        steps=case["steps"],
        denoise=case["denoise"],
    )
    assert _values(output) == tuple(case["sigmas"])


def test_denoise_zero_returns_empty_sigmas() -> None:
    assert (
        _values(
            arm.GenerationAlignYourStepsScheduler.execute(model_type="SD1", steps=10, denoise=0.0)
        )
        == ()
    )
    assert _values(arm.GenerationGITSScheduler.execute(coeff=1.2, steps=10, denoise=0.0)) == ()
    assert (
        _values(
            arm.GenerationOptimalStepsScheduler.execute(model_type="FLUX", steps=20, denoise=0.0)
        )
        == ()
    )


def test_invalid_inputs_raise() -> None:
    with pytest.raises(ValueError, match="model_type"):
        arm.GenerationAlignYourStepsScheduler.execute(model_type="SD3", steps=10, denoise=1.0)
    with pytest.raises(ValueError, match="steps"):
        arm.GenerationAlignYourStepsScheduler.execute(model_type="SD1", steps=0, denoise=1.0)
    with pytest.raises(ValueError, match="coeff"):
        arm.GenerationGITSScheduler.execute(coeff=0.77, steps=10, denoise=1.0)
    with pytest.raises(ValueError, match="steps"):
        arm.GenerationGITSScheduler.execute(coeff=1.2, steps=1, denoise=1.0)
    with pytest.raises(ValueError, match="model_type"):
        arm.GenerationOptimalStepsScheduler.execute(model_type="SD1", steps=20, denoise=1.0)
    with pytest.raises(ValueError, match="steps"):
        arm.GenerationOptimalStepsScheduler.execute(model_type="FLUX", steps=2, denoise=1.0)
    with pytest.raises(ValueError, match="denoise"):
        arm.GenerationGITSScheduler.execute(coeff=1.2, steps=10, denoise=1.5)
    with pytest.raises(ValueError, match="coeff"):
        arm.GenerationGITSScheduler.execute(coeff=0.795, steps=10, denoise=1.0)
    with pytest.raises(ValueError, match="coeff"):
        arm.GenerationGITSScheduler.execute(coeff=1.505, steps=10, denoise=1.0)


def test_gits_coeff_rounds_to_table_key() -> None:
    exact = arm.GenerationGITSScheduler.execute(coeff=1.20, steps=10, denoise=1.0)
    nearby = arm.GenerationGITSScheduler.execute(coeff=1.201, steps=10, denoise=1.0)
    assert _values(exact) == _values(nearby)
