"""Exact Ovis Qwen3-2B header and prompt-policy closure.

The golden is generated by executing ComfyUI at b78cec87 through
tools/gen_ovis_text_goldens.py. It pins the full model layout and the
fixed-template tokenizer behavior, including disabled prompt weights,
right padding, attention masks, and the post-template slice marker.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    BFLOAT16,
    OVIS_QWEN3_2B_CONFIG,
    QwenTextDetectError,
    TensorGeometry,
    detect_qwen_text_config,
    qwen_text_layout,
    tokenize_ovis_prompt,
)

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "ovis_text_goldens.json").read_text())
WORKLOADS = json.loads(
    (Path(__file__).parent.parent / "tools" / "inference_parity" / "workloads.json").read_text()
)


def exact_geometries() -> dict[str, TensorGeometry]:
    return {key: TensorGeometry(tuple(shape), BFLOAT16) for key, shape in GOLDENS["layout"]}


def test_full_layout_matches_executed_reference() -> None:
    expected = [(key, tuple(shape)) for key, shape in GOLDENS["layout"]]
    assert sorted(qwen_text_layout(OVIS_QWEN3_2B_CONFIG).items()) == expected
    assert detect_qwen_text_config(exact_geometries()) is OVIS_QWEN3_2B_CONFIG


def test_wrong_width_refuses() -> None:
    geometries = exact_geometries()
    geometries["embed_tokens.weight"] = TensorGeometry((151936, 3584), BFLOAT16)
    with pytest.raises(QwenTextDetectError, match="unknown Qwen text width"):
        detect_qwen_text_config(geometries)


def test_wrong_role_refuses() -> None:
    with pytest.raises(QwenTextDetectError, match="not a Qwen text-model role"):
        detect_qwen_text_config(
            {"vision_model.patch_embed.weight": TensorGeometry((8, 8), BFLOAT16)}
        )


def test_missing_or_extra_model_key_refuses_strictly() -> None:
    missing = exact_geometries()
    del missing["layers.27.mlp.down_proj.weight"]
    with pytest.raises(QwenTextDetectError, match="missing layers.27"):
        detect_qwen_text_config(missing)

    extra = exact_geometries()
    extra["lm_head.weight"] = TensorGeometry((151936, 2048), BFLOAT16)
    with pytest.raises(QwenTextDetectError, match="unexpected key lm_head.weight"):
        detect_qwen_text_config(extra)


@pytest.mark.parametrize("case", GOLDENS["tokenizer"], ids=lambda case: case["text"])
def test_tokenizer_matches_executed_reference(case: dict[str, Any]) -> None:
    got = tokenize_ovis_prompt(str(case["text"]))
    assert list(got.ids) == case["ids"]
    assert list(got.attention_mask) == case["attention_mask"]
    assert set(case["weights"]) == {1.0}


def test_template_padding_mask_and_post_template_slice() -> None:
    tokens = tokenize_ovis_prompt("cat")
    assert len(tokens.ids) == OVIS_QWEN3_2B_CONFIG.min_tokens == 284
    assert tokens.ids[-1] == OVIS_QWEN3_2B_CONFIG.pad_token_id
    assert tokens.attention_mask[-1] == 0
    assert tokens.ids[tokens.slice_start - 1 : tokens.slice_start + 1] == (4004, 25)
    assert tokens.slice_start == 28


def test_prompt_weight_syntax_is_literal() -> None:
    plain = tokenize_ovis_prompt("cat")
    weighted_syntax = tokenize_ovis_prompt("(cat:2.0)")
    assert plain.ids != weighted_syntax.ids
    case = next(item for item in GOLDENS["tokenizer"] if item["text"] == "(cat:2.0)")
    assert set(case["weights"]) == {1.0}


def test_escaped_parentheses_and_embedding_boundaries_match_reference() -> None:
    for text in (r"\(cat:1.2\)", "a embedding:foo"):
        case = next(item for item in GOLDENS["tokenizer"] if item["text"] == text)
        assert list(tokenize_ovis_prompt(text).ids) == case["ids"]


def test_literal_pad_token_starts_reference_attention_masking() -> None:
    tokens = tokenize_ovis_prompt("<|endoftext|> masked tail")
    first_pad = tokens.ids.index(OVIS_QWEN3_2B_CONFIG.pad_token_id)
    assert tokens.attention_mask[first_pad - 1 : first_pad + 2] == (1, 0, 0)


def test_vendored_tokenizer_is_deterministic() -> None:
    first = tokenize_ovis_prompt("cafe\u0301 \u4e2d")
    second = tokenize_ovis_prompt("cafe\u0301 \u4e2d")
    assert first == second


def test_adversarial_tokenizer_corpus_matches_executed_reference() -> None:
    outputs = [
        [list(tokenize_ovis_prompt(str(text)).ids)]
        for text in GOLDENS["tokenizer_corpus"]["prompts"]
    ]
    canonical = json.dumps(outputs, separators=(",", ":")).encode("ascii")
    assert (
        hashlib.sha256(canonical).hexdigest() == (GOLDENS["tokenizer_corpus"]["token_ids_sha256"])
    )


def test_workload_manifest_closes_accepted_artifact_list() -> None:
    component_ids = {item["id"] for item in WORKLOADS["component_artifacts"]}
    assert component_ids == {
        "longcat-image-bf16-diffusion",
        "longcat-qwen-2.5-vl-7b-fp8-text",
    }
    workload = next(
        item for item in WORKLOADS["workloads"] if item["id"] == "W0-FLUX-GATED-OVIS-TXT2IMG"
    )
    artifacts = {item["role"]: item for item in workload["artifacts"]}
    assert workload["execution"]["precision"]["text"] == {
        "compute": "float32",
        "storage": "bfloat16",
    }
    assert {role: item["digest"] for role, item in artifacts.items()} == {
        "flux-16-channel-kl-codec": (
            "sha256:afc8e28272cd15db3919bacdb6918ce9c1ed22e96cb12c4d5ed0fba823529e38"
        ),
        "ovis-qwen3-2b-text-encoder": (
            "sha256:f453ee5e7a25cb23cf2adf7aae3e5b405f22097cb67f2cfcca029688cb3f740d"
        ),
        "ovis-vector-free-gated-txt-norm-flux-diffusion": (
            "sha256:eb3d9e1b201412b3b527472cf82a2c5add6b5a40a37e94d99f11c381f18a9e2b"
        ),
    }
    assert artifacts["ovis-qwen3-2b-text-encoder"]["layout"]["embedding"] == (
        "model.embed_tokens.weight [151936, 2048]"
    )


def test_ovis_and_txt_norm_workloads_name_exact_vector_free_trigger() -> None:
    workload = next(
        item for item in WORKLOADS["workloads"] if item["id"] == "W0-FLUX-GATED-OVIS-TXT2IMG"
    )
    assert workload["provenance"]["fired_trigger"] == ("W0-FLUX-VECTOR-FREE landed at 272e842")
    assert set(workload["provenance"]["discharged_deferrals"]) == {
        "W0-FLUX-GATED-OVIS-TWO-PHASE",
        "W0-FLUX-TXT-NORM-TWO-PHASE",
    }
    artifacts = {item["role"]: item for item in workload["artifacts"]}
    diffusion_layout = artifacts["ovis-vector-free-gated-txt-norm-flux-diffusion"]["layout"]
    assert diffusion_layout["text_input"] == "txt_in.weight [3072, 2048]"
    assert diffusion_layout["text_normalization"] == "txt_norm.scale [2048]"
    assert diffusion_layout["vector_input"] == "absent"
    assert diffusion_layout["guidance_input"] == "absent"
    component_ids = {item["id"] for item in WORKLOADS["component_artifacts"]}
    assert not component_ids.intersection(
        {"ovis-2.5-qwen3-2b-text", "ovis-image-bf16-diffusion", "flux-ae-kl-codec"}
    )
    assert WORKLOADS["deferred_workloads"] == []
    longcat = {item["id"]: item for item in WORKLOADS["component_artifacts"]}
    diffusion = longcat["longcat-image-bf16-diffusion"]
    text = longcat["longcat-qwen-2.5-vl-7b-fp8-text"]
    assert diffusion["status"] == "accepted-component-layout"
    assert text["status"] == "accepted-component-layout"
    assert "deferral" not in diffusion
    assert "deferral" not in text
    assert diffusion["follow_up_deferral"] == text["follow_up_deferral"]
    assert diffusion["follow_up_deferral"]["name"] == "W0-LONGCAT-EXECUTION"
    expected_provenance = {
        "download_date": "2026-07-30",
        "template_commit": "aa3661d9fc1a493f8de6b029f5b8af27da3c5d08",
        "template_digest": (
            "sha256:30f5a89de5e516a36b47d7bbb912c6901079064ba4f9b31bcda43188103450a4"
        ),
        "upstream_reference_commit": "9cf91339b708a245762fa38ffeec9702b381e0db",
        "verified_on": "RipperPC",
    }
    assert diffusion["provenance"] == expected_provenance
    assert text["provenance"] == expected_provenance

    diffusion_layout = diffusion["layout"]
    assert diffusion_layout["key_count"] == 412
    assert diffusion_layout["dtype"] == "bfloat16"
    assert diffusion_layout["text_input"] == "txt_in.weight [3072, 3584]"
    assert diffusion_layout["block_structure"] == "10 double blocks and 20 single blocks"
    assert diffusion_layout["single_block_mlp"] == (
        "linear1.weight [21504, 3072]; linear2.weight [3072, 15360]"
    )
    assert diffusion_layout["image_input"] == "img_in.weight [3072, 64]"

    text_layout = text["layout"]
    assert text_layout["key_count"] == 1446
    assert text_layout["model_subtree_keys"] == 730
    assert text_layout["embedding"] == "model.embed_tokens.weight [152064, 3584] bfloat16"
    assert text_layout["scaled_fp8"] == (
        "F8_E4M3 weights; each of 358 linear weights has scalar float32 .scale_weight and "
        ".scale_input; zero-length scaled_fp8 marker"
    )
    assert text_layout["visual_subtree_keys"] == 714
    assert text_layout["root_lm_head"] == (
        "lm_head.weight [152064, 3584] bfloat16; present but not instantiated by upstream encoder"
    )


@pytest.mark.skipif(
    not Path("/home/kosin/ComfyUI/models/vae/ae.safetensors").exists(),
    reason="accepted Flux KL artifact absent",
)
def test_local_accepted_flux_codec_matches_manifest_content_digest() -> None:
    path = Path("/home/kosin/ComfyUI/models/vae/ae.safetensors")
    with path.open("rb") as handle:
        digest = hashlib.file_digest(handle, "sha256").hexdigest()
    assert digest == "afc8e28272cd15db3919bacdb6918ce9c1ed22e96cb12c4d5ed0fba823529e38"
