"""Native inference stage 5 slice 3: CLIP tokenization, torch-free.

Every port is pinned against goldens generated by RUNNING the ComfyUI
reference @ 947c2749 (tests/goldens/clip_tokenizer_goldens.json,
produced by tools/gen_clip_tokenizer_goldens.py with the reference
interpreter): Hugging Face CLIPTokenizer output for raw BPE ids, and
SDTokenizer/SDXLClipGTokenizer tokenize_with_weights for the grammar
and chunk packing. Token ids, weights (bit-exact floats), and word
ids all must match. Tensor tokens appear in the goldens as
``{"emb": name, "row": r}`` markers.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    CLIP_BOS,
    CLIP_EOS,
    CLIP_G_PROFILE,
    CLIP_L_PROFILE,
    CLIP_VOCAB_SIZE,
    ClipBpe,
    EmbeddingRef,
    EmbeddingSlot,
    PackedToken,
    PromptTokenizer,
    Tokenizer,
    TokenizerProfile,
    WeightedSpan,
    load_clip_bpe,
    pack_spans,
    parse_prompt_weights,
    tokenize_prompt,
)

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "clip_tokenizer_goldens.json").read_text()
)

FIXTURE_ROWS: dict[str, int] = GOLDENS["embedding_fixtures"]

BPE = load_clip_bpe()


def resolve_fixture(name: str) -> int | None:
    return FIXTURE_ROWS.get(name)


def chunks_to_json(chunks) -> list[list[list[Any]]]:
    out = []
    for chunk in chunks:
        row: list[list[Any]] = []
        for item in chunk:
            if isinstance(item.unit, EmbeddingSlot):
                row.append(
                    [{"emb": item.unit.name, "row": item.unit.row}, item.weight, item.word_id]
                )
            else:
                row.append([item.unit, item.weight, item.word_id])
        out.append(row)
    return out


def reference_pack(
    text: str,
    profile: TokenizerProfile,
    resolve=None,
) -> list[list[list[Any]]]:
    tokenized = tokenize_prompt(text, encode_word=BPE.encode, resolve=resolve)
    return chunks_to_json(pack_spans(tokenized.spans, profile, resolve=resolve))


# ---------------------------------------------------------------- BPE


@pytest.mark.parametrize("case", GOLDENS["bpe"], ids=lambda c: repr(c["text"][:30]))
def test_bpe_matches_reference_tokenizer(case: dict[str, Any]) -> None:
    assert [CLIP_BOS, *BPE.encode(case["text"]), CLIP_EOS] == case["ids"]


def test_vendored_data_hash_guard() -> None:
    fresh = ClipBpe.from_vendored_data()
    assert fresh.encode("a photo of a cat") == BPE.encode("a photo of a cat")


def test_vendored_data_hash_mismatch_is_loud() -> None:
    from dinkster_inference.vendored import read_vendored

    with pytest.raises(ValueError, match="hash mismatch"):
        read_vendored("clip_vocab.json.gz", "0" * 64)


def test_vocab_constants_match_vendored_data() -> None:
    import gzip
    from importlib import resources

    vocab = json.loads(
        gzip.decompress(
            resources.files("dinkster_inference.data").joinpath("clip_vocab.json.gz").read_bytes()
        )
    )
    assert len(vocab) == CLIP_VOCAB_SIZE
    assert vocab["<|startoftext|>"] == CLIP_BOS
    assert vocab["<|endoftext|>"] == CLIP_EOS


# ----------------------------------------------------------- grammar


def test_nested_default_weight_is_exact_float_product() -> None:
    segments = parse_prompt_weights("((deep))")
    assert segments == (("deep", 1.1 * 1.1),)


def test_explicit_weight_replaces_inherited_weight() -> None:
    segments = parse_prompt_weights("(outer (inner:2.0) rest:1.5)")
    assert ("inner", 2.0) in segments
    assert all(w != 1.5 * 2.0 for _, w in segments)


def test_escaped_parens_are_literal_text() -> None:
    segments = parse_prompt_weights("\\(literal\\) (weighted)")
    assert segments[0] == ("(literal) ", 1.0)
    assert segments[1] == ("weighted", 1.1)


def test_disable_weights_is_single_segment() -> None:
    segments = parse_prompt_weights("(x:2.0) y", disable_weights=True)
    assert segments == (("(x:2.0) y", 1.0),)


# ----------------------------------------- weighted packing goldens


@pytest.mark.parametrize("case", GOLDENS["weighted"], ids=lambda c: repr(c["text"][:30]))
def test_weighted_packing_matches_reference(case: dict[str, Any]) -> None:
    assert reference_pack(case["text"], CLIP_L_PROFILE) == case["l"]
    assert reference_pack(case["text"], CLIP_G_PROFILE) == case["g"]


@pytest.mark.parametrize("case", GOLDENS["variants"], ids=lambda c: json.dumps(c["params"]))
def test_packing_variants_match_reference(case: dict[str, Any]) -> None:
    profile = TokenizerProfile(**case["params"])
    assert reference_pack(case["text"], profile) == case["chunks"]


# ------------------------------------------------ embedding goldens


@pytest.mark.parametrize("case", GOLDENS["embeddings"], ids=lambda c: repr(c["text"][:30]))
def test_embedding_directives_match_reference(case: dict[str, Any]) -> None:
    assert reference_pack(case["text"], CLIP_L_PROFILE, resolve=resolve_fixture) == case["chunks"]


def test_missing_embedding_is_reported_not_silent() -> None:
    tokenized = tokenize_prompt(
        "a embedding:nosuch b", encode_word=BPE.encode, resolve=resolve_fixture
    )
    assert tokenized.missing_embeddings == ("nosuch",)


def test_bare_directive_is_missing_not_a_crash() -> None:
    # The reference raises IndexError here (docs/comfyui-issues/
    # sd1-clip-bare-embedding-directive-crash.md); Dinkster reports it.
    tokenized = tokenize_prompt("foo embedding:", encode_word=BPE.encode, resolve=resolve_fixture)
    assert tokenized.missing_embeddings == ("",)
    assert chunks_to_json(pack_spans(tokenized.spans, CLIP_L_PROFILE)) == (
        chunks_to_json(
            pack_spans(
                tokenize_prompt("foo", encode_word=BPE.encode).spans,
                CLIP_L_PROFILE,
            )
        )
    )


def test_directives_without_resolver_are_plain_text() -> None:
    with_resolver = tokenize_prompt(
        "a embedding:emb2 b", encode_word=BPE.encode, resolve=resolve_fixture
    )
    without = tokenize_prompt("a embedding:emb2 b", encode_word=BPE.encode)
    assert any(isinstance(u, EmbeddingRef) for s in with_resolver.spans for u in s.tokens)
    assert not any(isinstance(u, EmbeddingRef) for s in without.spans for u in s.tokens)


# -------------------------------------------------------- unit edges


def test_pack_requires_resolvable_embedding_refs() -> None:
    spans = (WeightedSpan((EmbeddingRef("ghost"),), 1.0),)
    with pytest.raises(ValueError, match="ghost"):
        pack_spans(spans, CLIP_L_PROFILE, resolve=resolve_fixture)
    with pytest.raises(ValueError, match="resolver"):
        pack_spans(spans, CLIP_L_PROFILE)


def test_profile_rejects_unpackable_geometry() -> None:
    with pytest.raises(ValueError, match="max_length"):
        TokenizerProfile(max_length=6, max_word_length=8)
    with pytest.raises(ValueError, match="max_word_length"):
        TokenizerProfile(max_word_length=0)


def test_embedding_slot_validation() -> None:
    with pytest.raises(ValueError):
        EmbeddingSlot("", 0)
    with pytest.raises(ValueError):
        EmbeddingSlot("x", -1)


def test_packed_specials_carry_weight_one_and_word_zero() -> None:
    chunks = pack_spans((WeightedSpan((320,), 1.5),), CLIP_L_PROFILE)
    (chunk,) = chunks
    assert chunk[0] == PackedToken(CLIP_BOS, 1.0, 0)
    assert chunk[1] == PackedToken(320, 1.5, 1)
    assert chunk[2] == PackedToken(CLIP_EOS, 1.0, 0)
    assert all(item == PackedToken(CLIP_EOS, 1.0, 0) for item in chunk[3:])
    assert len(chunk) == 77


def test_clip_g_profile_pads_with_zero() -> None:
    (chunk,) = pack_spans((), CLIP_G_PROFILE)
    assert chunk[0].unit == CLIP_BOS
    assert chunk[1].unit == CLIP_EOS
    assert all(item.unit == 0 for item in chunk[2:])


def test_prompt_tokenizer_satisfies_the_stage1_contract() -> None:
    tokenizer: Tokenizer = PromptTokenizer(encode_word=BPE.encode)
    spans = tokenizer.tokenize("a (cat:1.2)")
    assert all(isinstance(span, WeightedSpan) for span in spans)
    assert spans[-1].weight == 1.2
