"""Exact Krea 2 Qwen3-VL-4B header and prompt-policy closure.

The golden is generated by executing ComfyUI at b78cec87 through
tools/gen_krea2_text_goldens.py. It pins the full checkpoint layout,
the fixed template, the twelve-tap policy, and the tokenizer behavior,
including disabled prompt weights, first-pad attention masking, and
the post-template strip boundary.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import FrozenInstanceError, replace
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    BFLOAT16,
    KREA2_TAP_LAYERS,
    KREA2_TEXT_CONFIG,
    Krea2OutputSelection,
    Krea2Prompt,
    Krea2TextConfig,
    Krea2TextDetectError,
    TensorGeometry,
    detect_krea2_text_config,
    format_krea2_prompt,
    krea2_language_layout,
    krea2_text_layout,
    select_krea2_output,
    tokenize_krea2_prompt,
)
from dinkster_inference.qwen_bpe import Krea2PromptTokens

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "krea2_text_goldens.json").read_text())


def exact_geometries() -> dict[str, TensorGeometry]:
    return {key: TensorGeometry(shape, BFLOAT16) for key, shape in krea2_text_layout().items()}


def test_krea2_text_config_is_exact_pinned_and_immutable() -> None:
    config = KREA2_TEXT_CONFIG
    assert config == Krea2TextConfig()
    assert (
        config.architecture,
        config.vocab_size,
        config.hidden_size,
        config.intermediate_size,
        config.num_hidden_layers,
        config.num_attention_heads,
        config.num_key_value_heads,
        config.head_dim,
        config.max_position_embeddings,
    ) == ("krea2_qwen3vl_4b", 151936, 2560, 9728, 36, 32, 8, 128, 262144)
    assert (config.rms_norm_eps, config.rope_theta) == (1e-6, 5_000_000.0)
    assert config.rope_dims == (24, 20, 20)
    assert config.interleaved_mrope is True
    assert config.qkv_bias is False
    assert (config.qk_norm, config.final_norm) == (True, True)
    assert config.tap_layers == KREA2_TAP_LAYERS
    assert config.stack_width == 12 * 2560 == 30720
    assert (
        config.pad_token_id,
        config.im_start_token_id,
        config.user_token_id,
        config.newline_token_id,
    ) == (151643, 151644, 872, 198)
    with pytest.raises(FrozenInstanceError):
        config.hidden_size = 1  # type: ignore[misc]
    with pytest.raises(ValueError, match="exact Krea 2 profile"):
        replace(config, hidden_size=1)
    with pytest.raises(ValueError, match="exact Krea 2 profile"):
        replace(config, qkv_bias=0)  # type: ignore[arg-type]


def test_tap_layers_and_template_match_executed_reference() -> None:
    assert list(KREA2_TAP_LAYERS) == GOLDENS["tap_layers"]
    assert KREA2_TEXT_CONFIG.prompt_template == GOLDENS["template"]


def test_full_layout_matches_executed_reference() -> None:
    layout = krea2_text_layout()
    assert len(layout) == 713
    assert sorted(layout.items()) == [(key, tuple(shape)) for key, shape in GOLDENS["layout"]]
    assert layout["model.language_model.embed_tokens.weight"] == (151936, 2560)
    assert layout["model.language_model.layers.35.self_attn.q_norm.weight"] == (128,)
    assert layout["model.visual.deepstack_merger_list.2.linear_fc2.weight"] == (2560, 4096)
    with pytest.raises(TypeError):
        layout["model.language_model.norm.weight"] = (1,)  # type: ignore[index]
    assert detect_krea2_text_config(exact_geometries()) is KREA2_TEXT_CONFIG


def test_language_layout_is_the_prefix_stripped_text_tower() -> None:
    language = krea2_language_layout()
    full = krea2_text_layout()
    assert len(language) == 398
    assert all(not key.startswith("model.") for key in language)
    assert all(full[f"model.language_model.{key}"] == shape for key, shape in language.items())
    assert language["embed_tokens.weight"] == (151936, 2560)
    assert language["layers.0.self_attn.k_norm.weight"] == (128,)
    assert language["norm.weight"] == (2560,)


@pytest.mark.parametrize(
    ("key", "shape"),
    (
        ("model.language_model.embed_tokens.weight", (151936, 2559)),
        ("model.language_model.layers.0.self_attn.q_norm.weight", (127,)),
        ("model.visual.patch_embed.proj.weight", (1024, 3, 2, 14, 14)),
        ("model.visual.deepstack_merger_list.2.linear_fc2.weight", (2559, 4096)),
    ),
)
def test_wrong_geometry_refuses(key: str, shape: tuple[int, ...]) -> None:
    geometries = exact_geometries()
    geometries[key] = TensorGeometry(shape, BFLOAT16)
    with pytest.raises(Krea2TextDetectError, match="expected shape"):
        detect_krea2_text_config(geometries)


def test_missing_extra_and_wrong_role_refuse_strictly() -> None:
    missing = exact_geometries()
    del missing["model.language_model.layers.35.mlp.down_proj.weight"]
    with pytest.raises(Krea2TextDetectError, match="missing model.language_model.layers.35"):
        detect_krea2_text_config(missing)

    extra = exact_geometries()
    extra["lm_head.weight"] = TensorGeometry((151936, 2560), BFLOAT16)
    with pytest.raises(Krea2TextDetectError, match="unexpected key lm_head.weight"):
        detect_krea2_text_config(extra)

    with pytest.raises(Krea2TextDetectError, match="not a Krea 2"):
        detect_krea2_text_config(
            {"model.language_model.embed_tokens.weight": TensorGeometry((151936, 2560), BFLOAT16)}
        )


def test_prompt_template_and_preformatted_bypass_are_exact() -> None:
    formatted = format_krea2_prompt("paint a red fox")
    assert formatted.preformatted is False
    assert formatted.text == (
        "<|im_start|>system\nDescribe the image by detailing the color, shape, size, "
        "texture, quantity, text, spatial relationships of the objects and background:"
        "<|im_end|>\n<|im_start|>user\npaint a red fox<|im_end|>\n"
        "<|im_start|>assistant\n"
    )
    raw = "<|im_start|>raw prompt"
    passthrough = format_krea2_prompt(raw)
    assert passthrough.text == raw
    assert passthrough.preformatted is True
    with pytest.raises(TypeError, match="preformatted must be a bool"):
        Krea2Prompt("x", 1)  # type: ignore[arg-type]


@pytest.mark.parametrize("case", GOLDENS["tokenizer"], ids=lambda case: case["text"])
def test_tokenizer_matches_executed_reference(case: dict[str, Any]) -> None:
    got = tokenize_krea2_prompt(str(case["text"]))
    assert list(got.ids) == case["ids"]
    assert list(got.attention_mask) == case["attention_mask"]
    assert set(case["weights"]) == {1.0}


@pytest.mark.parametrize("case", GOLDENS["tokenizer"], ids=lambda case: case["text"])
def test_template_strip_matches_executed_reference(case: dict[str, Any]) -> None:
    ids = [int(token) for token in case["ids"]]
    mask = [int(value) for value in case["attention_mask"]]
    if ids.count(KREA2_TEXT_CONFIG.im_start_token_id) < 2:
        with pytest.raises(ValueError, match="two im-start"):
            select_krea2_output([ids], [mask])
        return
    selected = select_krea2_output([ids], [mask])
    assert selected.slice_start == case["template_end"]
    assert selected.token_rows == (tuple(ids[selected.slice_start :]),)
    tail = tuple(mask[selected.slice_start :])
    assert selected.attention_mask == (None if all(tail) else (tail,))


def test_literal_pad_token_starts_reference_attention_masking() -> None:
    tokens = tokenize_krea2_prompt("<|endoftext|> masked tail")
    first_pad = tokens.ids.index(KREA2_TEXT_CONFIG.pad_token_id)
    assert tokens.attention_mask[first_pad - 1 : first_pad + 2] == (1, 0, 0)
    assert set(tokens.attention_mask[first_pad:]) == {0}
    selected = select_krea2_output([list(tokens.ids)], [list(tokens.attention_mask)])
    assert selected.attention_mask is not None


def test_prompt_tokens_constructor_refuses_malformed_masks() -> None:
    with pytest.raises(ValueError, match="non-empty and equal"):
        Krea2PromptTokens((), ())
    with pytest.raises(ValueError, match="non-empty and equal"):
        Krea2PromptTokens((1, 2), (1,))
    with pytest.raises(ValueError, match="non-negative integers"):
        Krea2PromptTokens((1, -2), (1, 1))
    with pytest.raises(ValueError, match="non-negative integers"):
        Krea2PromptTokens((1, True), (1, 1))
    with pytest.raises(ValueError, match="binary"):
        Krea2PromptTokens((1, 2), (2, 2))
    with pytest.raises(ValueError, match="non-empty prefix"):
        Krea2PromptTokens((1, 2), (0, 0))
    with pytest.raises(ValueError, match="non-empty prefix"):
        Krea2PromptTokens((1, 2, 3), (1, 0, 1))
    snapshot = Krea2PromptTokens([5, 6], [1, 0])  # type: ignore[arg-type]
    assert snapshot.ids == (5, 6)
    assert snapshot.attention_mask == (1, 0)


def test_output_selection_retains_only_masking_masks() -> None:
    row = (151644, 20, 151644, 872, 198, 30, 31, 151644)
    selected = select_krea2_output((row,), ((1, 1, 1, 1, 1, 1, 0, 0),))
    assert selected.slice_start == 5
    assert selected.token_rows == ((30, 31, 151644),)
    assert selected.attention_mask == ((1, 0, 0),)

    dropped = select_krea2_output((row,), ((1,) * len(row),))
    assert dropped.attention_mask is None
    direct = Krea2OutputSelection(((30,),), ((1,),), 5)
    assert direct.attention_mask is None
    explicit = select_krea2_output((row,), None, template_end=2)
    assert explicit.slice_start == 2
    assert explicit.token_rows == ((151644, 872, 198, 30, 31, 151644),)


def test_output_selection_refuses_malformed_rows_masks_and_offsets() -> None:
    row = (151644, 1, 151644, 872, 198, 30)
    with pytest.raises(ValueError, match="exactly one non-empty token row"):
        select_krea2_output((row, row), None)
    with pytest.raises(ValueError, match="ambiguous user boundary"):
        select_krea2_output(((151644, 1, 151644, 872),), None)
    with pytest.raises(ValueError, match="ambiguous user boundary"):
        select_krea2_output(((151644, 1, 151644, 198),), None)
    with pytest.raises(ValueError, match="attention mask shape"):
        select_krea2_output((row,), ((1, 1),))
    with pytest.raises(ValueError, match="binary"):
        select_krea2_output((row,), ((1, 1, 1, 1, 1, 2),))
    for template_end in (True, -2, len(row)):
        with pytest.raises(ValueError, match="template_end"):
            select_krea2_output((row,), None, template_end=template_end)  # type: ignore[arg-type]


def test_vendored_tokenizer_is_deterministic() -> None:
    first = tokenize_krea2_prompt("cafe\u0301 \u4e2d")
    second = tokenize_krea2_prompt("cafe\u0301 \u4e2d")
    assert first == second


def test_adversarial_tokenizer_corpus_matches_executed_reference() -> None:
    outputs = [
        [list(tokenize_krea2_prompt(str(text)).ids)]
        for text in GOLDENS["tokenizer_corpus"]["prompts"]
    ]
    canonical = json.dumps(outputs, separators=(",", ":")).encode("ascii")
    assert hashlib.sha256(canonical).hexdigest() == GOLDENS["tokenizer_corpus"]["token_ids_sha256"]
