"""Native inference stage 4a: LoRA dialect decoding vs the reference.

The torch-free decoder (dinkster_inference.lora) is pinned against
goldens generated by RUNNING comfy.lora_convert.convert_lora,
comfy.lora.load_lora, and comfy.lora.model_lora_keys_clip @ 947c2749
on synthetic key sets (tools/gen_lora_goldens.py). The goldens record
the reference's classification - which adapter class claimed each
target, which keys were consumed, which were left over - and the
weights-tuple slot shapes, so our spec fields are provably wired to
the same tensors the reference would read.

Documented deviations (loud diagnostics instead of upstream crashes
or silent corruption) are tested separately, not against goldens.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    FLOAT32,
    SDXL_UNET_CONFIG,
    BOFTSpec,
    DiffPatchRef,
    GLoRASpec,
    LoHaSpec,
    LoKrSpec,
    LoRASpec,
    OFTSpec,
    PatchOffset,
    PatchTarget,
    SetPatchRef,
    TensorGeometry,
    clip_lora_key_map,
    decode_lora,
    flux_linear1_qkv_key_map,
    load_safetensors_header,
    native_unet_key_map,
    normalize_lora_keys,
    qwen_image_dit_layout,
    qwen_image_lora_key_map,
    sd_unet_diffusers_key_map,
    unet_layout,
    z_image_diffusers_key_map,
    z_image_layout,
)

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "lora_goldens.json").read_text())

EXPECTED_DIALECTS = {
    "bfl_flux_control": "bfl_flux_control",
    "wan_fun": "wan_fun",
    "uso": "uso",
    "passthrough": "none",
}

KIND_TO_SPEC = {
    "LoRAAdapter": LoRASpec,
    "LoHaAdapter": LoHaSpec,
    "LoKrAdapter": LoKrSpec,
    "GLoRAAdapter": GLoRASpec,
    "OFTAdapter": OFTSpec,
    "BOFTAdapter": BOFTSpec,
    "diff": DiffPatchRef,
    "set": SetPatchRef,
}

# spec field name per reference weights-tuple slot, per adapter kind
# (the tuple layouts documented in the spec docstrings).
SLOT_FIELDS: dict[str, tuple[str, ...]] = {
    "LoRAAdapter": ("up", "down", "alpha", "mid", "dora_scale", "reshape"),
    "LoHaAdapter": (
        "w1_a",
        "w1_b",
        "alpha",
        "w2_a",
        "w2_b",
        "t1",
        "t2",
        "dora_scale",
    ),
    "LoKrAdapter": (
        "w1",
        "w2",
        "alpha",
        "w1_a",
        "w1_b",
        "w2_a",
        "w2_b",
        "t2",
        "dora_scale",
    ),
    "GLoRAAdapter": ("a1", "a2", "b1", "b2", "alpha", "dora_scale"),
    "OFTAdapter": ("blocks", "rescale", "alpha", "dora_scale"),
    "BOFTAdapter": ("blocks", "rescale", "alpha", "dora_scale"),
}


def geometries(shapes: dict[str, list[int]]) -> dict[str, TensorGeometry]:
    return {k: TensorGeometry(shape=tuple(v), dtype=FLOAT32) for k, v in shapes.items()}


class TestConvertGoldens:
    @pytest.mark.parametrize("case", GOLDENS["convert"], ids=lambda c: c["name"])
    def test_normalized_keys_match_reference(self, case: dict[str, Any]) -> None:
        normalized = normalize_lora_keys(geometries(case["input_shapes"]))
        assert normalized.dialect == EXPECTED_DIALECTS[case["name"]]
        ours = set(normalized.keys) | set(normalized.synthesized_reshapes)
        assert sorted(ours) == case["output_keys"]
        for key, dims in case["reshape_values"].items():
            assert list(normalized.synthesized_reshapes[key]) == dims

    def test_sources_point_back_at_file_keys(self) -> None:
        case = next(c for c in GOLDENS["convert"] if c["name"] == "bfl_flux_control")
        normalized = normalize_lora_keys(geometries(case["input_shapes"]))
        for source in normalized.keys.values():
            assert source in case["input_shapes"]
        assert normalized.keys["diffusion_model.img_in.diff_b"] == "img_in.lora_B.bias"


class TestDecodeGoldens:
    @pytest.mark.parametrize("case", GOLDENS["decode"], ids=lambda c: c["name"])
    def test_classification_matches_reference(self, case: dict[str, Any]) -> None:
        result = decode_lora(geometries(case["lora_shapes"]), case["to_load"])

        golden = {json.loads(target): entry for target, entry in case["patches"].items()}
        ours = {t.key: p for t, p in result.patches.items()}
        assert sorted(ours) == sorted(golden)
        assert sorted(result.unmatched) == case["leftovers"]
        assert result.diagnostics == ()

        for target, entry in golden.items():
            spec = ours[target]
            assert isinstance(spec, KIND_TO_SPEC[entry["kind"]])
            if entry["kind"] in ("diff", "set"):
                # slot 0 is the tensor; our ref key must have its shape
                assert isinstance(spec, (DiffPatchRef, SetPatchRef))
                shape = entry["slots"][0]
                assert f"tensor:{case['lora_shapes'][spec.key]}" == shape
                continue
            fields = SLOT_FIELDS[entry["kind"]]
            for slot, field_name in zip(entry["slots"], fields, strict=True):
                got = getattr(spec, field_name)
                if slot is None:
                    assert got is None
                elif isinstance(slot, str) and slot.startswith("tensor:"):
                    assert got is not None, field_name
                    assert f"tensor:{case['lora_shapes'][got]}" == slot
                elif field_name == "alpha":
                    # reference stores the .item() value; we defer the
                    # read and keep the key reference
                    assert isinstance(slot, (int, float))
                    assert got is not None and got.endswith(".alpha")
                elif field_name == "reshape":
                    # reference stores the tolist() value; we keep the
                    # key reference (value read deferred)
                    assert isinstance(slot, list)
                    assert got is not None
                    assert got.endswith(".reshape_weight")
                else:  # pragma: no cover - unexpected slot payload
                    raise AssertionError((field_name, slot))


class TestClipKeyMapGoldens:
    @pytest.mark.parametrize("case", GOLDENS["clip_key_maps"], ids=lambda c: c["name"])
    def test_key_map_matches_reference(self, case: dict[str, Any]) -> None:
        assert clip_lora_key_map(case["model_keys"]) == case["key_map"]


class TestNativeUnetKeyMap:
    """Transcription tests for the universal diffusion_model.* aliases
    (comfy/lora.py:188-198)."""

    def test_weight_keys_get_kohya_and_generic_stems(self) -> None:
        key_map = native_unet_key_map(
            [
                "diffusion_model.input_blocks.1.0.emb_layers.1.weight",
                "diffusion_model.out.norm.scale",
                "first_stage_model.decoder.weight",
            ]
        )
        assert key_map == {
            "lora_unet_input_blocks_1_0_emb_layers_1": (
                "diffusion_model.input_blocks.1.0.emb_layers.1.weight"
            ),
            "diffusion_model.input_blocks.1.0.emb_layers.1": (
                "diffusion_model.input_blocks.1.0.emb_layers.1.weight"
            ),
            "diffusion_model.out.norm.scale": "diffusion_model.out.norm.scale",
        }

    def test_wan_scail_projection_keys_get_generic_aliases(self) -> None:
        key_map = native_unet_key_map(
            (
                "diffusion_model.patch_embedding_pose.weight",
                "diffusion_model.patch_embedding_mask.weight",
            )
        )

        assert key_map == {
            "lora_unet_patch_embedding_pose": ("diffusion_model.patch_embedding_pose.weight"),
            "diffusion_model.patch_embedding_pose": ("diffusion_model.patch_embedding_pose.weight"),
            "lora_unet_patch_embedding_mask": ("diffusion_model.patch_embedding_mask.weight"),
            "diffusion_model.patch_embedding_mask": ("diffusion_model.patch_embedding_mask.weight"),
        }


class TestSDUnetDiffusersKeyMap:
    def test_sdxl_maps_diffusers_kohya_and_processor_aliases(self) -> None:
        model_keys = {f"diffusion_model.{key}" for key in unet_layout(SDXL_UNET_CONFIG)}
        key_map = sd_unet_diffusers_key_map(model_keys, SDXL_UNET_CONFIG)

        target = "diffusion_model.input_blocks.1.0.in_layers.2.weight"
        assert key_map["lora_unet_down_blocks_0_resnets_0_conv1"] == target
        assert key_map["lycoris_down_blocks_0_resnets_0_conv1"] == target
        attention_target = "diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight"
        assert (
            key_map["down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_q"]
            == attention_target
        )
        assert (
            key_map["unet.down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_q"]
            == attention_target
        )
        assert set(key_map.values()) <= model_keys


class TestFluxQkvKeyMap:
    def test_slice_targets(self) -> None:
        key_map = flux_linear1_qkv_key_map(
            ["diffusion_model.single_blocks.0.linear1.weight", "other.weight"],
            hidden_size=3072,
        )
        assert key_map == {
            "diffusion_model.single_blocks.0.linear1_qkv": PatchTarget(
                key="diffusion_model.single_blocks.0.linear1.weight",
                offset=PatchOffset(dim=0, start=0, length=9216),
            )
        }

    def test_zero_hidden_size_is_an_error(self) -> None:
        # The reference emits a zero-length slice target when
        # hidden_size is absent from the config; that patch is
        # unusable, so here it is loud.
        with pytest.raises(ValueError, match="hidden_size"):
            flux_linear1_qkv_key_map([], hidden_size=0)


class TestZImageDiffusersKeyMap:
    def test_split_attention_targets_fused_qkv_slices(self) -> None:
        key_map = z_image_diffusers_key_map(
            [
                "diffusion_model.layers.0.attention.qkv.weight",
                "diffusion_model.layers.0.attention.out.weight",
                "diffusion_model.context_refiner.0.attention.q_norm.weight",
                "diffusion_model.noise_refiner.0.attention.k_norm.weight",
                "diffusion_model.final_layer.linear.weight",
                "diffusion_model.x_embedder.weight",
            ],
            hidden_size=3840,
        )

        for index, name in enumerate(("to_q", "to_k", "to_v")):
            target = PatchTarget(
                "diffusion_model.layers.0.attention.qkv.weight",
                PatchOffset(dim=0, start=index * 3840, length=3840),
            )
            stem = f"layers.0.attention.{name}"
            assert key_map[f"diffusion_model.{stem}"] == target
            assert key_map[f"transformer.{stem}"] == target
            assert key_map[f"lycoris_{stem.replace('.', '_')}"] == target
            assert key_map[stem] == target

        output = PatchTarget("diffusion_model.layers.0.attention.out.weight")
        assert key_map["diffusion_model.layers.0.attention.to_out.0"] == output
        assert key_map["context_refiner.0.attention.norm_q"] == PatchTarget(
            "diffusion_model.context_refiner.0.attention.q_norm.weight"
        )
        assert key_map["noise_refiner.0.attention.norm_k"] == PatchTarget(
            "diffusion_model.noise_refiner.0.attention.k_norm.weight"
        )
        assert key_map["all_final_layer.2-1.linear"] == PatchTarget(
            "diffusion_model.final_layer.linear.weight"
        )
        assert key_map["all_x_embedder.2-1"] == PatchTarget("diffusion_model.x_embedder.weight")

    def test_real_z_image_lora_layout_decodes_without_unmatched_keys(self) -> None:
        model_keys: list[str] = []
        lora_shapes: dict[str, TensorGeometry] = {}
        for layer in range(30):
            model_keys.extend(
                (
                    f"diffusion_model.layers.{layer}.attention.qkv.weight",
                    f"diffusion_model.layers.{layer}.attention.out.weight",
                    f"diffusion_model.layers.{layer}.adaLN_modulation.0.weight",
                    f"diffusion_model.layers.{layer}.feed_forward.w1.weight",
                    f"diffusion_model.layers.{layer}.feed_forward.w2.weight",
                    f"diffusion_model.layers.{layer}.feed_forward.w3.weight",
                )
            )
            for stem, inputs, outputs in (
                ("adaLN_modulation.0", 256, 15360),
                ("attention.to_q", 3840, 3840),
                ("attention.to_k", 3840, 3840),
                ("attention.to_v", 3840, 3840),
                ("attention.to_out.0", 3840, 3840),
                ("feed_forward.w1", 3840, 10240),
                ("feed_forward.w2", 10240, 3840),
                ("feed_forward.w3", 3840, 10240),
            ):
                prefix = f"diffusion_model.layers.{layer}.{stem}"
                lora_shapes[f"{prefix}.lora_A.weight"] = geom(32, inputs)
                lora_shapes[f"{prefix}.lora_B.weight"] = geom(outputs, 32)

        key_map: dict[str, str | PatchTarget] = {}
        key_map.update(native_unet_key_map(model_keys))
        key_map.update(z_image_diffusers_key_map(model_keys, hidden_size=3840))
        decoded = decode_lora(lora_shapes, key_map)

        assert len(lora_shapes) == 480
        assert len(decoded.patches) == 240
        assert decoded.unmatched == ()
        q_target = PatchTarget(
            "diffusion_model.layers.0.attention.qkv.weight",
            PatchOffset(dim=0, start=0, length=3840),
        )
        assert isinstance(decoded.patches[q_target], LoRASpec)

    @pytest.fixture
    def real_z_image_lora(self, model_root: Path) -> Path:
        path = model_root / "loras/pixel_art_style_z_image_turbo.safetensors"
        if not path.exists():
            pytest.skip("Z-Image LoRA absent")
        return path

    def test_public_z_image_lora_header_decodes_without_unmatched_keys(
        self, real_z_image_lora: Path
    ) -> None:
        source = load_safetensors_header(real_z_image_lora)
        geometries = {key: source.entry(key).geometry for key in source.keys()}
        model_keys = tuple(f"diffusion_model.{key}" for key in z_image_layout())
        key_map: dict[str, str | PatchTarget] = {}
        key_map.update(native_unet_key_map(model_keys))
        key_map.update(z_image_diffusers_key_map(model_keys, hidden_size=3840))

        decoded = decode_lora(geometries, key_map)

        assert len(geometries) == 480
        assert len(decoded.patches) == 240
        assert len([target for target in decoded.patches if target.offset is not None]) == 90
        assert decoded.unmatched == ()
        assert decoded.diagnostics == ()
        assert decoded.loaded_keys == frozenset(geometries)

    def test_invalid_hidden_size_is_an_error(self) -> None:
        with pytest.raises(ValueError, match="hidden_size"):
            z_image_diffusers_key_map([], hidden_size=0)


class TestQwenImageLoraKeyMap:
    @pytest.mark.parametrize(
        ("stem", "down_suffix", "up_suffix"),
        (
            ("transformer_blocks.0.attn.to_q", ".lora_A.weight", ".lora_B.weight"),
            (
                "transformer.transformer_blocks.0.attn.to_q",
                ".lora_A.default.weight",
                ".lora_B.default.weight",
            ),
            (
                "lycoris_transformer_blocks_0_attn_to_q",
                ".lora_down.weight",
                ".lora_up.weight",
            ),
        ),
    )
    def test_supported_qwen_dialects_decode_to_native_weight(
        self, stem: str, down_suffix: str, up_suffix: str
    ) -> None:
        target = "diffusion_model.transformer_blocks.0.attn.to_q.weight"
        key_map = qwen_image_lora_key_map((target,))
        decoded = decode_lora(
            {
                stem + down_suffix: geom(8, 3072),
                stem + up_suffix: geom(3072, 8),
            },
            key_map,
        )
        assert decoded.unmatched == ()
        assert set(decoded.patches) == {PatchTarget(target)}
        assert isinstance(decoded.patches[PatchTarget(target)], LoRASpec)

    def test_official_diffsynth_union_lora_maps_all_60_blocks(self) -> None:
        modules = (
            "attn.add_k_proj",
            "attn.add_q_proj",
            "attn.add_v_proj",
            "attn.to_add_out",
            "attn.to_k",
            "attn.to_out.0",
            "attn.to_q",
            "attn.to_v",
            "img_mlp.net.2",
            "img_mod.1",
            "txt_mlp.net.2",
            "txt_mod.1",
        )
        model_keys = tuple(f"diffusion_model.{key}" for key in qwen_image_dit_layout().keys)
        key_map = qwen_image_lora_key_map(model_keys)
        geometries: dict[str, TensorGeometry] = {}
        for block in range(60):
            for module in modules:
                stem = f"transformer_blocks.{block}.{module}"
                target = f"diffusion_model.{stem}.weight"
                output, input_ = qwen_image_dit_layout().keys[
                    target.removeprefix("diffusion_model.")
                ]
                geometries[f"{stem}.lora_A.default.weight"] = geom(32, input_)
                geometries[f"{stem}.lora_B.default.weight"] = geom(output, 32)
        decoded = decode_lora(geometries, key_map)
        assert len(geometries) == 1440
        assert len(decoded.patches) == 720
        assert decoded.unmatched == ()
        assert decoded.loaded_keys == frozenset(geometries)


def geom(*shape: int) -> TensorGeometry:
    return TensorGeometry(shape=shape, dtype=FLOAT32)


class TestSourceKeyReferences:
    def test_specs_reference_pre_conversion_names(self) -> None:
        """After a dialect rename, spec fields must name the keys as
        they exist IN THE FILE, so the torch layer reads the right
        tensors."""
        result = decode_lora(
            {
                "lora_unet__blocks_0_cross_attn_k.lora_down.weight": geom(4, 5120),
                "lora_unet__blocks_0_cross_attn_k.lora_up.weight": geom(5120, 4),
                "lora_unet__blocks_0_cross_attn_k.alpha": geom(),
            },
            {"lora_unet_blocks_0_cross_attn_k": ("diffusion_model.blocks.0.cross_attn.k.weight")},
        )
        assert result.dialect == "wan_fun"
        (spec,) = result.patches.values()
        assert isinstance(spec, LoRASpec)
        assert spec.up == "lora_unet__blocks_0_cross_attn_k.lora_up.weight"
        assert spec.down == "lora_unet__blocks_0_cross_attn_k.lora_down.weight"
        assert spec.alpha == "lora_unet__blocks_0_cross_attn_k.alpha"
        assert result.loaded_keys == {
            "lora_unet__blocks_0_cross_attn_k.lora_up.weight",
            "lora_unet__blocks_0_cross_attn_k.lora_down.weight",
            "lora_unet__blocks_0_cross_attn_k.alpha",
        }

    def test_bfl_synthesized_reshape_travels_as_dims(self) -> None:
        result = decode_lora(
            {
                "img_in.lora_A.weight": geom(4, 64),
                "img_in.lora_B.weight": geom(3072, 4),
                "single_blocks.0.norm.key_norm.scale": geom(128),
            },
            {
                "diffusion_model.img_in": "diffusion_model.img_in.weight",
                "diffusion_model.single_blocks.0.norm.key_norm": (
                    "diffusion_model.single_blocks.0.norm.key_norm.scale"
                ),
            },
        )
        assert result.dialect == "bfl_flux_control"
        img_in = result.patches[PatchTarget("diffusion_model.img_in.weight")]
        assert isinstance(img_in, LoRASpec)
        assert img_in.variant == "peft"
        assert img_in.reshape is None
        assert img_in.reshape_dims == (3072, 64)
        norm = result.patches[PatchTarget("diffusion_model.single_blocks.0.norm.key_norm.scale")]
        assert isinstance(norm, SetPatchRef)
        assert norm.key == "single_blocks.0.norm.key_norm.scale"


class TestDeviations:
    """Where the reference crashes (KeyError) or silently corrupts,
    the decoder records a diagnostic and drops only the affected
    patch."""

    def test_loha_missing_companion(self) -> None:
        result = decode_lora({"stem.hada_w1_a": geom(320, 4)}, {"stem": "model.weight"})
        assert result.patches == {}
        assert result.unmatched == ("stem.hada_w1_a",)
        assert any("hada_w1_b" in d for d in result.diagnostics)

    def test_glora_missing_companion(self) -> None:
        result = decode_lora({"stem.a1.weight": geom(320, 4)}, {"stem": "model.weight"})
        assert result.patches == {}
        assert any("glora" in d for d in result.diagnostics)

    def test_lora_up_without_down(self) -> None:
        result = decode_lora({"stem.lora_up.weight": geom(320, 4)}, {"stem": "model.weight"})
        assert result.patches == {}
        assert any("lora_down" in d for d in result.diagnostics)

    def test_lone_lokr_partner_surfaces_as_unmatched(self) -> None:
        # The reference consumes a lone lokr_w1_b silently without
        # producing an adapter (lokr.py marks keys loaded before its
        # qualification check); here it stays unmatched.
        result = decode_lora({"stem.lokr_w1_b": geom(2, 10)}, {"stem": "model.weight"})
        assert result.patches == {}
        assert result.unmatched == ("stem.lokr_w1_b",)

    def test_diff_b_on_non_weight_target(self) -> None:
        result = decode_lora({"stem.diff_b": geom(320)}, {"stem": "model.scale"})
        assert result.patches == {}
        assert any("bias target" in d for d in result.diagnostics)

    def test_diff_b_on_offset_target(self) -> None:
        result = decode_lora(
            {"stem.diff_b": geom(320)},
            {
                "stem": PatchTarget(
                    key="model.weight",
                    offset=PatchOffset(dim=0, start=0, length=320),
                )
            },
        )
        assert result.patches == {}
        assert any("bias target" in d for d in result.diagnostics)

    def test_diff_on_offset_target_is_fine(self) -> None:
        target = PatchTarget(key="model.weight", offset=PatchOffset(dim=0, start=0, length=320))
        result = decode_lora({"stem.diff": geom(320, 320)}, {"stem": target})
        assert result.patches == {target: DiffPatchRef(key="stem.diff")}
        assert result.diagnostics == ()
