"""Exact Gemma 3 12B header, LTX projection, and prompt-policy closure.

The golden is generated by executing ComfyUI at b78cec87 through
tools/gen_ltx_gemma_text_goldens.py. It pins the full model layout
(cross-checked against the packaged Comfy-Org checkpoint header at
generation time), the single/dual text-projection listings, the
embeddings-connector facts of the real ltx-2-19b-dev checkpoint, and
the tokenizer policy. Executed tokenizer replays need the official
SentencePiece model and live in the torch suite; the policy tests here
use a fake encode.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path

import pytest
from dinkster_inference import (
    BFLOAT16,
    GEMMA3_LTX_12B_CONFIG,
    LTX_GEMMA_PROMPT_TEMPLATE,
    GemmaTextDetectError,
    LtxGemmaPromptTokens,
    TensorGeometry,
    detect_gemma_text_config,
    detect_ltx_text_connectors,
    detect_ltx_text_projection,
    gemma_text_layout,
    ltx_text_projection_layout,
    tokenize_ltx_gemma_prompt,
)

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "ltx_gemma_text_goldens.json").read_text()
)


def exact_geometries() -> dict[str, TensorGeometry]:
    return {
        key: TensorGeometry(tuple(shape), BFLOAT16) for key, shape in GOLDENS["layout"]["model"]
    }


def test_full_layout_matches_executed_reference_and_real_checkpoint() -> None:
    expected = [(key, tuple(shape)) for key, shape in GOLDENS["layout"]["model"]]
    assert sorted(gemma_text_layout(GEMMA3_LTX_12B_CONFIG).items()) == expected
    assert detect_gemma_text_config(exact_geometries()) is GEMMA3_LTX_12B_CONFIG
    assert GOLDENS["real_checkpoint"]["model_subtree_matches_meta_layout"] is True


def test_wrong_width_refuses() -> None:
    geometries = exact_geometries()
    geometries["embed_tokens.weight"] = TensorGeometry((262208, 2559), BFLOAT16)
    with pytest.raises(GemmaTextDetectError, match="unknown Gemma text width"):
        detect_gemma_text_config(geometries)


def test_wrong_role_refuses() -> None:
    with pytest.raises(GemmaTextDetectError, match="not a Gemma text-model role"):
        detect_gemma_text_config(
            {"vision_model.patch_embed.weight": TensorGeometry((8, 8), BFLOAT16)}
        )


def test_missing_or_extra_model_key_refuses_strictly() -> None:
    missing = exact_geometries()
    del missing["layers.47.self_attn.q_norm.weight"]
    with pytest.raises(GemmaTextDetectError, match="missing layers.47"):
        detect_gemma_text_config(missing)

    extra = exact_geometries()
    extra["lm_head.weight"] = TensorGeometry((262208, 3840), BFLOAT16)
    with pytest.raises(GemmaTextDetectError, match="unexpected key lm_head.weight"):
        detect_gemma_text_config(extra)


def _projection_geometries(entries: Sequence[Sequence[object]]) -> dict[str, TensorGeometry]:
    return {str(key): TensorGeometry(tuple(shape), BFLOAT16) for key, shape in entries}  # type: ignore[arg-type]


def test_single_projection_detects_from_real_checkpoint_listing() -> None:
    listing = [
        (key.removeprefix("text_embedding_projection."), shape)
        for key, shape in GOLDENS["ltx2_19b_dev"]["text_embedding_projection"]
    ]
    assert listing == [("aggregate_embed.weight", [3840, 188160])]
    assert detect_ltx_text_projection(_projection_geometries(listing)) == "single_linear"
    assert (
        detect_ltx_text_projection(_projection_geometries([["weight", [3840, 188160]]]))
        == "single_linear"
    )


def test_dual_projection_detects_from_reference_module_layout() -> None:
    listing = GOLDENS["dual_projection"]["layout"]
    assert GOLDENS["dual_projection"]["structure_derived"] is True
    assert sorted(ltx_text_projection_layout("dual_linear").items()) == [
        (key, tuple(shape)) for key, shape in listing
    ]
    assert detect_ltx_text_projection(_projection_geometries(listing)) == "dual_linear"


def test_projection_refuses_both_spellings_wrong_shapes_and_extras() -> None:
    with pytest.raises(GemmaTextDetectError, match="both aggregate_embed.weight and weight"):
        detect_ltx_text_projection(
            _projection_geometries(
                [["weight", [3840, 188160]], ["aggregate_embed.weight", [3840, 188160]]]
            )
        )
    with pytest.raises(GemmaTextDetectError, match="expected shape"):
        detect_ltx_text_projection(_projection_geometries([["weight", [3840, 3840]]]))
    with pytest.raises(GemmaTextDetectError, match="unexpected key extra"):
        detect_ltx_text_projection(
            _projection_geometries([["weight", [3840, 188160]], ["extra", [1]]])
        )
    incomplete = _projection_geometries(GOLDENS["dual_projection"]["layout"])
    del incomplete["video_aggregate_embed.weight"]
    with pytest.raises(GemmaTextDetectError, match="missing video_aggregate_embed.weight"):
        detect_ltx_text_projection(incomplete)
    with pytest.raises(GemmaTextDetectError, match="empty text-projection header"):
        detect_ltx_text_projection({})


def test_connector_carrying_checkpoints_are_detected_not_rejected() -> None:
    facts = GOLDENS["ltx2_19b_dev"]["legacy_connector"]
    assert facts["fires_reference_compat_mode"] is True
    assert facts["absent_probe_present"] is False
    header = {str(facts["trigger_key"]): TensorGeometry(tuple(facts["trigger_shape"]), BFLOAT16)}
    with pytest.raises(GemmaTextDetectError, match="missing"):
        detect_ltx_text_connectors(header)
    assert detect_ltx_text_connectors({}) is None


def _fake_encode(text: str) -> list[int]:
    return [ord(char) % 200 + 10 for char in text]


def test_template_application_equals_pretemplated_text() -> None:
    templated = tokenize_ltx_gemma_prompt("cat", encode=_fake_encode, apply_template=True)
    manual = tokenize_ltx_gemma_prompt(LTX_GEMMA_PROMPT_TEMPLATE.format("cat"), encode=_fake_encode)
    assert templated == manual
    raw = tokenize_ltx_gemma_prompt("cat", encode=_fake_encode)
    assert raw.ids != templated.ids


def test_text_already_starting_a_turn_forces_the_raw_path() -> None:
    text = "<start_of_turn>user\nalready templated<end_of_turn>\n"
    assert tokenize_ltx_gemma_prompt(
        text, encode=_fake_encode, apply_template=True
    ) == tokenize_ltx_gemma_prompt(text, encode=_fake_encode)


def test_escaped_parentheses_unescape_and_weights_stay_literal() -> None:
    assert tokenize_ltx_gemma_prompt(r"\(cat\)", encode=_fake_encode) == tokenize_ltx_gemma_prompt(
        "(cat)", encode=_fake_encode
    )


def test_plain_prompt_keeps_bos_and_left_pads_to_minimum() -> None:
    tokens = tokenize_ltx_gemma_prompt("cat", encode=_fake_encode)
    encoded = _fake_encode("cat")
    width = GEMMA3_LTX_12B_CONFIG.min_tokens
    assert len(tokens.ids) == width
    padding = width - 1 - len(encoded)
    assert tokens.ids[:padding] == (GEMMA3_LTX_12B_CONFIG.pad_token_id,) * padding
    assert tokens.ids[padding] == GEMMA3_LTX_12B_CONFIG.bos_token_id
    assert tokens.ids[padding + 1 :] == tuple(encoded)
    assert tokens.attention_mask == (0,) * padding + (1,) * (1 + len(encoded))
    assert tokens.word_ids == (0,) * (padding + 1) + (1,) * len(encoded)


def test_special_token_segment_drops_its_first_content_token() -> None:
    tokens = tokenize_ltx_gemma_prompt("<end_of_turn>x", encode=_fake_encode)
    content = [token for token, keep in zip(tokens.ids, tokens.attention_mask, strict=True) if keep]
    assert content == [GEMMA3_LTX_12B_CONFIG.bos_token_id, *_fake_encode("x")]


def test_embedding_marker_splits_word_ids_only_after_whitespace() -> None:
    split = tokenize_ltx_gemma_prompt("a embedding:b", encode=_fake_encode)
    assert set(split.word_ids) == {0, 1, 2}
    fused = tokenize_ltx_gemma_prompt("aembedding:b", encode=_fake_encode)
    assert set(fused.word_ids) == {0, 1}


def test_empty_prompt_is_a_lone_attended_bos() -> None:
    tokens = tokenize_ltx_gemma_prompt("", encode=_fake_encode)
    assert tokens.ids[-1] == GEMMA3_LTX_12B_CONFIG.bos_token_id
    assert sum(tokens.attention_mask) == 1
    assert tokens.attention_mask[-1] == 1


def test_pad_token_after_content_masks_the_rest() -> None:
    tokens = tokenize_ltx_gemma_prompt("z", encode=lambda _text: [5, 0, 7])
    attended = tokens.attention_mask[-4:]
    assert tokens.ids[-4:] == (2, 5, 0, 7)
    assert attended == (1, 1, 0, 0)


def test_prompt_tokens_validate_shape_and_mask_values() -> None:
    with pytest.raises(ValueError, match="non-empty and equal"):
        LtxGemmaPromptTokens((), (), ())
    with pytest.raises(ValueError, match="non-empty and equal"):
        LtxGemmaPromptTokens((1, 2), (1,), (0, 0))
    with pytest.raises(ValueError, match="equal length"):
        LtxGemmaPromptTokens((1, 2), (1, 1), (0,))
    with pytest.raises(ValueError, match="binary"):
        LtxGemmaPromptTokens((1,), (2,), (0,))


def test_tokenizer_cases_and_corpus_are_recorded_for_torch_replay() -> None:
    assert len(GOLDENS["tokenizer"]) == 24
    assert len(GOLDENS["tokenizer_corpus"]["prompts"]) == 128
    for case in GOLDENS["tokenizer"]:
        assert len(case["ids"]) == len(case["attention_mask"]) == len(case["word_ids"])
        assert len(case["ids"]) >= GEMMA3_LTX_12B_CONFIG.min_tokens
