"""Exact Anima Qwen3-0.6B header and dual-tokenizer policy closure.

The golden is generated by executing ComfyUI at 82f839f5 through
tools/gen_anima_text_goldens.py. It pins the full model layout and the
template-free dual tokenizer: the Qwen row whose attention masks come
from the executed reference masking code and whose weights are forced
to 1.0, and the T5 row whose ids and emphasis weights ride to the
diffusion model's LLM adapter.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    ANIMA_QWEN3_06B_CONFIG,
    BFLOAT16,
    AnimaPromptTokens,
    TensorGeometry,
    detect_qwen_text_config,
    load_qwen_bpe,
    qwen_text_layout,
    tokenize_anima_prompt,
)

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "anima_text_goldens.json").read_text())


def exact_geometries() -> dict[str, TensorGeometry]:
    return {key: TensorGeometry(tuple(shape), BFLOAT16) for key, shape in GOLDENS["layout"]}


def test_full_layout_matches_executed_reference() -> None:
    expected = [(key, tuple(shape)) for key, shape in GOLDENS["layout"]]
    assert sorted(qwen_text_layout(ANIMA_QWEN3_06B_CONFIG).items()) == expected
    assert detect_qwen_text_config(exact_geometries()) is ANIMA_QWEN3_06B_CONFIG


def test_profile_identity_is_exact() -> None:
    config = ANIMA_QWEN3_06B_CONFIG
    assert (
        config.vocab_size,
        config.hidden_size,
        config.intermediate_size,
        config.num_hidden_layers,
        config.num_attention_heads,
        config.num_key_value_heads,
        config.head_dim,
    ) == (151936, 1024, 3072, 28, 16, 8, 128)
    assert config.max_position_embeddings == 32768
    assert config.pad_token_id == 151643
    assert config.prompt_template == "{}"
    assert config.min_tokens == 1
    assert config.qk_norm and not config.qkv_bias
    assert not config.zero_masked
    assert not config.layer_norm_hidden_state
    assert config.final_norm
    layout = qwen_text_layout(config)
    assert len(layout) == 310
    assert layout["layers.0.self_attn.q_proj.weight"] == (2048, 1024)
    assert layout["layers.0.self_attn.k_proj.weight"] == (1024, 1024)
    assert layout["layers.0.self_attn.q_norm.weight"] == (128,)


@pytest.mark.parametrize("case", GOLDENS["tokenizer"], ids=lambda case: case["text"])
def test_dual_tokenizer_matches_executed_reference(case: dict[str, Any]) -> None:
    got = tokenize_anima_prompt(str(case["text"]))
    assert list(got.qwen_ids) == case["qwen_ids"]
    assert list(got.qwen_attention_mask) == case["qwen_attention_mask"]
    assert set(case["qwen_weights"]) == {1.0}
    assert list(got.t5xxl_ids) == case["t5xxl_ids"]
    assert list(got.t5xxl_weights) == case["t5xxl_weights"]


def test_emphasis_weights_ride_the_t5_stream_only() -> None:
    plain = tokenize_anima_prompt("cat")
    weighted = tokenize_anima_prompt("(cat:1.2)")
    assert weighted.qwen_ids == plain.qwen_ids
    assert weighted.t5xxl_ids == plain.t5xxl_ids
    assert plain.t5xxl_weights == (1.0,) * len(plain.t5xxl_ids)
    assert weighted.t5xxl_weights[:-1] == (1.2,) * (len(weighted.t5xxl_ids) - 1)
    assert weighted.t5xxl_weights[-1] == 1.0


def test_empty_prompt_is_one_masked_pad_and_bare_eos() -> None:
    tokens = tokenize_anima_prompt("")
    assert tokens.qwen_ids == (151643,)
    assert tokens.qwen_attention_mask == (0,)
    assert tokens.t5xxl_ids == (1,)
    assert tokens.t5xxl_weights == (1.0,)


def test_literal_pad_token_masking_follows_reference_left_pad_rule() -> None:
    leading = tokenize_anima_prompt("<|endoftext|> masked tail")
    assert leading.qwen_ids[0] == ANIMA_QWEN3_06B_CONFIG.pad_token_id
    assert leading.qwen_attention_mask[0] == 0
    assert set(leading.qwen_attention_mask[1:]) == {1}

    mid = tokenize_anima_prompt("tail then <|endoftext|> more text")
    first_pad = mid.qwen_ids.index(ANIMA_QWEN3_06B_CONFIG.pad_token_id)
    assert first_pad > 0
    assert set(mid.qwen_attention_mask[:first_pad]) == {1}
    assert set(mid.qwen_attention_mask[first_pad:]) == {0}


def test_vendored_tokenizers_are_deterministic() -> None:
    first = tokenize_anima_prompt("cafe\u0301 \u4e2d")
    second = tokenize_anima_prompt("cafe\u0301 \u4e2d")
    assert first == second


@pytest.mark.parametrize(
    "text",
    (
        "plain text",
        "cafe\u0301 \u4e2d",
        "emoji \U0001f600 and symbols +/-=",
        "don't stop...\nnext",
    ),
)
def test_qwen_decode_round_trips_normalized_text(text: str) -> None:
    import unicodedata

    tokenizer = load_qwen_bpe()
    assert tokenizer.decode(tokenizer.encode(text)) == unicodedata.normalize("NFC", text)


def test_qwen_decode_handles_specials_byte_fragments_and_invalid_ids() -> None:
    tokenizer = load_qwen_bpe()
    ids = tokenizer.encode("a<|im_start|>\U0001f600<|im_end|>b")
    assert tokenizer.decode(ids) == "a\U0001f600b"
    assert tokenizer.decode_bytes(ids) == "a\U0001f600b".encode()
    assert tokenizer.decode(ids, skip_special_tokens=False) == (
        "a<|im_start|>\U0001f600<|im_end|>b"
    )
    with pytest.raises(ValueError, match="non-negative exact integers"):
        tokenizer.decode([True])
    with pytest.raises(ValueError, match="no token ID"):
        tokenizer.decode([999_999])
    with pytest.raises(ValueError, match="decode errors"):
        tokenizer.decode(ids, errors="xmlcharrefreplace")


def test_adversarial_tokenizer_corpus_matches_executed_reference() -> None:
    outputs = []
    for text in GOLDENS["tokenizer_corpus"]["prompts"]:
        tokens = tokenize_anima_prompt(str(text))
        outputs.append(
            {
                "qwen_ids": [list(tokens.qwen_ids)],
                "t5xxl_ids": [list(tokens.t5xxl_ids)],
                "t5xxl_weights": [list(tokens.t5xxl_weights)],
            }
        )
    canonical = json.dumps(outputs, separators=(",", ":")).encode("ascii")
    assert hashlib.sha256(canonical).hexdigest() == GOLDENS["tokenizer_corpus"]["streams_sha256"]


def test_prompt_tokens_validators_fire() -> None:
    with pytest.raises(ValueError, match="non-empty and equal"):
        AnimaPromptTokens((1,), (1, 0), (5, 1), (1.0, 1.0))
    with pytest.raises(ValueError, match="binary"):
        AnimaPromptTokens((1,), (2,), (5, 1), (1.0, 1.0))
    with pytest.raises(ValueError, match="end with EOS"):
        AnimaPromptTokens((1,), (1,), (5, 3), (1.0, 1.0))
