"""Native inference stage 3b: solver ports vs the ComfyUI reference.

Every ported solver is pinned against goldens generated by RUNNING the
reference sample_* functions @ 947c2749 in float64 with a deterministic
mock denoiser and counter-based injected noise (tools/
gen_sampling_goldens.py, "solvers" section). This file replicates the
exact same denoiser/noise formulas over the plain-float Vec stub, so
the port and the reference consume identical inputs and any coefficient
error surfaces as a golden mismatch.

Draw-count expectations are port-side: the port deliberately skips
noise calls whose coefficient is exactly 0.0 (the reference draws and
discards, e.g. euler_ancestral at eta=0), so those counts differ from
the golden's reference counts while the finals still match - that
deviation being behavior-preserving is itself under test here.
"""

from __future__ import annotations

import json
import math
from collections.abc import Sequence
from dataclasses import FrozenInstanceError, dataclass, field, replace
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    BuiltinSamplerSelection,
    CancellationFlag,
    NoiseKind,
    OptionKind,
    OptionSpec,
    Parameterization,
    SamplerDescriptor,
    SamplerInfo,
    SamplingCancelled,
    SolverStateEvent,
    StepEvent,
    builtin_scheduler_registry,
    builtin_schedulers,
    resolve_options,
    use_sampling_environment,
)
from dinkster_inference.registry import RegistryError
from dinkster_inference.sampling import run_step_begin_solver
from dinkster_inference.schedules import offset_first_sigma_for_snr
from dinkster_inference.spaces import FlowSigmas
from dinkster_inference_torch._portable_solvers import (
    builtin_sampler_registry,
    builtin_samplers,
    ddim,
    deis,
    dpm_2_ancestral,
    dpm_adaptive,
    dpmpp_2m_cfg_pp,
    dpmpp_2m_sde,
    dpmpp_2s_ancestral,
    dpmpp_2s_ancestral_cfg_pp,
    dpmpp_sde,
    er_sde,
    euler,
    euler_ancestral,
    euler_ancestral_cfg_pp,
    euler_cfg_pp,
    res_multistep,
    res_multistep_ancestral,
    res_multistep_ancestral_cfg_pp,
    res_multistep_cfg_pp,
    select_builtin_sampler,
    uni_pc,
    uni_pc_bh2,
)
from dinkster_inference_torch.res4lyf_rk import prepare_rk_sigmas, res4lyf_rk
from test_inference_sampling_math import Vec

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "sampling_goldens.json").read_text())
SOLVERS: dict[str, Any] = GOLDENS["solvers"]
SOLVERS["cases"]["sa_solver_current_configured"] = json.loads(
    (Path(__file__).parent / "goldens" / "configured_sa_solver_1d48d9cf.json").read_text()
)
DIMS = len(SOLVERS["x0"])

# Both sides compute in float64; only op-ordering differences remain.
REL = 1e-9
ABS = 1e-10


def mock_denoised(x: Vec, sigma: float) -> Vec:
    """Twin of the generator's solver_mock_denoised: nonlinear in x so
    coefficient errors cannot cancel."""
    return x * (1.0 / (1.0 + sigma)) + (x * x) * (0.05 / (1.0 + sigma))


def mock_uncond(x: Vec, sigma: float) -> Vec:
    """Twin of the generator's solver_mock_uncond: a second, distinct
    nonlinear formula so the CFG++ solvers' combined/uncond channels
    cannot be confused."""
    return x * (0.8 / (1.2 + sigma)) - (x * x) * (0.03 / (1.0 + sigma))


class CfgMockDenoiser:
    """Twin of the generator's _MockCfgModel: a denoiser carrying the
    UncondDenoiser capability, returning the same combined/uncond pair
    the reference's post-CFG hook chain hands the cfg_pp solvers."""

    def __call__(self, x: Vec, sigma: float) -> Vec:
        return mock_denoised(x, sigma)

    def call_with_uncond(self, x: Vec, sigma: float) -> tuple[Vec, Vec]:
        return mock_denoised(x, sigma), mock_uncond(x, sigma)


@dataclass
class CountingNoise:
    """Twin of the generator's counter-based draw: deterministic values
    per draw index, recording call arguments."""

    calls: list[tuple[float, float]] = field(default_factory=list)

    def __call__(self, sigma_from: float, sigma_to: float) -> Vec:
        k = len(self.calls)
        self.calls.append((sigma_from, sigma_to))
        return Vec(tuple(math.sin(1.3 * k + 0.7 * j + 0.1) for j in range(DIMS)))


SPACE_INFO = {
    "eps": SamplerInfo(
        parameterization=Parameterization.EPS,
        percent_to_sigma=lambda p: 10 ** (1 - 3 * p),
    ),
    "flow": SamplerInfo(parameterization=Parameterization.FLOW, percent_to_sigma=lambda p: 1 - p),
    "flow_scaled": SamplerInfo(
        parameterization=Parameterization.FLOW,
        noise_scale=SOLVERS["noise_scale"]["flow_scaled"],
    ),
    "flow_snr": SamplerInfo(parameterization=Parameterization.FLOW),
}

# Cases whose flow schedule starts at exactly 1.0 and runs an SDE
# solver: the reference offsets the first sigma inside the solver via
# model probing; here schedule preparation owns it, so the test applies
# the ported helper before solving. FlowSigmas(shift=1.0) is the exact
# twin of the golden's ModelSamplingDiscreteFlow default (both compute
# time_snr_shift(1.0, 1 - 1e-4)).
OFFSET_CASES = {"dpmpp_sde_flow1", "dpmpp_2m_sde_flow1", "dpmpp_3m_sde_flow1"}

# golden case -> descriptor id (options and space come from the golden
# record itself). dpmpp_2m_sde_eps_heun additionally proves the fixed
# dinkster.dpmpp_2m_sde_heun descriptor below.
CASE_DESCRIPTOR = {
    "euler_eps": "dinkster.euler",
    "euler_churn_eps": "dinkster.euler",
    "heun_eps": "dinkster.heun",
    "heun_churn_eps": "dinkster.heun",
    "heunpp2_eps": "dinkster.heunpp2",
    "heunpp2_churn_eps": "dinkster.heunpp2",
    "lms_eps": "dinkster.lms",
    "lms_eps_order2": "dinkster.lms",
    "lms_eps_order6": "dinkster.lms",
    "dpm_fast_eps": "dinkster.dpm_fast",
    "dpm_fast_flow": "dinkster.dpm_fast",
    "dpm_adaptive_eps": "dinkster.dpm_adaptive",
    "dpm_adaptive_eps_eta2": "dinkster.dpm_adaptive",
    "dpm_adaptive_flow_order2_options": "dinkster.dpm_adaptive",
    "uni_pc_eps": "dinkster.uni_pc",
    "uni_pc_flow": "dinkster.uni_pc",
    "uni_pc_bh2_eps": "dinkster.uni_pc_bh2",
    "uni_pc_bh2_flow": "dinkster.uni_pc_bh2",
    "dpm_2_eps": "dinkster.dpm_2",
    "dpm_2_churn_eps": "dinkster.dpm_2",
    "euler_ancestral_eps": "dinkster.euler_ancestral",
    "euler_ancestral_eps_eta0.4": "dinkster.euler_ancestral",
    "euler_ancestral_eps_eta0": "dinkster.euler_ancestral",
    "euler_ancestral_flow": "dinkster.euler_ancestral",
    "euler_ancestral_flow_scaled": "dinkster.euler_ancestral",
    "dpm_2_ancestral_eps": "dinkster.dpm_2_ancestral",
    "dpm_2_ancestral_flow": "dinkster.dpm_2_ancestral",
    "dpmpp_2s_ancestral_eps": "dinkster.dpmpp_2s_ancestral",
    "dpmpp_2s_ancestral_flow": "dinkster.dpmpp_2s_ancestral",
    "dpmpp_sde_eps": "dinkster.dpmpp_sde",
    "dpmpp_sde_eps_r0.33": "dinkster.dpmpp_sde",
    "dpmpp_sde_eps_r2": "dinkster.dpmpp_sde",
    "dpmpp_sde_flow": "dinkster.dpmpp_sde",
    "dpmpp_2m_eps": "dinkster.dpmpp_2m",
    "dpmpp_2m_sde_eps": "dinkster.dpmpp_2m_sde",
    "dpmpp_2m_sde_eps_heun": "dinkster.dpmpp_2m_sde",
    "dpmpp_2m_sde_eps_eta0.5": "dinkster.dpmpp_2m_sde",
    "dpmpp_2m_sde_eps_eta0": "dinkster.dpmpp_2m_sde",
    "dpmpp_2m_sde_flow": "dinkster.dpmpp_2m_sde",
    "dpmpp_3m_sde_eps": "dinkster.dpmpp_3m_sde",
    "dpmpp_3m_sde_flow": "dinkster.dpmpp_3m_sde",
    "ddpm_eps": "dinkster.ddpm",
    "lcm_eps": "dinkster.lcm",
    "lcm_eps_snoise0.7": "dinkster.lcm",
    "lcm_flow_scaled": "dinkster.lcm",
    "lcm_eps_noise_range": "dinkster.lcm",
    "lcm_eps_noise_clip": "dinkster.lcm",
    "ipndm_eps": "dinkster.ipndm",
    "ipndm_eps_order2": "dinkster.ipndm",
    "ipndm_v_eps": "dinkster.ipndm_v",
    "ipndm_v_flow": "dinkster.ipndm_v",
    "deis_eps": "dinkster.deis",
    "deis_flow": "dinkster.deis",
    "deis_eps_order2": "dinkster.deis",
    "gradient_estimation_eps": "dinkster.gradient_estimation",
    "gradient_estimation_flow_gamma1.5": "dinkster.gradient_estimation",
    "gradient_estimation_cfg_pp_eps": "dinkster.gradient_estimation_cfg_pp",
    "er_sde_eps": "dinkster.er_sde",
    "er_sde_flow": "dinkster.er_sde",
    "er_sde_flow_scaled": "dinkster.er_sde",
    "er_sde_eps_stage2_snoise0.6": "dinkster.er_sde",
    "exp_heun_2_x0_eps_phi2": "dinkster.exp_heun_2_x0",
    "exp_heun_2_x0_flow_phi1": "dinkster.exp_heun_2_x0",
    "exp_heun_2_x0_sde_eps": "dinkster.exp_heun_2_x0_sde",
    "exp_heun_2_x0_sde_flow_eta0.4_phi1": "dinkster.exp_heun_2_x0_sde",
    "seeds_2_eps_phi1": "dinkster.seeds_2",
    "seeds_2_eps_phi2_eta0": "dinkster.seeds_2",
    "seeds_2_flow_phi2_eta0.4": "dinkster.seeds_2",
    "seeds_3_eps": "dinkster.seeds_3",
    "seeds_3_flow_eta0.4": "dinkster.seeds_3",
    "euler_churn_cap_eps": "dinkster.euler",
    "dpmpp_2s_ancestral_flow1": "dinkster.dpmpp_2s_ancestral",
    "dpmpp_sde_flow1": "dinkster.dpmpp_sde",
    "dpmpp_2m_sde_flow1": "dinkster.dpmpp_2m_sde",
    "dpmpp_3m_sde_flow1": "dinkster.dpmpp_3m_sde",
    "dpmpp_2m_sde_flow_heun": "dinkster.dpmpp_2m_sde",
    "dpmpp_sde_eps_eta0": "dinkster.dpmpp_sde",
    "dpmpp_3m_sde_eps_eta0": "dinkster.dpmpp_3m_sde",
    "dpm_2_ancestral_flow_scaled_eta0.4": "dinkster.dpm_2_ancestral",
    "dpmpp_2s_ancestral_flow_scaled_eta0.4": "dinkster.dpmpp_2s_ancestral",
    # CFG++ family: goldens ran against the generator's _MockCfgModel,
    # so run_case swaps in CfgMockDenoiser for these (needs_uncond).
    "euler_cfg_pp_eps": "dinkster.euler_cfg_pp",
    "euler_cfg_pp_flow": "dinkster.euler_cfg_pp",
    "euler_ancestral_cfg_pp_eps": "dinkster.euler_ancestral_cfg_pp",
    "euler_ancestral_cfg_pp_eps_eta0.4": "dinkster.euler_ancestral_cfg_pp",
    "euler_ancestral_cfg_pp_flow": "dinkster.euler_ancestral_cfg_pp",
    "euler_ancestral_cfg_pp_flow_scaled": "dinkster.euler_ancestral_cfg_pp",
    "dpmpp_2s_ancestral_cfg_pp_eps": "dinkster.dpmpp_2s_ancestral_cfg_pp",
    "dpmpp_2s_ancestral_cfg_pp_flow_scaled": "dinkster.dpmpp_2s_ancestral_cfg_pp",
    "dpmpp_2m_cfg_pp_eps": "dinkster.dpmpp_2m_cfg_pp",
    "dpmpp_2m_cfg_pp_flow": "dinkster.dpmpp_2m_cfg_pp",
    # res_multistep family: deterministic, ancestral, and CFG++ paths.
    "res_multistep_eps": "dinkster.res_multistep",
    "res_multistep_flow": "dinkster.res_multistep",
    "res_multistep_cfg_pp_eps": "dinkster.res_multistep_cfg_pp",
    "res_multistep_cfg_pp_flow": "dinkster.res_multistep_cfg_pp",
    "res_multistep_ancestral_eps": "dinkster.res_multistep_ancestral",
    "res_multistep_ancestral_eps_eta0.4": "dinkster.res_multistep_ancestral",
    "res_multistep_ancestral_flow": "dinkster.res_multistep_ancestral",
    "res_multistep_ancestral_flow_scaled": "dinkster.res_multistep_ancestral",
    "res_multistep_ancestral_cfg_pp_eps": "dinkster.res_multistep_ancestral_cfg_pp",
    "res_multistep_ancestral_cfg_pp_flow_scaled": "dinkster.res_multistep_ancestral_cfg_pp",
}
CASE_DESCRIPTOR.update(
    {name: "dinkster.er_sde" for name in SOLVERS["cases"] if name.startswith("er_sde_current_")}
)
CASE_DESCRIPTOR["sa_solver_current_configured"] = "dinkster.configured_sa_solver"

# Port draw counts differ from the golden's reference counts exactly
# where the reference draws with a zero coefficient and the port skips.
PORT_DRAWS_OVERRIDE = {
    "euler_ancestral_eps_eta0": 0,
    "heunpp2_eps": 0,
    "dpm_fast_eps": 0,
    "dpm_fast_flow": 0,
    "dpm_adaptive_eps": 0,
    "dpm_adaptive_eps_eta2": 8,
    "dpm_adaptive_flow_order2_options": 4,
}


def run_case(name: str, descriptor_id: str) -> tuple[Vec, CountingNoise]:
    case = SOLVERS["cases"][name]
    descriptor = builtin_sampler_registry().get(descriptor_id)
    assert descriptor is not None
    solver = descriptor.build(**case["options"])
    noise = CountingNoise()
    x = Vec(tuple(SOLVERS["x0"]))
    sigmas = tuple(SOLVERS["sigmas"][case["space"]])
    if name in OFFSET_CASES:
        sigmas = offset_first_sigma_for_snr(sigmas, FlowSigmas(shift=1.0), flow=True)
    denoiser = CfgMockDenoiser() if descriptor.needs_uncond else mock_denoised
    final = solver(denoiser, x, sigmas, SPACE_INFO[case["space"]], noise=noise)
    return final, noise


class TestSolverGoldens:
    @pytest.mark.parametrize("name", sorted(CASE_DESCRIPTOR))
    def test_final_matches_reference(self, name: str) -> None:
        case = SOLVERS["cases"][name]
        final, noise = run_case(name, CASE_DESCRIPTOR[name])
        # DEIS evaluates 10,000-point transcendental tables with scalar
        # math instead of torch kernels; the observed float64 seam is
        # 5.63e-8, with 7e-8 headroom and identical integration/order math.
        # DPM-fast's reference torch.linspace/transcendentals versus the
        # scalar float64 port drift by at most 2.90e-8; 4e-8 is per-case
        # headroom after the endpoint/order seams were verified exactly.
        # ER-SDE deliberately mirrors the reference's float32 integration
        # grid with scalar math; its measured seam is 7.49e-9, with 1.3e-8
        # headroom and identical stage/noise equations.
        # UniPC's portable torch-free solver deliberately evaluates the
        # reference's float32 tensor coefficients and linear solves as
        # Python float64 scalar math. Its 2e-5 band covers that proven
        # portable/reference arithmetic seam; torch runtimes replace it
        # with the exact reference-kernel override.
        abs_tol = (
            2e-5
            if name.startswith("uni_pc")
            else 4e-8
            if name.startswith("dpm_fast_")
            else 7e-8
            if name.startswith("deis_")
            else 1.3e-8
            if name.startswith("er_sde_")
            else ABS
        )
        for i, (ours, ref) in enumerate(zip(final.values, case["final"], strict=True)):
            assert math.isclose(ours, ref, rel_tol=REL, abs_tol=abs_tol), (
                f"{name} index {i}: {ours} != {ref}"
            )
        expected_draws = PORT_DRAWS_OVERRIDE.get(name, case["noise_draws"])
        assert len(noise.calls) == expected_draws, (
            f"{name}: {len(noise.calls)} draws != {expected_draws}"
        )

    def test_configured_sa_solver_capture_uses_current_node_contract(self) -> None:
        case = SOLVERS["cases"]["sa_solver_current_configured"]
        assert case["reference_commit"] == "1d48d9cf7bcecb6022a87b3cb13e0fb435bf9b8a"
        assert case["reference_node_options"] == {
            "eta": 0.65,
            "sde_start_percent": 0.17,
            "sde_end_percent": 0.73,
            "s_noise": 0.6,
            "predictor_order": 5,
            "corrector_order": 2,
            "use_pece": True,
            "simple_order_2": True,
        }

    @pytest.mark.parametrize(
        "name",
        sorted(
            name
            for name in CASE_DESCRIPTOR
            if SOLVERS["cases"][name]["space"].startswith("flow")
            and CASE_DESCRIPTOR[name] != "dinkster.lcm"
        ),
    )
    def test_image_to_image_flow_uses_every_const_solver_dispatch_branch(self, name: str) -> None:
        case = SOLVERS["cases"][name]
        descriptor = builtin_sampler_registry().get(CASE_DESCRIPTOR[name])
        assert descriptor is not None
        sigmas = tuple(SOLVERS["sigmas"][case["space"]])
        if name in OFFSET_CASES:
            sigmas = offset_first_sigma_for_snr(sigmas, FlowSigmas(shift=1.0), flow=True)
        denoiser = CfgMockDenoiser() if descriptor.needs_uncond else mock_denoised
        flow_noise = CountingNoise()
        image_flow_noise = CountingNoise()
        options = case["options"]
        flow = descriptor.build(**options)(
            denoiser,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            SPACE_INFO[case["space"]],
            noise=flow_noise,
        )
        image_flow = descriptor.build(**options)(
            denoiser,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            replace(
                SPACE_INFO[case["space"]],
                parameterization=Parameterization.IMAGE_TO_IMAGE_FLOW,
            ),
            noise=image_flow_noise,
        )

        assert image_flow.values == flow.values
        assert image_flow_noise.calls == flow_noise.calls

    @pytest.mark.parametrize(
        "name",
        sorted(
            name
            for name, descriptor_id in CASE_DESCRIPTOR.items()
            if descriptor_id not in {"dinkster.dpm_fast", "dinkster.dpm_adaptive"}
        ),
    )
    def test_fixed_row_solver_paths_begin_every_outer_step(self, name: str) -> None:
        case = SOLVERS["cases"][name]
        descriptor = builtin_sampler_registry().get(CASE_DESCRIPTOR[name])
        assert descriptor is not None
        sigmas = tuple(SOLVERS["sigmas"][case["space"]])
        if name in OFFSET_CASES:
            sigmas = offset_first_sigma_for_snr(sigmas, FlowSigmas(shift=1.0), flow=True)
        begun: list[int] = []
        denoiser = CfgMockDenoiser() if descriptor.needs_uncond else mock_denoised

        run_step_begin_solver(
            descriptor.build(**case["options"]),
            denoiser,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            SPACE_INFO[case["space"]],
            noise=CountingNoise(),
            on_step=None,
            on_step_begin=begun.append,
        )

        assert begun == list(range(len(sigmas) - 1))

    def test_2m_sde_heun_descriptor_matches_solver_type_option(self) -> None:
        """dinkster.dpmpp_2m_sde_heun is dpmpp_2m_sde with solver_type
        pinned - same golden, same math (sample_dpmpp_2m_sde_heun
        @ 947c2749 is the same delegation)."""
        case = SOLVERS["cases"]["dpmpp_2m_sde_eps_heun"]
        descriptor = builtin_sampler_registry().get("dinkster.dpmpp_2m_sde_heun")
        assert descriptor is not None
        solver = descriptor.build()  # solver_type is not an option here
        noise = CountingNoise()
        final = solver(
            mock_denoised,
            Vec(tuple(SOLVERS["x0"])),
            tuple(SOLVERS["sigmas"]["eps"]),
            SPACE_INFO["eps"],
            noise=noise,
        )
        for ours, ref in zip(final.values, case["final"], strict=True):
            assert math.isclose(ours, ref, rel_tol=REL, abs_tol=ABS)

    def test_noise_call_arguments(self) -> None:
        """Ancestral draws receive (sigmas[i], sigmas[i+1]) exactly as
        the reference passes to noise_sampler; SDE step-1 draws receive
        (sigmas[i], sigma_s_1) - the first element is always the
        current sigma."""
        sigmas = SOLVERS["sigmas"]["eps"]
        _, noise = run_case("euler_ancestral_eps", "dinkster.euler_ancestral")
        assert noise.calls == [(sigmas[i], sigmas[i + 1]) for i in range(len(sigmas) - 2)]
        _, sde_noise = run_case("dpmpp_sde_eps", "dinkster.dpmpp_sde")
        froms = [call[0] for call in sde_noise.calls]
        assert froms == [s for s in sigmas[:-2] for _ in range(2)]


class TestSolverEdges:
    @pytest.mark.parametrize(
        "descriptor",
        builtin_samplers(),
        ids=lambda d: d.id,
    )
    def test_empty_and_single_schedules_are_identity(
        self, descriptor: SamplerDescriptor[Any]
    ) -> None:
        """No intervals, no work: matches the reference's range(len-1)
        loops and its len(sigmas) <= 1 early-outs. (Deliberate deviation
        for dinkster.lcm: the reference forces one iteration and would
        IndexError on a single-sigma schedule; the port returns x.)"""
        solver = descriptor.build()
        x = Vec(tuple(SOLVERS["x0"]))
        info = SPACE_INFO["eps"]
        denoiser = CfgMockDenoiser() if descriptor.needs_uncond else mock_denoised
        assert solver(denoiser, x, (), info) is x
        assert solver(denoiser, x, (1.0,), info) is x

    def test_missing_noise_is_loud(self) -> None:
        solver = euler_ancestral()
        with pytest.raises(ValueError, match="noise sampler"):
            solver(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 0.5, 0.0),
                SPACE_INFO["eps"],
            )

    def test_res_multistep_noise_required_only_for_nonzero_draw(self) -> None:
        x = Vec(tuple(SOLVERS["x0"]))
        sigmas = tuple(SOLVERS["sigmas"]["eps"])
        info = SPACE_INFO["eps"]
        # eta 0 makes sigma_up zero, so no sampler is required.
        res_multistep_ancestral(eta=0.0)(mock_denoised, x, sigmas, info)
        with pytest.raises(ValueError, match="res_multistep_ancestral requires"):
            res_multistep_ancestral()(mock_denoised, x, sigmas, info)

    def test_res_multistep_refuses_degenerate_schedule(self) -> None:
        with pytest.raises(ValueError, match="degenerate schedule"):
            res_multistep()(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 0.5, 0.5, 0.0),
                SPACE_INFO["eps"],
            )

    @pytest.mark.parametrize("descriptor_id", ["dinkster.lms", "dinkster.ipndm_v"])
    def test_multistep_refuses_degenerate_schedule(self, descriptor_id: str) -> None:
        descriptor = builtin_sampler_registry().get(descriptor_id)
        assert descriptor is not None
        name = descriptor_id.removeprefix("dinkster.")
        with pytest.raises(ValueError, match=rf"{name} degenerate schedule"):
            descriptor.build()(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 0.5, 0.5, 0.25, 0.0),
                SPACE_INFO["eps"],
            )

    def test_deterministic_solvers_never_draw(self) -> None:
        """euler at s_churn=0 and the other NONE/GAUSSIAN-optional paths
        run without a noise sampler at all - proven for every case whose
        golden recorded zero draws."""
        for name, case in SOLVERS["cases"].items():
            if PORT_DRAWS_OVERRIDE.get(name, case["noise_draws"]) != 0:
                continue
            descriptor = builtin_sampler_registry().get(CASE_DESCRIPTOR[name])
            assert descriptor is not None
            solver = descriptor.build(**case["options"])
            denoiser = CfgMockDenoiser() if descriptor.needs_uncond else mock_denoised
            final = solver(
                denoiser,
                Vec(tuple(SOLVERS["x0"])),
                tuple(SOLVERS["sigmas"][case["space"]]),
                SPACE_INFO[case["space"]],
            )
            abs_tol = (
                2e-5
                if name.startswith("uni_pc")
                else 4e-8
                if name.startswith("dpm_fast_")
                else 7e-8
                if name.startswith("deis_")
                else ABS
            )
            for ours, ref in zip(final.values, case["final"], strict=True):
                assert math.isclose(ours, ref, rel_tol=REL, abs_tol=abs_tol)

    def test_step_callback(self) -> None:
        events: list[StepEvent] = []
        sigmas = tuple(SOLVERS["sigmas"]["eps"])
        euler()(
            mock_denoised,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            SPACE_INFO["eps"],
            on_step=events.append,
        )
        n = len(sigmas) - 1
        assert [e.step for e in events] == list(range(n))
        assert all(e.total == n for e in events)
        assert [e.sigma for e in events] == list(sigmas[:-1])

    def test_solver_state_callback_carries_the_callback_point_tensors(self) -> None:
        states: list[SolverStateEvent[object]] = []
        sigmas = tuple(SOLVERS["sigmas"]["eps"])
        initial = Vec(tuple(SOLVERS["x0"]))
        info = SamplerInfo(Parameterization.EPS, on_state=states.append)
        euler()(mock_denoised, initial, sigmas, info)

        assert len(states) == len(sigmas) - 1
        assert states[0].phase == "pre_update"
        assert states[0].current is initial
        assert states[0].denoised == mock_denoised(initial, sigmas[0])

    @pytest.mark.parametrize("name", sorted(CASE_DESCRIPTOR))
    def test_every_solver_path_emits_state_and_propagates_cancellation(self, name: str) -> None:
        case = SOLVERS["cases"][name]
        descriptor = builtin_sampler_registry().get(CASE_DESCRIPTOR[name])
        assert descriptor is not None
        solver = descriptor.build(**case["options"])
        sigmas = tuple(SOLVERS["sigmas"][case["space"]])
        if name in OFFSET_CASES:
            sigmas = offset_first_sigma_for_snr(sigmas, FlowSigmas(shift=1.0), flow=True)

        def cancel_state(_event: SolverStateEvent[object]) -> None:
            raise KeyboardInterrupt

        info = replace(SPACE_INFO[case["space"]], on_state=cancel_state)
        denoiser = CfgMockDenoiser() if descriptor.needs_uncond else mock_denoised

        with pytest.raises(KeyboardInterrupt):
            solver(
                denoiser,
                Vec(tuple(SOLVERS["x0"])),
                sigmas,
                info,
                noise=CountingNoise(),
            )

    def test_callback_exception_cancels(self) -> None:
        """Cancellation is a raising callback: it propagates immediately
        and stops driving the denoiser."""
        calls = 0

        def counting_denoiser(x: Vec, sigma: float) -> Vec:
            nonlocal calls
            calls += 1
            return mock_denoised(x, sigma)

        def cancel(event: StepEvent) -> None:
            raise KeyboardInterrupt

        with pytest.raises(KeyboardInterrupt):
            euler()(
                counting_denoiser,
                Vec(tuple(SOLVERS["x0"])),
                tuple(SOLVERS["sigmas"]["eps"]),
                SPACE_INFO["eps"],
                on_step=cancel,
            )
        assert calls == 1

    @pytest.mark.parametrize(
        "descriptor_id",
        ["dinkster.dpmpp_sde", "dinkster.dpmpp_2m_sde", "dinkster.dpmpp_3m_sde"],
    )
    def test_flow_sde_requires_offset_first_sigma(self, descriptor_id: str) -> None:
        """logit(1) is infinite: the SDE solvers refuse a flow schedule
        starting at sigma >= 1 and point at offset_first_sigma_for_snr
        (the reference clamps inside the solver via model probing
        @ 947c2749; here schedule preparation owns it)."""
        descriptor = builtin_sampler_registry().get(descriptor_id)
        assert descriptor is not None
        solver = descriptor.build()
        with pytest.raises(ValueError, match="offset_first_sigma_for_snr"):
            solver(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 0.5, 0.0),
                SPACE_INFO["flow"],
                noise=CountingNoise(),
            )

    def test_offset_first_sigma_for_snr(self) -> None:
        space = FlowSigmas(shift=3.0)
        sigmas = (1.0, 0.5, 0.0)
        adjusted = offset_first_sigma_for_snr(sigmas, space, flow=True)
        assert adjusted[0] == space.percent_to_sigma(1e-4)
        assert adjusted[0] < 1.0
        assert adjusted[1:] == sigmas[1:]
        # Identity: non-flow, already-below-1, and trivial schedules.
        assert offset_first_sigma_for_snr(sigmas, space, flow=False) == sigmas
        below = (0.98, 0.5, 0.0)
        assert offset_first_sigma_for_snr(below, space, flow=True) == below
        assert offset_first_sigma_for_snr((1.0,), space, flow=True) == (1.0,)


class TestOptions:
    def test_unknown_option_is_loud(self) -> None:
        with pytest.raises(ValueError, match="unknown option"):
            builtin_sampler_registry().get("dinkster.euler").build(churn=1.0)  # type: ignore[union-attr]

    def test_bounds_enforced(self) -> None:
        descriptor = builtin_sampler_registry().get("dinkster.euler_ancestral")
        assert descriptor is not None
        with pytest.raises(ValueError, match="must be >="):
            descriptor.build(eta=-0.1)

    def test_ancestral_eta_capped_at_one(self) -> None:
        """eta > 1 drives the RF downstep sigma to zero or negative
        (division/log blowups the reference answers with NaNs), so the
        supported domain is [0, 1] - enforced on both the descriptor
        option schema and the exported factories."""
        for descriptor_id in (
            "dinkster.euler_ancestral",
            "dinkster.dpm_2_ancestral",
            "dinkster.dpmpp_2s_ancestral",
            "dinkster.euler_ancestral_cfg_pp",
            "dinkster.dpmpp_2s_ancestral_cfg_pp",
            "dinkster.res_multistep_ancestral",
            "dinkster.res_multistep_ancestral_cfg_pp",
        ):
            descriptor = builtin_sampler_registry().get(descriptor_id)
            assert descriptor is not None
            with pytest.raises(ValueError, match="must be <="):
                descriptor.build(eta=1.5)
        for factory in (
            euler_ancestral,
            dpm_2_ancestral,
            dpmpp_2s_ancestral,
            euler_ancestral_cfg_pp,
            dpmpp_2s_ancestral_cfg_pp,
            res_multistep_ancestral,
            res_multistep_ancestral_cfg_pp,
        ):
            with pytest.raises(ValueError, match=r"eta must be in \[0, 1\]"):
                factory(eta=1.5)

    def test_bool_is_not_a_float(self) -> None:
        spec = OptionSpec("eta", OptionKind.FLOAT, 1.0)
        with pytest.raises(ValueError, match="expects a float"):
            spec.check(True)
        assert spec.check(2) == 2.0  # ints normalize

    def test_nan_rejected(self) -> None:
        spec = OptionSpec("eta", OptionKind.FLOAT, 1.0)
        with pytest.raises(ValueError, match="NaN"):
            spec.check(math.nan)

    def test_choice_enforced(self) -> None:
        descriptor = builtin_sampler_registry().get("dinkster.dpmpp_2m_sde")
        assert descriptor is not None
        with pytest.raises(ValueError, match="expects one of"):
            descriptor.build(solver_type="bogus")

    def test_factory_guards(self) -> None:
        with pytest.raises(ValueError, match="r must be > 0"):
            dpmpp_sde(r=0.0)
        with pytest.raises(ValueError, match="solver_type"):
            dpmpp_2m_sde(solver_type="bogus")

    def test_resolve_options_defaults(self) -> None:
        schema = (
            OptionSpec("eta", OptionKind.FLOAT, 1.0),
            OptionSpec("s_noise", OptionKind.FLOAT, 1.0),
        )
        assert resolve_options(schema, {}) == {"eta": 1.0, "s_noise": 1.0}
        assert resolve_options(schema, {"eta": 0}) == {
            "eta": 0.0,
            "s_noise": 1.0,
        }


class TestCfgPP:
    """The CFG++ family's capability seam: the reference smuggles the
    uncond out through a post-CFG hook; here it is the UncondDenoiser
    method, declared on descriptors and enforced loudly."""

    CFG_PP_IDS = (
        "dinkster.euler_cfg_pp",
        "dinkster.euler_ancestral_cfg_pp",
        "dinkster.dpmpp_2s_ancestral_cfg_pp",
        "dinkster.dpmpp_2m_cfg_pp",
        "dinkster.res_multistep_cfg_pp",
        "dinkster.res_multistep_ancestral_cfg_pp",
        "dinkster.gradient_estimation_cfg_pp",
    )

    def test_needs_uncond_flags_exactly_the_family(self) -> None:
        flagged = tuple(d.id for d in builtin_samplers() if d.needs_uncond)
        assert flagged == self.CFG_PP_IDS

    @pytest.mark.parametrize(
        "factory, name",
        [
            (euler_cfg_pp, "euler_cfg_pp"),
            (euler_ancestral_cfg_pp, "euler_ancestral_cfg_pp"),
            (dpmpp_2s_ancestral_cfg_pp, "dpmpp_2s_ancestral_cfg_pp"),
            (dpmpp_2m_cfg_pp, "dpmpp_2m_cfg_pp"),
            (res_multistep_cfg_pp, "res_multistep_cfg_pp"),
            (
                res_multistep_ancestral_cfg_pp,
                "res_multistep_ancestral_cfg_pp",
            ),
        ],
    )
    def test_plain_denoiser_is_refused_by_name(self, factory: Any, name: str) -> None:
        """Each solver refuses a capability-less denoiser before any
        stepping, naming ITSELF - including euler_cfg_pp, which
        delegates to the ancestral implementation."""
        solver = factory()
        with pytest.raises(ValueError, match=rf"{name} is a CFG\+\+ solver"):
            solver(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 0.5, 0.0),
                SPACE_INFO["eps"],
                noise=CountingNoise(),
            )

    def test_uncond_actually_steers(self) -> None:
        """The uncond channel must influence the result: the same case
        with a denoiser whose uncond equals its combined output lands
        somewhere else than the golden."""
        case = SOLVERS["cases"]["euler_cfg_pp_eps"]

        class DegenerateUncond:
            def __call__(self, x: Vec, sigma: float) -> Vec:
                return mock_denoised(x, sigma)

            def call_with_uncond(self, x: Vec, sigma: float) -> tuple[Vec, Vec]:
                out = mock_denoised(x, sigma)
                return out, out

        final = euler_cfg_pp()(
            DegenerateUncond(),
            Vec(tuple(SOLVERS["x0"])),
            tuple(SOLVERS["sigmas"]["eps"]),
            SPACE_INFO["eps"],
        )
        assert any(
            not math.isclose(ours, ref, rel_tol=REL, abs_tol=ABS)
            for ours, ref in zip(final.values, case["final"], strict=True)
        )


class TestCatalogs:
    def test_ar_video_selection_and_capability_delegation(self) -> None:
        selection = select_builtin_sampler("ar_video", num_frame_per_block=3)
        assert selection == BuiltinSamplerSelection(
            "dinkster.ar_video", (("num_frame_per_block", 3),)
        )
        with pytest.raises(FrozenInstanceError):
            selection.sampler_id = "dinkster.euler"  # type: ignore[misc]
        with pytest.raises(ValueError, match="num_frame_per_block.*must be <= 64"):
            select_builtin_sampler("ar_video", num_frame_per_block=65)

        calls: list[tuple[Any, ...]] = []

        class ARSession:
            block_count = 2
            sigma_step_count = 2

            def __init__(self, x: Vec) -> None:
                self.current = x

            def begin_block(self, block_index: int) -> None:
                calls.append(("begin", block_index))

            def evaluate(
                self, sigma: float, *, capture_state: bool
            ) -> tuple[Vec | None, Vec | None, Vec]:
                denoised = self.current + 1.0
                calls.append(("evaluate", sigma, capture_state))
                return (
                    self.current if capture_state else None,
                    denoised if capture_state else None,
                    denoised,
                )

            def advance(self, denoised: Vec, sigma_next: float, seed: int) -> None:
                calls.append(("advance", sigma_next, seed))
                self.current = denoised

            def commit_block(self) -> None:
                calls.append(("commit",))

            def finish(self) -> Vec:
                calls.append(("finish",))
                return self.current

        class ARDenoiser:
            def __call__(self, x: Vec, sigma: float) -> Vec:
                del sigma
                return x

            def prepare_autoregressive(
                self,
                x: Vec,
                sigmas: Sequence[float],
                *,
                num_frame_per_block: int,
            ) -> ARSession:
                calls.append(("prepare", x, tuple(sigmas), num_frame_per_block))
                return ARSession(x)

        descriptor = builtin_sampler_registry().get(selection.sampler_id)
        assert descriptor is not None
        solver = descriptor.build(**dict(selection.options))
        x = Vec((1.0, 2.0, 3.0))
        sigmas = (1.0, 0.5, 0.0)
        result = solver(
            ARDenoiser(),
            x,
            sigmas,
            SamplerInfo(Parameterization.FLOW, seed=17),
        )
        assert result == x + 4.0
        assert calls == [
            ("prepare", x, sigmas, 3),
            ("begin", 0),
            ("evaluate", 1.0, False),
            ("advance", 0.5, 17),
            ("evaluate", 0.5, False),
            ("advance", 0.0, 18),
            ("commit",),
            ("begin", 1),
            ("evaluate", 1.0, False),
            ("advance", 0.5, 1017),
            ("evaluate", 0.5, False),
            ("advance", 0.0, 1018),
            ("commit",),
            ("finish",),
        ]
        assert solver(mock_denoised, x, (0.0,), SPACE_INFO["flow"]) is x
        with pytest.raises(TypeError, match="autoregressive denoiser"):
            solver(mock_denoised, x, sigmas, SPACE_INFO["flow"])

        cancellation = CancellationFlag()

        class CancellingARDenoiser(ARDenoiser):
            def prepare_autoregressive(
                self,
                x: Vec,
                sigmas: Sequence[float],
                *,
                num_frame_per_block: int,
            ) -> ARSession:
                cancellation.cancel()
                return super().prepare_autoregressive(
                    x,
                    sigmas,
                    num_frame_per_block=num_frame_per_block,
                )

        with use_sampling_environment((), cancellation):
            with pytest.raises(SamplingCancelled, match="sampling cancelled"):
                solver(CancellingARDenoiser(), x, sigmas, SPACE_INFO["flow"])

    def test_sa_solver_catalog_and_default_tau_requirement(self) -> None:
        descriptors = builtin_samplers()
        index = [descriptor.id for descriptor in descriptors].index("dinkster.sa_solver")
        sa_descriptors = descriptors[index : index + 3]
        assert [descriptor.id for descriptor in sa_descriptors] == [
            "dinkster.sa_solver",
            "dinkster.sa_solver_pece",
            "dinkster.configured_sa_solver",
        ]
        for descriptor in sa_descriptors[:2]:
            assert descriptor.noise is NoiseKind.GAUSSIAN
            assert [(option.name, option.default) for option in descriptor.options] == [
                ("s_noise", 1.0),
                ("predictor_order", 3),
                ("corrector_order", 4),
                ("simple_order_2", False),
            ]
        configured = sa_descriptors[2]
        assert configured.noise is NoiseKind.GAUSSIAN
        assert [
            (option.name, option.default, option.minimum, option.maximum)
            for option in configured.options
        ] == [
            ("eta", 1.0, 0.0, 10.0),
            ("sde_start_sigma", 1.0, 0.0, None),
            ("sde_end_sigma", 0.0, 0.0, None),
            ("s_noise", 1.0, 0.0, 100.0),
            ("predictor_order", 3, 1, 6),
            ("corrector_order", 4, 0, 6),
            ("use_pece", False, None, None),
            ("simple_order_2", False, None, None),
        ]
        with pytest.raises(ValueError, match="SamplerInfo.percent_to_sigma"):
            sa_descriptors[0].build()(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 0.5, 0.0),
                SamplerInfo(parameterization=Parameterization.EPS),
                noise=CountingNoise(),
            )

    def test_sampler_catalog_shape(self) -> None:
        descriptors = builtin_samplers()
        assert len(descriptors) == 63
        ids = [d.id for d in descriptors]
        assert len(set(ids)) == len(ids)
        assert all(d.id.startswith(("dinkster.", "res4lyf.")) for d in descriptors)
        # Every descriptor carries the matching legacy ComfyUI alias.
        for d in descriptors:
            assert d.id.split(".", 1)[1] in d.aliases

    def test_catalogs_reconstruct_fresh_descriptors_per_call(self) -> None:
        """Each catalog call builds new descriptor objects from deep
        snapshots captured at import: the published descriptor constants
        are caller-reachable and mutable via ``object.__setattr__``, so
        no shared instance - descriptor or nested container - may double
        as the admission trust root. Fresh constructions stay
        behaviorally canonical (catalog_value_is_canonical), with
        behavior-bearing functions identical across calls."""
        from dataclasses import fields as dataclass_fields

        from dinkster_inference import catalog_value_is_canonical

        for first, second in (
            (builtin_samplers(), builtin_samplers()),
            (builtin_schedulers(), builtin_schedulers()),
        ):
            assert len(first) == len(second)
            for left, right in zip(first, second, strict=True):
                assert left is not right
                assert type(left) is type(right)
                names = {item.name for item in dataclass_fields(left)}
                assert set(vars(left)) == set(vars(right)) == names
                for name in names:
                    left_value = getattr(left, name)
                    right_value = getattr(right, name)
                    assert catalog_value_is_canonical(left_value, right_value)
                    if callable(left_value):
                        assert left_value is right_value
                    elif type(left_value) is tuple and left_value:
                        assert left_value is not right_value

    def test_sampler_registry_lookup(self) -> None:
        registry = builtin_sampler_registry()
        assert registry.get("dinkster.euler") is not None
        # Legacy ComfyUI vocabulary resolves via aliases.
        assert registry.get("euler") is registry.get("dinkster.euler")
        assert registry.get("dpmpp_2m") is registry.get("dinkster.dpmpp_2m")
        assert registry.get("nonexistent") is None
        # Aliases never appear as identity.
        assert "euler" not in registry.ids()

    def test_ddim_catalog_alias_export_and_order(self) -> None:
        catalog = builtin_samplers()
        descriptor = catalog[[item.id for item in catalog].index("dinkster.ddim")]
        assert descriptor.id == "dinkster.ddim"
        assert descriptor.display_name == "DDIM"
        assert descriptor.aliases == ("ddim",)
        assert descriptor.options == ()
        assert descriptor.noise is NoiseKind.NONE
        assert descriptor.random_inpaint_noise
        assert [item.id for item in builtin_samplers() if item.random_inpaint_noise] == [
            "dinkster.ddim"
        ]
        registry_ddim = builtin_sampler_registry().get("ddim")
        assert registry_ddim is not None
        # Catalogs reconstruct per call, so cross-construction lookup
        # yields a distinct object with identical field values.
        assert registry_ddim is not descriptor
        assert vars(registry_ddim) == vars(descriptor)
        assert callable(ddim)

    def test_unipc_tail_metadata_exports_and_degenerate_errors(self) -> None:
        catalog = builtin_samplers()
        index = [item.id for item in catalog].index("dinkster.ddim")
        ddim_descriptor, bh1, bh2 = catalog[index : index + 3]
        assert [d.id for d in (ddim_descriptor, bh1, bh2)] == [
            "dinkster.ddim",
            "dinkster.uni_pc",
            "dinkster.uni_pc_bh2",
        ]
        assert bh1.aliases == ("uni_pc",)
        assert bh2.aliases == ("uni_pc_bh2",)
        assert bh1.discard_penultimate and bh2.discard_penultimate
        assert bh1.noise is bh2.noise is NoiseKind.NONE
        assert callable(uni_pc) and callable(uni_pc_bh2)
        for descriptor in (bh1, bh2):
            with pytest.raises(ValueError, match=rf"{descriptor.aliases[0]} degenerate schedule"):
                descriptor.build()(
                    mock_denoised,
                    Vec(tuple(SOLVERS["x0"])),
                    (1.0, 1.0, 0.0),
                    SPACE_INFO["eps"],
                )

    def test_ddim_build_is_exact_default_euler_without_inpaint(self) -> None:
        descriptor = builtin_sampler_registry().get("ddim")
        assert descriptor is not None
        x = Vec(tuple(SOLVERS["x0"]))
        sigmas = tuple(SOLVERS["sigmas"]["eps"])
        expected = euler()(mock_denoised, x, sigmas, SPACE_INFO["eps"])
        assert descriptor.build()(mock_denoised, x, sigmas, SPACE_INFO["eps"]) == expected
        assert ddim(mock_denoised, x, sigmas, SPACE_INFO["eps"]) == expected

    def test_deis_catalog_position_options_alias_and_noise(self) -> None:
        descriptors = builtin_samplers()
        index = next(
            i for i, descriptor in enumerate(descriptors) if descriptor.id == "dinkster.deis"
        )
        assert descriptors[index - 1].id == "dinkster.ipndm_v"
        assert descriptors[index + 1].id == "dinkster.res_multistep"
        descriptor = descriptors[index]
        assert descriptor.aliases == ("deis",)
        assert descriptor.noise is NoiseKind.NONE
        assert [(option.name, option.default) for option in descriptor.options] == [
            ("max_order", 3),
            ("deis_mode", "tab"),
        ]

    def test_dpm_catalog_positions_options_aliases_and_noise(self) -> None:
        descriptors = builtin_samplers()
        index = next(
            i for i, descriptor in enumerate(descriptors) if descriptor.id == "dinkster.dpm_fast"
        )
        assert descriptors[index - 1].id == "dinkster.lms"
        assert descriptors[index + 1].id == "dinkster.dpm_adaptive"
        assert descriptors[index + 2].id == "dinkster.dpmpp_2s_ancestral"
        fast, adaptive = descriptors[index : index + 2]
        assert fast.aliases == ("dpm_fast",)
        assert adaptive.aliases == ("dpm_adaptive",)
        assert fast.noise is adaptive.noise is NoiseKind.GAUSSIAN
        assert [(option.name, option.default) for option in fast.options] == [
            ("eta", 0.0),
            ("s_noise", 1.0),
        ]
        assert [(option.name, option.default) for option in adaptive.options] == [
            ("order", 3),
            ("rtol", 0.05),
            ("atol", 0.0078),
            ("h_init", 0.05),
            ("pcoeff", 0.0),
            ("icoeff", 1.0),
            ("dcoeff", 0.0),
            ("accept_safety", 0.81),
            ("eta", 0.0),
            ("s_noise", 1.0),
        ]

    def test_dpm_named_degenerate_and_option_errors(self) -> None:
        with pytest.raises(ValueError, match="dpm_adaptive order"):
            dpm_adaptive(order=1)
        for descriptor_id in ("dinkster.dpm_fast", "dinkster.dpm_adaptive"):
            descriptor = builtin_sampler_registry().get(descriptor_id)
            assert descriptor is not None
            with pytest.raises(
                ValueError, match=rf"{descriptor_id.removeprefix('dinkster.')} degenerate schedule"
            ):
                descriptor.build()(
                    mock_denoised, Vec(tuple(SOLVERS["x0"])), (0.0, 0.0), SPACE_INFO["eps"]
                )

    def test_deis_named_degenerate_and_option_errors(self) -> None:
        with pytest.raises(ValueError, match="deis_mode must be 'tab'"):
            deis(deis_mode="rhoab")
        with pytest.raises(ValueError, match="deis degenerate schedule"):
            deis()(mock_denoised, Vec(tuple(SOLVERS["x0"])), (1.0, 1.0, 0.0), SPACE_INFO["eps"])

    def test_er_sde_catalog_position_options_alias_and_noise(self) -> None:
        descriptors = builtin_samplers()
        index = next(
            i for i, descriptor in enumerate(descriptors) if descriptor.id == "dinkster.er_sde"
        )
        assert descriptors[index - 1].id == "dinkster.gradient_estimation_cfg_pp"
        assert descriptors[index + 1].id == "dinkster.seeds_2"
        descriptor = descriptors[index]
        assert descriptor.aliases == ("er_sde",)
        assert descriptor.noise is NoiseKind.GAUSSIAN
        assert [(option.name, option.default) for option in descriptor.options] == [
            ("solver_type", "ER-SDE"),
            ("max_stage", 3),
            ("eta", 1.0),
            ("s_noise", 1.0),
        ]
        assert descriptor.options[0].choices == ("ER-SDE", "Reverse-time SDE", "ODE")
        assert (descriptor.options[2].minimum, descriptor.options[2].maximum) == (0.0, 100.0)
        assert (descriptor.options[3].minimum, descriptor.options[3].maximum) == (0.0, 100.0)

    def test_er_sde_default_is_bit_identical_to_legacy_scaler(self) -> None:
        descriptor = builtin_sampler_registry().get("dinkster.er_sde")
        assert descriptor is not None
        sigmas = tuple(SOLVERS["sigmas"]["eps"])
        default_noise = CountingNoise()
        default = descriptor.build()(
            mock_denoised,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            SPACE_INFO["eps"],
            noise=default_noise,
        )
        legacy_noise = CountingNoise()
        legacy = er_sde(noise_scaler=lambda value: value * (math.exp(value**0.3) + 10.0))(
            mock_denoised,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            SPACE_INFO["eps"],
            noise=legacy_noise,
        )
        assert default == legacy
        assert default_noise.calls == legacy_noise.calls

    def test_er_sde_current_matrix_has_explicit_authority(self) -> None:
        cases = {
            name: case
            for name, case in SOLVERS["cases"].items()
            if name.startswith("er_sde_current_")
        }
        assert len(cases) == 37
        assert {
            (
                case["options"]["solver_type"],
                case["options"]["eta"],
                case["options"]["max_stage"],
            )
            for case in cases.values()
        } == {
            (solver_type, eta, max_stage)
            for solver_type in ("ER-SDE", "Reverse-time SDE", "ODE")
            for eta in (0.0, 0.5, 1.0, 2.0)
            for max_stage in (1, 2, 3)
        } | {("ER-SDE", 11.0, 3)}
        assert {case["reference_commit"] for case in cases.values()} == {
            "76135e557da1ec7dcb270160f01e597565e3e003"
        }

    def test_er_sde_eta_zero_canonicalizes_every_mode_to_ode(self) -> None:
        descriptor = builtin_sampler_registry().get("dinkster.er_sde")
        assert descriptor is not None
        expected, expected_noise = run_case("er_sde_current_ode_eta2_stage3", descriptor.id)
        assert expected_noise.calls == []
        for solver_type in ("ER-SDE", "Reverse-time SDE", "ODE"):
            noise = CountingNoise()
            actual = descriptor.build(
                solver_type=solver_type,
                max_stage=3,
                eta=0.0,
                s_noise=100.0,
            )(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                tuple(SOLVERS["sigmas"]["eps"]),
                SPACE_INFO["eps"],
                noise=noise,
            )
            assert actual == expected
            assert noise.calls == []

    def test_er_sde_named_invalid_and_degenerate_errors(self) -> None:
        with pytest.raises(ValueError, match="er_sde max_stage"):
            er_sde(max_stage=4)
        with pytest.raises(ValueError, match="er_sde solver_type"):
            er_sde(solver_type="not-a-solver")
        with pytest.raises(ValueError, match="er_sde eta"):
            er_sde(eta=100.1)
        with pytest.raises(ValueError, match="cannot be combined"):
            er_sde(noise_scaler=lambda value: value, eta=0.5)
        with pytest.raises(ValueError, match="er_sde degenerate schedule"):
            er_sde(s_noise=0, max_stage=2)(
                mock_denoised,
                Vec(tuple(SOLVERS["x0"])),
                (1.0, 1.0, 0.5, 0.0),
                SPACE_INFO["eps"],
            )
        with pytest.raises(ValueError, match="offset_first_sigma_for_snr"):
            er_sde()(mock_denoised, Vec(tuple(SOLVERS["x0"])), (1.0, 0.5, 0.0), SPACE_INFO["flow"])

    def test_sampler_registry_collision(self) -> None:
        registry = builtin_sampler_registry()
        with pytest.raises(RegistryError, match="already registered"):
            registry.register(builtin_samplers()[0])

    def test_noise_kinds(self) -> None:
        by_id = {d.id: d.noise for d in builtin_samplers()}
        assert by_id["dinkster.dpmpp_2m"] is NoiseKind.NONE
        for sde in (
            "dinkster.dpmpp_sde",
            "dinkster.dpmpp_2m_sde",
            "dinkster.dpmpp_2m_sde_heun",
            "dinkster.dpmpp_3m_sde",
        ):
            assert by_id[sde] is NoiseKind.BROWNIAN
        for sde_gpu in (
            "dinkster.dpmpp_sde_gpu",
            "dinkster.dpmpp_2m_sde_gpu",
            "dinkster.dpmpp_2m_sde_heun_gpu",
            "dinkster.dpmpp_3m_sde_gpu",
        ):
            assert by_id[sde_gpu] is NoiseKind.BROWNIAN_GPU

    def test_snr_offset_sampler_metadata_matches_reference_set(self) -> None:
        required = {
            "dinkster.exp_heun_2_x0",
            "dinkster.exp_heun_2_x0_sde",
            "dinkster.dpmpp_sde",
            "dinkster.dpmpp_sde_gpu",
            "dinkster.dpmpp_2m_sde",
            "dinkster.dpmpp_2m_sde_gpu",
            "dinkster.dpmpp_2m_sde_heun",
            "dinkster.dpmpp_2m_sde_heun_gpu",
            "dinkster.dpmpp_3m_sde",
            "dinkster.dpmpp_3m_sde_gpu",
            "dinkster.er_sde",
            "dinkster.seeds_2",
            "dinkster.seeds_3",
            "dinkster.sa_solver",
            "dinkster.sa_solver_pece",
            "dinkster.configured_sa_solver",
        }
        assert {d.id for d in builtin_samplers() if d.requires_snr_offset} == required

    @pytest.mark.parametrize("solver", [uni_pc(), uni_pc_bh2()])
    def test_unipc_accepts_one_step_two_sigma_schedule(self, solver: object) -> None:
        result = solver(  # type: ignore[operator]
            mock_denoised,
            Vec(tuple(SOLVERS["x0"])),
            (1.0, 0.0),
            SPACE_INFO["eps"],
        )
        assert all(math.isfinite(value) for value in result.values)

    @pytest.mark.parametrize("solver", [uni_pc(), uni_pc_bh2()])
    def test_unipc_state_matches_the_reported_current_value(self, solver: object) -> None:
        states: list[SolverStateEvent[object]] = []
        sigmas = tuple(SOLVERS["sigmas"]["eps"])
        solver(  # type: ignore[operator]
            mock_denoised,
            Vec(tuple(SOLVERS["x0"])),
            sigmas,
            SamplerInfo(Parameterization.EPS, on_state=states.append),
        )
        assert len(states) == len(sigmas) - 1
        for index, state in enumerate(states):
            assert state.step == index
            assert state.total == len(sigmas) - 1
            assert state.phase == "pre_update"
            assert isinstance(state.current, Vec)
            assert isinstance(state.denoised, Vec)
            assert state.denoised == mock_denoised(state.current, state.sigma)

    def test_optional_float_validates_defaults_and_shape(self) -> None:
        assert OptionSpec("x", OptionKind.OPTIONAL_FLOAT, None, minimum=0).default is None
        with pytest.raises(ValueError, match="expects a float"):
            OptionSpec("x", OptionKind.OPTIONAL_FLOAT, "bad")
        with pytest.raises(ValueError, match="carry no choices"):
            OptionSpec("x", OptionKind.OPTIONAL_FLOAT, None, choices=("bad",))

    def test_gpu_sde_catalog_positions_aliases_options_and_factories(self) -> None:
        descriptors = builtin_samplers()
        ids = [descriptor.id for descriptor in descriptors]
        by_id = {descriptor.id: descriptor.noise for descriptor in descriptors}
        pairs = (
            ("dinkster.dpmpp_sde", "dinkster.dpmpp_sde_gpu"),
            ("dinkster.dpmpp_2m_sde", "dinkster.dpmpp_2m_sde_gpu"),
            ("dinkster.dpmpp_2m_sde_heun", "dinkster.dpmpp_2m_sde_heun_gpu"),
            ("dinkster.dpmpp_3m_sde", "dinkster.dpmpp_3m_sde_gpu"),
        )
        for cpu_id, gpu_id in pairs:
            cpu = descriptors[ids.index(cpu_id)]
            gpu = descriptors[ids.index(gpu_id)]
            assert ids.index(gpu_id) == ids.index(cpu_id) + 1
            assert gpu.aliases == (gpu_id.removeprefix("dinkster."),)
            assert gpu.options == cpu.options
            assert gpu.make is cpu.make
        for gaussian in (
            "dinkster.euler",
            "dinkster.euler_ancestral",
            "dinkster.ddpm",
            "dinkster.lcm",
            "dinkster.euler_ancestral_cfg_pp",
            "dinkster.dpmpp_2s_ancestral_cfg_pp",
            "dinkster.res_multistep_ancestral",
            "dinkster.res_multistep_ancestral_cfg_pp",
        ):
            assert by_id[gaussian] is NoiseKind.GAUSSIAN
        # The deterministic CFG++ pair never draws.
        assert by_id["dinkster.euler_cfg_pp"] is NoiseKind.NONE
        assert by_id["dinkster.dpmpp_2m_cfg_pp"] is NoiseKind.NONE
        assert by_id["dinkster.res_multistep"] is NoiseKind.NONE
        assert by_id["dinkster.res_multistep_cfg_pp"] is NoiseKind.NONE

    def test_res_multistep_catalog_order_and_aliases(self) -> None:
        catalog = builtin_samplers()
        index = [descriptor.id for descriptor in catalog].index("dinkster.res_multistep")
        tail = catalog[index : index + 4]
        assert [descriptor.id for descriptor in tail] == [
            "dinkster.res_multistep",
            "dinkster.res_multistep_cfg_pp",
            "dinkster.res_multistep_ancestral",
            "dinkster.res_multistep_ancestral_cfg_pp",
        ]
        assert [descriptor.aliases for descriptor in tail] == [
            ("res_multistep",),
            ("res_multistep_cfg_pp",),
            ("res_multistep_ancestral",),
            ("res_multistep_ancestral_cfg_pp",),
        ]

    def test_res4lyf_rk_catalog_block_noise_and_options(self) -> None:
        catalog = builtin_samplers()
        ids = [descriptor.id for descriptor in catalog]
        index = ids.index("res4lyf.res_2m")
        block = catalog[index : index + 17]
        # beta/__init__.py wrapper registration order @ 26036f64.
        expected = [
            "res4lyf.res_2m",
            "res4lyf.res_3m",
            "res4lyf.res_2s",
            "res4lyf.res_3s",
            "res4lyf.res_5s",
            "res4lyf.res_6s",
            "res4lyf.res_2m_ode",
            "res4lyf.res_3m_ode",
            "res4lyf.res_2s_ode",
            "res4lyf.res_3s_ode",
            "res4lyf.res_5s_ode",
            "res4lyf.res_6s_ode",
            "res4lyf.deis_2m",
            "res4lyf.deis_3m",
            "res4lyf.deis_2m_ode",
            "res4lyf.deis_3m_ode",
            "res4lyf.rk_beta",
        ]
        assert [descriptor.id for descriptor in block] == expected
        for descriptor in block:
            name = descriptor.id.split(".", 1)[1]
            if name == "res_2m_ode":
                # Carries the retired legacy-module name "rk" as well.
                assert descriptor.aliases == (name, "rk")
            else:
                assert descriptor.aliases == (name,)
            assert descriptor.supports_step_begin
            if name.endswith("_ode"):
                assert descriptor.noise is NoiseKind.NONE
            else:
                assert descriptor.noise is NoiseKind.RES4LYF_GAUSSIAN
            if name == "rk_beta":
                assert [spec.name for spec in descriptor.options] == [
                    "rk_type",
                    "eta",
                    "eta_substep",
                ]
                assert [spec.default for spec in descriptor.options] == [
                    "res_2m",
                    0.5,
                    0.5,
                ]
            else:
                assert descriptor.options == ()
        registry = builtin_sampler_registry()
        assert registry.get("res_2m") is registry.get("res4lyf.res_2m")
        assert registry.get("rk_beta") is registry.get("res4lyf.rk_beta")
        # Retired legacy-module names: "rk" always ran its library defaults
        # (rk_type res_2m, eta 0.0 - deterministic), so it resolves to the
        # beta engine's deterministic res_2m; "legacy_rk" has no beta
        # equivalent and stays unknown.
        assert registry.get("rk") is registry.get("res4lyf.res_2m_ode")
        assert registry.get("legacy_rk") is None

    def test_res4lyf_rk_beta_option_errors_and_build(self) -> None:
        registry = builtin_sampler_registry()
        descriptor = registry.get("res4lyf.rk_beta")
        assert descriptor is not None
        assert callable(descriptor.build(rk_type="res_3s"))
        with pytest.raises(ValueError, match="unknown option"):
            descriptor.build(bogus=1.0)
        with pytest.raises(ValueError):
            descriptor.build(eta=1.5)
        with pytest.raises(ValueError, match="unknown rk_type"):
            res4lyf_rk(rk_type="euler")

    def test_res4lyf_rk_named_refusals(self) -> None:
        x = Vec(tuple(SOLVERS["x0"]))
        solver = res4lyf_rk(rk_type="res_2m")
        bounded = replace(SPACE_INFO["eps"], sigma_min=0.03, sigma_max=14.6)

        # Zero-step schedules return the input untouched.
        assert solver(mock_denoised, x, [1.0], bounded) is x

        with pytest.raises(ValueError, match="EPS and flow parameterizations"):
            solver(
                mock_denoised,
                x,
                [2.0, 1.0, 0.5],
                replace(bounded, parameterization=Parameterization.V_PREDICTION),
            )
        with pytest.raises(ValueError, match="sigma_min and sigma_max"):
            solver(mock_denoised, x, [2.0, 1.0, 0.5], SPACE_INFO["eps"])
        with pytest.raises(ValueError, match="two-stream RK noise sampler"):
            solver(mock_denoised, x, [2.0, 1.0, 0.5], bounded)
        with pytest.raises(ValueError, match="two-stream RK noise sampler"):
            solver(mock_denoised, x, [2.0, 1.0, 0.5], bounded, noise=CountingNoise())

        class TwoStream:
            def __call__(self, sigma_from: float, sigma_to: float) -> Vec:
                return Vec(tuple(0.0 for _ in range(DIMS)))

            def step_noise(self, sigma_from: float, sigma_to: float) -> Vec:
                return Vec(tuple(0.0 for _ in range(DIMS)))

            def substep_noise(self, sigma_from: float, sigma_to: float) -> Vec:
                return Vec(tuple(0.0 for _ in range(DIMS)))

        with pytest.raises(TypeError, match="requires tensor division"):
            solver(mock_denoised, object(), [2.0, 1.0, 0.5], bounded, noise=TwoStream())

    def test_res4lyf_prepare_sigmas_branches_and_refusals(self) -> None:
        # Consecutive duplicates collapse; a trailing zero pulls the
        # model's exact sigma_min in (replacing a smaller neighbor,
        # inserted when the gap exceeds 1e-4, untouched when close).
        assert prepare_rk_sigmas([4.0, 2.0, 2.0, 1.0, 0.0], 0.03) == [
            4.0,
            2.0,
            1.0,
            0.03,
            0.0,
        ]
        assert prepare_rk_sigmas([4.0, 1.0, 0.01, 0.0], 0.03) == [4.0, 1.0, 0.03, 0.0]
        assert prepare_rk_sigmas([4.0, 1.0, 0.030005, 0.0], 0.03) == [
            4.0,
            1.0,
            0.030005,
            0.0,
        ]
        assert prepare_rk_sigmas([4.0, 1.0], 0.03) == [4.0, 1.0]
        with pytest.raises(ValueError, match="at least two sigmas"):
            prepare_rk_sigmas([1.0], 0.03)
        with pytest.raises(ValueError, match="starting at sigma 0"):
            prepare_rk_sigmas([0.0, 1.0], 0.03)

    def test_scheduler_catalog_matches_reference_order(self) -> None:
        # comfy.samplers SCHEDULER_HANDLERS order @ 947c2749, then the two
        # schedulers RES4LYF registers globally in its registration order
        # (RES4LYF __init__.py @ 26036f64).
        assert [d.id for d in builtin_schedulers()] == [
            "dinkster.simple",
            "dinkster.sgm_uniform",
            "dinkster.karras",
            "dinkster.exponential",
            "dinkster.ddim_uniform",
            "dinkster.beta",
            "dinkster.normal",
            "dinkster.linear_quadratic",
            "dinkster.kl_optimal",
            "res4lyf.bong_tangent",
            "res4lyf.beta57",
        ]
        registry = builtin_scheduler_registry()
        assert registry.get("karras") is registry.get("dinkster.karras")
        assert registry.get("bong_tangent") is registry.get("res4lyf.bong_tangent")
        assert registry.get("beta57") is registry.get("res4lyf.beta57")


class TestCanonicalCatalogSnapshots:
    """The builtin catalogs rebuild from deep import-time snapshots: no
    caller-reachable nested object rides into a fresh descriptor, and a
    mutated catalog function refuses loudly instead of executing."""

    def test_fresh_catalogs_share_no_mutable_nested_objects(self) -> None:
        first = {descriptor.id: descriptor for descriptor in builtin_samplers()}
        second = {descriptor.id: descriptor for descriptor in builtin_samplers()}
        for sampler_id, descriptor in first.items():
            other = second[sampler_id]
            assert descriptor is not other
            assert descriptor == other
            if descriptor.options:
                assert descriptor.options is not other.options
                for spec, other_spec in zip(descriptor.options, other.options, strict=True):
                    assert spec is not other_spec
                    assert spec == other_spec

    def test_nested_option_spec_poisoning_stays_isolated(self) -> None:
        from dinkster_inference_torch._portable_solvers import DINKSTER_EULER_ANCESTRAL

        spec = DINKSTER_EULER_ANCESTRAL.options[0]
        canonical_default = spec.default
        object.__setattr__(spec, "default", 999.0)
        try:
            fresh = next(
                descriptor
                for descriptor in builtin_samplers()
                if descriptor.id == DINKSTER_EULER_ANCESTRAL.id
            )
            assert fresh.options[0].default == canonical_default
        finally:
            object.__setattr__(spec, "default", canonical_default)

    def test_mutated_catalog_function_refuses_loudly(self) -> None:
        from dinkster_inference_torch._portable_solvers import DINKSTER_HEUN

        make = DINKSTER_HEUN.make
        assert make is not None
        canonical_code = make.__code__

        def attacker(_options: object) -> object:
            raise AssertionError("attacker code must never build")

        make.__code__ = attacker.__code__
        try:
            with pytest.raises(RuntimeError, match="mutated after import"):
                builtin_samplers()
        finally:
            make.__code__ = canonical_code
        assert len(builtin_samplers()) == 63

    def test_mutated_scheduler_function_refuses_loudly(self) -> None:
        from dinkster_inference.schedules import DINKSTER_KARRAS

        make_sigmas = DINKSTER_KARRAS.make_sigmas
        canonical_code = make_sigmas.__code__

        def attacker(_steps: object, _space: object) -> object:
            raise AssertionError("attacker code must never run")

        make_sigmas.__code__ = attacker.__code__
        try:
            with pytest.raises(RuntimeError, match="mutated after import"):
                builtin_schedulers()
        finally:
            make_sigmas.__code__ = canonical_code
        assert len(builtin_schedulers()) == 11

    def test_canonical_value_comparison_is_behavioral_not_equality(self) -> None:
        from dinkster_inference import catalog_value_is_canonical

        first = next(d for d in builtin_samplers() if d.id == "dinkster.euler_ancestral")
        second = next(d for d in builtin_samplers() if d.id == "dinkster.euler_ancestral")
        assert catalog_value_is_canonical(first.options, second.options)
        assert catalog_value_is_canonical(first.make, second.make)

        class EqualitySpoof:
            def __call__(self, *args: object, **kwargs: object) -> object:
                raise AssertionError("spoof must never run")

            def __eq__(self, _other: object) -> bool:
                return True

            def __hash__(self) -> int:
                return 0

        assert not catalog_value_is_canonical(EqualitySpoof(), second.make)
        poisoned = replace(first.options[0])
        object.__setattr__(poisoned, "extra", "state")
        assert not catalog_value_is_canonical((poisoned,), second.options[:1])


class TestCancellationTrust:
    """Distributed receipt admission executes the ambient cancellation
    between solver steps, so only cancellation that provably runs no
    caller code is trusted: the default no-op or the exact set-only
    CancellationFlag."""

    def test_flag_is_a_set_only_latch(self) -> None:
        from dinkster_inference import CancellationFlag

        flag = CancellationFlag()
        assert flag() is False
        flag.cancel()
        assert flag() is True
        with pytest.raises(AttributeError):
            flag.check = lambda: False  # type: ignore[attr-defined]

    def test_trust_covers_exactly_the_no_op_and_the_flag(self) -> None:
        from dinkster_inference import (
            CancellationFlag,
            sampling_cancellation_is_trusted,
            use_sampling_environment,
        )

        assert sampling_cancellation_is_trusted()
        with use_sampling_environment((), CancellationFlag()):
            assert sampling_cancellation_is_trusted()
        with use_sampling_environment((), lambda: False):
            assert not sampling_cancellation_is_trusted()

        class FlagAlike(CancellationFlag):  # pyright: ignore[reportGeneralTypeIssues]
            def __call__(self) -> bool:
                raise AssertionError("subclass code must never be trusted")

        subclassed = FlagAlike()
        with use_sampling_environment((), subclassed):
            assert not sampling_cancellation_is_trusted()

    def test_planted_slot_value_never_executes(self) -> None:
        """The slot is writable, so a foreign object planted there must
        read as not cancelled without its __bool__ ever running."""
        from dinkster_inference import CancellationFlag, CancellationToken

        executed: list[str] = []

        class Evil:
            def __bool__(self) -> bool:
                executed.append("executed")
                return False

        flag = CancellationFlag()
        flag._cancelled = Evil()  # type: ignore[assignment]
        result = flag()
        assert result is False
        CancellationToken(flag).check()
        assert executed == []
