"""Native inference: step planning (steps.sampling_sigmas / max_denoise).

Pinned against goldens generated by RUNNING the reference
KSampler.set_steps / calculate_sigmas / Sampler.max_denoise @ 947c2749
(tests/goldens/steps_goldens.json, produced by
tools/gen_steps_goldens.py with a torch interpreter). The oracle is
the reference code itself.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    DiscreteSigmas,
    FluxFlowSigmas,
    SigmaSpace,
    max_denoise,
    sampling_sigmas,
)
from dinkster_inference import solvers as solvers_module
from dinkster_inference.sampling import SamplerDescriptor, SchedulerDescriptor
from dinkster_inference.schedules import (
    DINKSTER_KARRAS,
    DINKSTER_NORMAL,
    DINKSTER_SIMPLE,
)
from dinkster_inference.solvers import (
    DINKSTER_DPM_2,
    DINKSTER_DPM_2_ANCESTRAL,
)

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "steps_goldens.json").read_text())

# float32 storage in the reference vs float64 here.
REL = 3e-6

SPACES: dict[str, SigmaSpace] = {
    "discrete_sd": DiscreteSigmas.linear_beta(),
    "flux_shift1.15": FluxFlowSigmas(),
}

SCHEDULERS: dict[str, SchedulerDescriptor] = {
    "normal": DINKSTER_NORMAL,
    "simple": DINKSTER_SIMPLE,
    "karras": DINKSTER_KARRAS,
}

# The goldens vary the reference sampler name; natively the discard
# correction is descriptor data.
DISCARD = {"euler": False, "dpm_2": True}


def _cases() -> list[tuple[str, dict[str, Any]]]:
    return [
        (space_key, entry)
        for space_key, entries in GOLDENS["set_steps"].items()
        for entry in entries
    ]


class TestSamplingSigmas:
    @pytest.mark.parametrize(
        "space_key, entry",
        _cases(),
        ids=lambda v: (
            v
            if isinstance(v, str)
            else (f"{v['scheduler']}-{v['sampler']}-s{v['steps']}-d{v['denoise']}")
        ),
    )
    def test_matches_reference_set_steps(self, space_key: str, entry: dict[str, Any]) -> None:
        ours = sampling_sigmas(
            SCHEDULERS[entry["scheduler"]],
            SPACES[space_key],
            entry["steps"],
            denoise=entry["denoise"],
            discard_penultimate=DISCARD[entry["sampler"]],
        )
        ref: list[float] = entry["sigmas"]
        assert len(ours) == len(ref), f"length {len(ours)} != {len(ref)}"
        for i, (a, b) in enumerate(zip(ours, ref, strict=True)):
            assert math.isclose(a, b, rel_tol=REL, abs_tol=1e-7), f"index {i}: {a} != {b}"

    def test_rejects_zero_steps(self) -> None:
        with pytest.raises(ValueError, match="steps"):
            sampling_sigmas(DINKSTER_NORMAL, SPACES["discrete_sd"], 0)

    def test_denoise_zero_is_empty(self) -> None:
        assert sampling_sigmas(DINKSTER_NORMAL, SPACES["discrete_sd"], 20, denoise=0.0) == ()

    def test_discard_keeps_step_count(self) -> None:
        space = SPACES["discrete_sd"]
        plain = sampling_sigmas(DINKSTER_NORMAL, space, 8)
        discarded = sampling_sigmas(DINKSTER_NORMAL, space, 8, discard_penultimate=True)
        assert len(plain) == len(discarded) == 9
        assert discarded[-1] == plain[-1] == 0.0
        # The correction reschedules with one extra step, so interior
        # sigmas differ from the plain schedule.
        assert discarded[:-1] != plain[:-1]


class TestDiscardDescriptors:
    def test_flagged_solvers_match_reference_set(self) -> None:
        """Every reference DISCARD_PENULTIMATE name that exists
        natively carries the flag; no native solver carries it
        without being in the reference set."""
        reference = set(GOLDENS["discard_penultimate_samplers"])
        descriptors = [
            value for value in vars(solvers_module).values() if isinstance(value, SamplerDescriptor)
        ]
        assert DINKSTER_DPM_2 in descriptors
        assert DINKSTER_DPM_2.discard_penultimate
        assert DINKSTER_DPM_2_ANCESTRAL.discard_penultimate
        for descriptor in descriptors:
            flagged = descriptor.discard_penultimate
            in_reference = bool(reference & set(descriptor.aliases))
            assert flagged == in_reference, descriptor.id


class TestMaxDenoise:
    @pytest.mark.parametrize("space_key", list(SPACES))
    def test_matches_reference(self, space_key: str) -> None:
        sigma_max = SPACES[space_key].sigma_max
        for entry in GOLDENS["max_denoise"][space_key]:
            ours = max_denoise(sigma_max, (entry["sigma0"], 0.0))
            assert ours == entry["result"], entry

    def test_rejects_empty(self) -> None:
        with pytest.raises(ValueError, match="nonempty"):
            max_denoise(1.0, ())
