"""Native inference stage 3a: sigma spaces, schedules, prediction math.

Every port is pinned against goldens generated by RUNNING the ComfyUI
reference implementations @ 947c2749 (tests/goldens/
sampling_goldens.json, produced by tools/gen_sampling_goldens.py with a
torch+scipy interpreter). The oracle is the reference code itself.

The reference stores sigma tables as float32; the native ports compute
in float64, so comparisons use float32-scale relative tolerance.
"""

from __future__ import annotations

import json
import math
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest
from dinkster_inference import (
    SD15,
    SIGMA_PERCENT_ZERO,
    CfgDenoiser,
    ContinuousEDMSigmas,
    DiscreteSigmas,
    FlowSigmas,
    FluxFlowSigmas,
    Parameterization,
    SigmaSpace,
    beta57_schedule,
    beta_schedule,
    bong_tangent_schedule,
    calculate_denoised,
    calculate_input,
    cfg_combine,
    cfg_needs_uncond,
    ddim_uniform_schedule,
    exponential_schedule,
    flux_time_shift,
    inverse_noise_scaling,
    karras_schedule,
    kl_optimal_schedule,
    linear_quadratic_schedule,
    noise_scaling,
    normal_schedule,
    sgm_uniform_schedule,
    simple_schedule,
    time_snr_shift,
)
from dinkster_inference.schedules import (
    _beta_quantile,
    _regularized_incomplete_beta,
)
from dinkster_inference.spaces import linear_beta_sigmas

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "sampling_goldens.json").read_text())
VPRED_GOLDENS = json.loads(
    (
        Path(__file__).parents[1]
        / "packages"
        / "dinkster-inference-torch"
        / "tests"
        / "goldens"
        / "sdxl_vpred_goldens.json"
    ).read_text()
)
EDM_VPRED_GOLDENS = json.loads(
    (
        Path(__file__).parents[1]
        / "packages"
        / "dinkster-inference-torch"
        / "tests"
        / "goldens"
        / "sdxl_edm_vpred_goldens.json"
    ).read_text()
)

# float32 storage in the reference vs float64 here.
REL = 3e-6


def close(a: float, b: float, rel: float = REL) -> bool:
    return math.isclose(a, b, rel_tol=rel, abs_tol=1e-7)


def seq_close(ours: tuple[float, ...], ref: list[float], rel: float = REL) -> None:
    assert len(ours) == len(ref), f"length {len(ours)} != {len(ref)}"
    for i, (a, b) in enumerate(zip(ours, ref, strict=True)):
        assert close(a, b, rel), f"index {i}: {a} != {b}"


@dataclass(frozen=True)
class Vec:
    """A minimal ArithTensor: elementwise math over a float tuple."""

    values: tuple[float, ...]

    def _lift(self, other: Vec | float) -> tuple[float, ...]:
        if isinstance(other, Vec):
            return other.values
        return tuple(other for _ in self.values)

    def __add__(self, other: Vec | float) -> Vec:
        return Vec(tuple(a + b for a, b in zip(self.values, self._lift(other), strict=True)))

    def __sub__(self, other: Vec | float) -> Vec:
        return Vec(tuple(a - b for a, b in zip(self.values, self._lift(other), strict=True)))

    def __mul__(self, other: Vec | float) -> Vec:
        return Vec(tuple(a * b for a, b in zip(self.values, self._lift(other), strict=True)))

    def __truediv__(self, other: Vec | float) -> Vec:
        return Vec(tuple(a / b for a, b in zip(self.values, self._lift(other), strict=True)))

    def clamp(self, minimum: float, maximum: float, /) -> Vec:
        return Vec(tuple(min(max(v, minimum), maximum) for v in self.values))

    def std(self) -> float:
        mean = sum(self.values) / len(self.values)
        return math.sqrt(sum((v - mean) ** 2 for v in self.values) / (len(self.values) - 1))

    def abs(self) -> Vec:
        return Vec(tuple(abs(v) for v in self.values))

    def maximum(self, other: Vec | float, /) -> Vec:
        lifted = self._lift(other)
        return Vec(tuple(max(a, b) for a, b in zip(self.values, lifted, strict=True)))

    def numel(self) -> int:
        return len(self.values)

    def sum(self) -> float:
        return sum(self.values)


def spaces_under_test() -> dict[str, SigmaSpace]:
    return {
        "discrete_sd": DiscreteSigmas.linear_beta(),
        "flow_shift3": FlowSigmas(shift=3.0),
        "flux_shift1.15": FluxFlowSigmas(),
        "continuous_edm": ContinuousEDMSigmas(),
    }


SCHEDULE_FNS = {
    "simple": simple_schedule,
    "sgm_uniform": sgm_uniform_schedule,
    "karras": karras_schedule,
    "exponential": exponential_schedule,
    "ddim_uniform": ddim_uniform_schedule,
    "beta": beta_schedule,
    "normal": normal_schedule,
    "linear_quadratic": linear_quadratic_schedule,
    "kl_optimal": kl_optimal_schedule,
}


class TestSigmaSpaces:
    def test_checkpoint_bounded_continuous_edm_matches_executed_golden(
        self,
    ) -> None:
        bounds = EDM_VPRED_GOLDENS["bounds"]
        golden = EDM_VPRED_GOLDENS["space"]
        space = ContinuousEDMSigmas(min_sigma=bounds["sigma_min"], max_sigma=bounds["sigma_max"])
        table = space.table
        assert table is not None
        seq_close(table[:3], golden["table_head"])
        assert close(table[len(table) // 2], golden["table_mid"])
        seq_close(table[-3:], golden["table_tail"])
        for timestep, sigma in golden["sigma_of_t"].items():
            assert close(space.sigma(float(timestep)), sigma)
        for sigma, timestep in golden["timestep_of_sigma"].items():
            assert close(space.timestep(float(sigma)), timestep)

    @pytest.mark.parametrize(
        ("sigma_min", "sigma_max"),
        ((float("nan"), 1.0), (0.1, float("inf")), (2.0, 1.0)),
    )
    def test_continuous_edm_rejects_invalid_bounds(
        self, sigma_min: float, sigma_max: float
    ) -> None:
        with pytest.raises(ValueError):
            ContinuousEDMSigmas(min_sigma=sigma_min, max_sigma=sigma_max)

    @pytest.mark.parametrize("name", list(spaces_under_test()))
    def test_endpoints_match_reference(self, name: str) -> None:
        space = spaces_under_test()[name]
        ref: dict[str, Any] = GOLDENS["spaces"][name]
        assert close(space.sigma_min, ref["sigma_min"])
        assert close(space.sigma_max, ref["sigma_max"])

    @pytest.mark.parametrize("name", list(spaces_under_test()))
    def test_table_matches_reference(self, name: str) -> None:
        space = spaces_under_test()[name]
        ref: dict[str, Any] = GOLDENS["spaces"][name]
        table = space.table
        assert table is not None
        assert len(table) == ref["table_len"]
        seq_close(table[:3], ref["table_head"])
        seq_close(table[-3:], ref["table_tail"])
        assert close(table[len(table) // 2], ref["table_mid"])

    @pytest.mark.parametrize("name", list(spaces_under_test()))
    def test_sigma_of_t_matches_reference(self, name: str) -> None:
        space = spaces_under_test()[name]
        for t_str, ref_sigma in GOLDENS["spaces"][name]["sigma_of_t"].items():
            assert close(space.sigma(float(t_str)), ref_sigma), t_str

    @pytest.mark.parametrize("name", list(spaces_under_test()))
    def test_timestep_of_sigma_matches_reference(self, name: str) -> None:
        space = spaces_under_test()[name]
        ref = GOLDENS["spaces"][name]["timestep_of_sigma"]
        for sigma_repr, ref_t in ref.items():
            got = space.timestep(float(sigma_repr))
            # Discrete argmin returns an integer index; allow it exact.
            if isinstance(space, DiscreteSigmas):
                assert got == ref_t, sigma_repr
            else:
                assert close(got, ref_t, rel=1e-5), sigma_repr

    @pytest.mark.parametrize("name", list(spaces_under_test()))
    def test_percent_to_sigma_matches_reference(self, name: str) -> None:
        space = spaces_under_test()[name]
        ref = GOLDENS["spaces"][name]["percent_to_sigma"]
        for p_str, ref_sigma in ref.items():
            assert close(space.percent_to_sigma(float(p_str)), ref_sigma), p_str

    def test_percent_zero_sentinel(self) -> None:
        assert DiscreteSigmas.linear_beta().percent_to_sigma(0.0) == (SIGMA_PERCENT_ZERO)
        assert FlowSigmas(shift=3.0).percent_to_sigma(0.0) == 1.0

    def test_discrete_matches_stage2_catalog_constants(self) -> None:
        space = DiscreteSigmas.linear_beta()
        assert math.isclose(space.sigma_min, SD15.sampling.sigma_min, rel_tol=1e-12)
        assert math.isclose(space.sigma_max, SD15.sampling.sigma_max, rel_tol=1e-12)

    def test_discrete_table_validation(self) -> None:
        with pytest.raises(ValueError, match="ascending"):
            DiscreteSigmas((2.0, 1.0))
        with pytest.raises(ValueError, match="positive"):
            DiscreteSigmas((-1.0, 1.0))
        with pytest.raises(ValueError, match="at least 2"):
            DiscreteSigmas((1.0,))

    def test_shift_helpers_match_reference(self) -> None:
        for key, ref in GOLDENS["shift_fns"]["time_snr_shift"].items():
            alpha, t = (float(v) for v in key.split(","))
            assert close(time_snr_shift(alpha, t), ref)
        for key, ref in GOLDENS["shift_fns"]["flux_time_shift"].items():
            mu, t = (float(v) for v in key.split(","))
            assert close(flux_time_shift(mu, 1.0, t), ref)

    def test_flux_default_matches_catalog_constant(self) -> None:
        # The stage-2 Flux dev sigma_min constant IS this space's t=1e-4
        # endpoint (catalog.py cites the same reference lines).
        assert math.isclose(
            FluxFlowSigmas().sigma_min,
            flux_time_shift(1.15, 1.0, 1.0 / 10000),
            rel_tol=1e-15,
        )


class TestSchedules:
    @pytest.mark.parametrize("space_name", ["discrete_sd", "flow_shift3"])
    @pytest.mark.parametrize("schedule", list(SCHEDULE_FNS))
    @pytest.mark.parametrize("steps", [4, 12, 20])
    def test_matches_reference(self, space_name: str, schedule: str, steps: int) -> None:
        space = spaces_under_test()[space_name]
        ref = GOLDENS["schedules"][space_name][schedule][str(steps)]
        ours = SCHEDULE_FNS[schedule](steps, space)
        seq_close(ours, ref)

    @pytest.mark.parametrize("schedule", list(SCHEDULE_FNS))
    def test_descending_and_terminal_zero(self, schedule: str) -> None:
        space = DiscreteSigmas.linear_beta()
        sigmas = SCHEDULE_FNS[schedule](12, space)
        assert sigmas[-1] == 0.0
        assert all(a > b for a, b in zip(sigmas, sigmas[1:], strict=False)), sigmas

    @pytest.mark.parametrize("schedule", ["simple", "ddim_uniform", "beta"])
    def test_table_schedules_reject_tableless_space(self, schedule: str) -> None:
        @dataclass(frozen=True)
        class NoTable:
            sigma_min: float = 0.01
            sigma_max: float = 10.0

            @property
            def table(self) -> tuple[float, ...] | None:
                return None

            def sigma(self, timestep: float) -> float:
                return timestep

            def timestep(self, sigma: float) -> float:
                return sigma

            def percent_to_sigma(self, percent: float) -> float:
                return 0.0

        with pytest.raises(ValueError, match="discrete sigma table"):
            SCHEDULE_FNS[schedule](8, NoTable())

    @pytest.mark.parametrize("schedule", list(SCHEDULE_FNS))
    def test_rejects_zero_steps(self, schedule: str) -> None:
        with pytest.raises(ValueError, match="steps"):
            SCHEDULE_FNS[schedule](0, DiscreteSigmas.linear_beta())

    def test_beta_quantile_matches_scipy(self) -> None:
        for key, ref in GOLDENS["beta_ppf"].items():
            a, b, p = (float(v) for v in key.split(","))
            assert math.isclose(_beta_quantile(p, a, b), ref, rel_tol=1e-9, abs_tol=1e-12), key

    @pytest.mark.parametrize("a", [0.4, 0.5, 0.6, 1.0])
    def test_beta_quantile_symmetric_midpoint_matches_scipy_bitwise(self, a: float) -> None:
        assert _beta_quantile(0.5, a, a) == GOLDENS["beta_ppf"][f"{a},{a},0.5"]

    def test_radiance_beta_schedule_matches_reference(self) -> None:
        sigmas = beta_schedule(
            30,
            FlowSigmas(shift=1.0, multiplier=1.0),
            alpha=0.4,
            beta=0.4,
        )
        seq_close(sigmas, GOLDENS["chroma_radiance_beta"])

    def test_incomplete_beta_known_values(self) -> None:
        # Symmetry: I_0.5(a, a) = 0.5 for any a.
        assert math.isclose(_regularized_incomplete_beta(0.5, 0.6, 0.6), 0.5, rel_tol=1e-12)
        # I_x(1, 1) = x (uniform distribution).
        assert math.isclose(_regularized_incomplete_beta(0.3, 1.0, 1.0), 0.3, rel_tol=1e-12)
        assert _regularized_incomplete_beta(0.0, 2.0, 3.0) == 0.0
        assert _regularized_incomplete_beta(1.0, 2.0, 3.0) == 1.0

    @pytest.mark.parametrize("bad", [0.0, -0.6, math.nan, math.inf, -math.inf])
    def test_beta_schedule_rejects_bad_shape_params(self, bad: float) -> None:
        space = DiscreteSigmas.linear_beta()
        with pytest.raises(ValueError, match="finite and > 0"):
            beta_schedule(8, space, alpha=bad)
        with pytest.raises(ValueError, match="finite and > 0"):
            beta_schedule(8, space, beta=bad)

    def test_kl_optimal_rejects_single_step(self) -> None:
        # The reference (kl_optimal_scheduler @ 947c2749) divides
        # arange(n) by n - 1: n == 1 is NaN there, refused loudly here.
        with pytest.raises(ValueError, match="steps >= 2"):
            kl_optimal_schedule(1, DiscreteSigmas.linear_beta())

    @pytest.mark.parametrize("schedule", ["simple", "ddim_uniform", "beta"])
    def test_table_schedules_reject_short_table(self, schedule: str) -> None:
        @dataclass(frozen=True)
        class OneEntry:
            sigma_min: float = 0.01
            sigma_max: float = 0.01

            @property
            def table(self) -> tuple[float, ...] | None:
                return (0.01,)

            def sigma(self, timestep: float) -> float:
                return timestep

            def timestep(self, sigma: float) -> float:
                return sigma

            def percent_to_sigma(self, percent: float) -> float:
                return 0.0

        with pytest.raises(ValueError, match="at least"):
            SCHEDULE_FNS[schedule](8, OneEntry())

    def test_zsnr_rescale_invariants(self) -> None:
        plain = linear_beta_sigmas()
        zsnr = linear_beta_sigmas(zsnr=True)
        assert len(zsnr) == len(plain)
        assert all(a < b for a, b in zip(zsnr, zsnr[1:], strict=False))
        # The reference pins the terminal alpha-bar
        # (rescale_zero_terminal_snr_sigmas @ 947c2749).
        terminal_alpha_bar = 4.8973451890853435e-08
        assert math.isclose(
            zsnr[-1],
            math.sqrt((1.0 - terminal_alpha_bar) / terminal_alpha_bar),
            rel_tol=1e-12,
        )

    def test_zsnr_table_matches_executed_comfyui_golden(self) -> None:
        actual = linear_beta_sigmas(zsnr=True)
        expected = VPRED_GOLDENS["zsnr_sigmas"]
        assert len(actual) == len(expected) == 1000
        for got, reference in zip(actual, expected, strict=True):
            assert struct.pack("<f", got) == struct.pack("<f", reference)


RES4LYF_GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "res4lyf_scheduler_goldens.json").read_text()
)

RES4LYF_SCHEDULE_FNS = {
    "beta57": beta57_schedule,
    "bong_tangent": bong_tangent_schedule,
}


class TestRes4lyfSchedules:
    """The two schedulers RES4LYF registers globally, pinned against
    goldens from RUNNING the reference code (RES4LYF sigmas.py
    bong_tangent_scheduler @ 26036f64 and comfy.samplers.beta_scheduler
    alpha=0.5/beta=0.7 @ b78cec87) via
    tools/gen_res4lyf_scheduler_goldens.py."""

    @pytest.mark.parametrize("space_name", ["discrete_sd", "flow_shift3"])
    @pytest.mark.parametrize("schedule", list(RES4LYF_SCHEDULE_FNS))
    @pytest.mark.parametrize("steps", [2, 4, 12, 20, 30, 50])
    def test_matches_reference(self, space_name: str, schedule: str, steps: int) -> None:
        space = spaces_under_test()[space_name]
        ref = RES4LYF_GOLDENS["schedules"][schedule][space_name][str(steps)]
        ours = RES4LYF_SCHEDULE_FNS[schedule](steps, space)
        seq_close(ours, ref)

    def test_bong_tangent_ignores_space(self) -> None:
        # The reference takes model_sampling but never reads it; the
        # goldens were executed under both spaces and are identical.
        assert (
            RES4LYF_GOLDENS["schedules"]["bong_tangent"]["discrete_sd"]
            == RES4LYF_GOLDENS["schedules"]["bong_tangent"]["flow_shift3"]
        )
        assert bong_tangent_schedule(12, DiscreteSigmas.linear_beta()) == bong_tangent_schedule(
            12, FlowSigmas(shift=3.0)
        )

    @pytest.mark.parametrize("schedule", list(RES4LYF_SCHEDULE_FNS))
    def test_descending_and_terminal_zero(self, schedule: str) -> None:
        sigmas = RES4LYF_SCHEDULE_FNS[schedule](12, DiscreteSigmas.linear_beta())
        assert sigmas[-1] == 0.0
        assert all(a > b for a, b in zip(sigmas, sigmas[1:], strict=False)), sigmas

    @pytest.mark.parametrize("steps", [0, 1])
    def test_bong_tangent_rejects_steps_below_two(self, steps: int) -> None:
        # The reference crashes with ZeroDivisionError at steps=1; the
        # port refuses both degenerate counts explicitly.
        with pytest.raises(ValueError, match="steps"):
            bong_tangent_schedule(steps, DiscreteSigmas.linear_beta())

    def test_beta57_rejects_zero_steps(self) -> None:
        with pytest.raises(ValueError, match="steps"):
            beta57_schedule(0, DiscreteSigmas.linear_beta())


PARAM_BY_GOLDEN_NAME = {
    "EPS": Parameterization.EPS,
    "V_PREDICTION": Parameterization.V_PREDICTION,
    "EDM": Parameterization.EDM,
    "CONST": Parameterization.FLOW,
    "IMG_TO_IMG_FLOW": Parameterization.IMAGE_TO_IMAGE_FLOW,
    "X0": Parameterization.X0,
}


class TestPredictions:
    @pytest.mark.parametrize("name", list(PARAM_BY_GOLDEN_NAME))
    def test_matches_reference(self, name: str) -> None:
        ref = GOLDENS["predictions"]
        case = ref[name]
        p = PARAM_BY_GOLDEN_NAME[name]
        sigma = ref["sigma"]
        sigma_data = case["sigma_data"]
        x = Vec(tuple(ref["x"]))
        model_output = Vec(tuple(ref["model_output"]))
        noise = Vec(tuple(ref["noise"]))
        latent = Vec(tuple(ref["latent"]))

        got = calculate_input(p, sigma, x, sigma_data=sigma_data)
        seq_close(got.values, case["calculate_input"], rel=1e-12)

        got = calculate_denoised(p, sigma, model_output, x, sigma_data=sigma_data)
        seq_close(got.values, case["calculate_denoised"], rel=1e-12)

        got = noise_scaling(p, sigma, noise, latent)
        seq_close(got.values, case["noise_scaling"], rel=1e-12)

        got = noise_scaling(p, sigma, noise, latent, max_denoise=True)
        seq_close(got.values, case["noise_scaling_max_denoise"], rel=1e-12)

        got = inverse_noise_scaling(p, sigma, latent)
        seq_close(got.values, case["inverse_noise_scaling"], rel=1e-12)

    def test_flow_noise_scale(self) -> None:
        noise = Vec((1.0, -2.0))
        latent = Vec((0.5, 0.5))
        got = noise_scaling(Parameterization.FLOW, 0.4, noise, latent, noise_scale=2.0)
        # sigma * (scale * noise) + (1 - sigma) * latent
        assert got.values == (0.4 * 2.0 * 1.0 + 0.6 * 0.5, 0.4 * 2.0 * -2.0 + 0.6 * 0.5)


class TestCfg:
    def test_combine_matches_reference_formula(self) -> None:
        cond = Vec((1.0, 2.0))
        uncond = Vec((0.5, -1.0))
        got = cfg_combine(cond, uncond, 7.5)
        assert got.values == (
            0.5 + (1.0 - 0.5) * 7.5,
            -1.0 + (2.0 - -1.0) * 7.5,
        )

    def test_scale_one_is_identity_on_cond(self) -> None:
        cond = Vec((0.25, -0.75))
        uncond = Vec((9.0, 9.0))
        assert cfg_combine(cond, uncond, 1.0).values == pytest.approx(cond.values)

    def test_needs_uncond(self) -> None:
        assert not cfg_needs_uncond(1.0)
        assert cfg_needs_uncond(1.0, disable_cfg1_optimization=True)
        assert cfg_needs_uncond(7.5)
        assert cfg_needs_uncond(0.0)


class TestCfgDenoiser:
    """CfgDenoiser owns cond/uncond branching so evaluators stay
    single-conditioning: one call at cfg 1 or without uncond, two calls
    plus cfg_combine otherwise."""

    @staticmethod
    def _recording_evaluate(
        calls: list[tuple[float, str]],
    ) -> Any:
        def evaluate(x: Vec, sigma: float, conditioning: str) -> Vec:
            calls.append((sigma, conditioning))
            return x * (2.0 if conditioning == "cond" else 0.5)

        return evaluate

    def test_no_uncond_evaluates_cond_once_and_returns_it_untouched(self) -> None:
        calls: list[tuple[float, str]] = []
        denoiser = CfgDenoiser(self._recording_evaluate(calls), "cond", None, 7.5)
        got = denoiser(Vec((1.0, -2.0)), 0.7)
        assert calls == [(0.7, "cond")]
        assert got.values == (2.0, -4.0)

    def test_scale_one_skips_uncond_evaluation(self) -> None:
        calls: list[tuple[float, str]] = []
        denoiser = CfgDenoiser(self._recording_evaluate(calls), "cond", "uncond", 1.0)
        got = denoiser(Vec((1.0, -2.0)), 0.7)
        assert calls == [(0.7, "cond")]
        assert got.values == (2.0, -4.0)

    def test_cfg_runs_cond_then_uncond_and_combines(self) -> None:
        calls: list[tuple[float, str]] = []
        denoiser = CfgDenoiser(self._recording_evaluate(calls), "cond", "uncond", 3.0)
        got = denoiser(Vec((1.0, -2.0)), 0.7)
        assert calls == [(0.7, "cond"), (0.7, "uncond")]
        expected = cfg_combine(Vec((2.0, -4.0)), Vec((0.5, -1.0)), 3.0)
        assert got.values == expected.values


class TestGoldenProvenance:
    def test_reference_commit_is_the_audited_baseline(self) -> None:
        assert GOLDENS["_meta"]["reference_commit"] == "b78cec879b9460d5cb25228a83a942fb78d2cd24"
