"""Proving tests for the self-contained T5 SentencePiece tokenizer.

Every case is pinned against goldens generated by RUNNING the
reference (tests/goldens/t5_tokenizer_goldens.json, produced by
tools/gen_t5_tokenizer_goldens.py with the pinned ``tokenizers``
wheel over ComfyUI's vendored tokenizer.json @ 947c2749): a curated
corpus covering every behavior class plus a 2000-case seeded fuzz
sweep. The oracle is the executed reference, never a re-derivation.
"""

from __future__ import annotations

import json
import sys
from dataclasses import replace
from pathlib import Path

import pytest
from dinkster_inference.prompt_tokens import pack_spans, tokenize_prompt
from dinkster_inference.t5_spm import (
    T5_EOS,
    T5_PAD,
    T5_TOKENIZER_SHA256,
    T5_UNK,
    T5_VOCAB_SIZE,
    T5_XXL_FLUX_PROFILE,
    T5SpmTokenizer,
    load_t5_spm,
)
from dinkster_inference.vendored import read_vendored

GOLDENS = json.loads((Path(__file__).parent / "goldens" / "t5_tokenizer_goldens.json").read_text())

TOK = load_t5_spm()


# ------------------------------------------------- reference parity


def test_goldens_pin_the_vendored_tokenizer_bytes() -> None:
    # The goldens were generated from the exact bytes this package
    # vendors; a drifted regeneration must fail here, not silently
    # re-baseline.
    assert GOLDENS["tokenizer_json_sha256"] == T5_TOKENIZER_SHA256
    assert GOLDENS["reference_commit"] == ("b78cec879b9460d5cb25228a83a942fb78d2cd24")
    assert len(GOLDENS["cases"]) >= 2000


def test_encode_matches_executed_reference() -> None:
    # Reference ids carry the template processor's trailing EOS;
    # encode() returns the inner ids (EOS belongs to chunk packing).
    failures = []
    for case in GOLDENS["cases"]:
        got = [*TOK.encode(case["text"]), T5_EOS]
        if got != case["ids"]:
            failures.append((case["text"], got, case["ids"]))
    assert failures == [], failures[:10]


def test_flux_packing_matches_executed_reference() -> None:
    # comfy.text_encoders.flux.T5XXLTokenizer.tokenize_with_weights,
    # executed: weights grammar over T5 words, no start token, EOS,
    # final chunk padded with 0 to at least 256, never split.
    failures = []
    for case in GOLDENS["weighted"]:
        spans = tokenize_prompt(case["text"], encode_word=TOK.encode).spans
        got = [
            [[item.unit, item.weight, item.word_id] for item in chunk]
            for chunk in pack_spans(spans, T5_XXL_FLUX_PROFILE)
        ]
        if got != case["chunks"]:
            failures.append(case["text"])
    assert failures == []


def test_flux_tokenizer_options_match_executed_reference() -> None:
    failures = []
    for case in GOLDENS["weighted_options"]:
        spans = tokenize_prompt(case["text"], encode_word=TOK.encode).spans
        profile = replace(
            T5_XXL_FLUX_PROFILE,
            min_padding=case["min_padding"],
            min_length=case["min_length"],
        )
        got = [
            [[item.unit, item.weight, item.word_id] for item in chunk]
            for chunk in pack_spans(spans, profile)
        ]
        if got != case["chunks"]:
            failures.append(case["text"])
    assert failures == []


def test_flux_profile_shape() -> None:
    assert T5_XXL_FLUX_PROFILE.start_token is None
    assert T5_XXL_FLUX_PROFILE.end_token == T5_EOS
    assert T5_XXL_FLUX_PROFILE.pad_token == T5_PAD
    assert T5_XXL_FLUX_PROFILE.min_length == 256
    assert not T5_XXL_FLUX_PROFILE.pad_to_max_length


# ------------------------------------------ behavior classes, direct


def test_no_bos_and_no_eos_in_inner_ids() -> None:
    assert TOK.encode("hello") == (21820,)
    assert TOK.encode("") == ()


def test_specials_extract_raw_before_normalization() -> None:
    # Added tokens match on the RAW text (leftmost-longest); the
    # metaspace word-start prefix applies only at original offset 0,
    # so text after a leading special gets no prefix.
    assert TOK.encode("a<extra_id_5>b") == (3, 9, 32094, 115)
    assert TOK.encode("</s>x") == (1, 226)
    assert TOK.encode("x</s>") == (3, 226, 1)


def test_unknown_scripts_fuse_into_single_unk() -> None:
    # fuse_unk: a run of unrepresentable scalars is ONE <unk>.
    assert TOK.encode("\ud55c\uad6d\uc5b4") == (3, T5_UNK)


def test_whitespace_only_normalizes_to_nothing() -> None:
    assert TOK.encode(" ") == ()
    assert TOK.encode("\xa0") == ()


def test_normalize_and_pretokenize_stages() -> None:
    # Charsmap (NFKC-flavored), right-strip, multi-space collapse,
    # then metaspace with prepend_scheme "first".
    assert TOK.normalize("Hey   friend!") == "Hey\u2581friend!"
    assert TOK.normalize("\ufb01") == "fi"
    assert TOK.normalize("\uff12\uff13") == "23"
    assert TOK.normalize("x ") == "x"
    assert TOK.normalize(" hello") == " hello"
    assert TOK.pre_tokenize("Hey   friend!") == ["\u2581Hey", "\u2581friend!"]
    assert TOK.pre_tokenize(" hello") == ["\u2581hello"]
    assert TOK.pre_tokenize("  ") == []


# --------------------------------------------- vendored data pinning


def test_special_ids_match_vendored_vocabulary() -> None:
    spec = json.loads(read_vendored("t5_tokenizer.json.gz", T5_TOKENIZER_SHA256))
    vocab = spec["model"]["vocab"]
    assert vocab[T5_PAD][0] == "<pad>"
    assert vocab[T5_EOS][0] == "</s>"
    assert vocab[T5_UNK][0] == "<unk>"
    assert spec["model"]["unk_id"] == T5_UNK
    assert len(vocab) == 32100
    assert len(spec["added_tokens"]) == 103
    # T5_VOCAB_SIZE is the EMBEDDING row count (padded past the
    # vocabulary), matching t5xxl_fp16 shared.weight [32128, 4096].
    assert T5_VOCAB_SIZE == 32128 > len(vocab)


def test_vendored_tokenizer_hash_mismatch_is_loud() -> None:
    with pytest.raises(ValueError, match="hash mismatch"):
        read_vendored("t5_tokenizer.json.gz", "0" * 64)


def test_fresh_construction_matches_shared_instance() -> None:
    fresh = T5SpmTokenizer.from_vendored_data()
    assert fresh.encode("a photo of a cat") == TOK.encode("a photo of a cat")


def test_no_hf_runtime_dependencies() -> None:
    # The whole pipeline is stdlib + vendored data; the reference
    # wheels must never leak into the runtime import closure.
    assert "tokenizers" not in sys.modules
    assert "transformers" not in sys.modules
    assert "sentencepiece" not in sys.modules
