"""Exact LTX text-embedding connector layout and detection closure.

The golden is generated by executing ComfyUI at b78cec87 through
tools/gen_ltx_embeddings_connector_goldens.py. It pins the connector
tower layout from the real ``Embeddings1DConnector`` state dictionary,
cross-checked at generation time against both connector subtrees of
the real ltx-2-19b-dev checkpoint header, plus the exact facts of the
reference activation condition on that header. Executed forward
replays live in the torch suite.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from dinkster_inference import (
    BFLOAT16,
    LTX_AUDIO_CONNECTOR_PREFIX,
    LTX_TEXT_CONNECTOR_CONFIG,
    LTX_VIDEO_CONNECTOR_PREFIX,
    GemmaTextDetectError,
    LtxConnectorConfig,
    TensorGeometry,
    detect_ltx_text_connectors,
    ltx_connector_layout,
)

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "ltx_embeddings_connector_goldens.json").read_text()
)


def _connector_geometries() -> dict[str, TensorGeometry]:
    return {
        f"{prefix}{key}": TensorGeometry(tuple(shape), BFLOAT16)
        for prefix in (LTX_VIDEO_CONNECTOR_PREFIX, LTX_AUDIO_CONNECTOR_PREFIX)
        for key, shape in GOLDENS["connector_layout"]
    }


def test_full_layout_matches_executed_reference_and_real_checkpoint() -> None:
    expected = [(key, tuple(shape)) for key, shape in GOLDENS["connector_layout"]]
    assert sorted(ltx_connector_layout(LTX_TEXT_CONNECTOR_CONFIG).items()) == expected
    facts = GOLDENS["ltx2_19b_dev"]
    assert facts["video_subtree_matches_reference_layout"] is True
    assert facts["audio_subtree_matches_reference_layout"] is True
    assert facts["connector_key_count"] == 2 * len(expected)
    assert facts["fires_reference_compat_mode"] is True
    assert facts["absent_probe_present"] is False


def test_tiny_layout_matches_executed_reference() -> None:
    config = LtxConnectorConfig(**GOLDENS["tiny"]["config"])
    expected = [(key, tuple(shape)) for key, shape in GOLDENS["tiny"]["state_dict"]]
    assert sorted(ltx_connector_layout(config).items()) == expected


def test_detection_accepts_the_real_combined_checkpoint() -> None:
    geometries = _connector_geometries()
    geometries["model.diffusion_model.transformer_blocks.0.attn.to_q.weight"] = TensorGeometry(
        (3840, 3840), BFLOAT16
    )
    geometries["text_embedding_projection.aggregate_embed.weight"] = TensorGeometry(
        (3840, 188160), BFLOAT16
    )
    assert detect_ltx_text_connectors(geometries) is LTX_TEXT_CONNECTOR_CONFIG


def test_detection_returns_none_without_connector_keys() -> None:
    assert detect_ltx_text_connectors({}) is None
    unrelated = {
        "model.diffusion_model.transformer_blocks.0.attn.to_q.weight": TensorGeometry(
            (3840, 3840), BFLOAT16
        )
    }
    assert detect_ltx_text_connectors(unrelated) is None


def test_reference_activation_condition_is_ported_exactly() -> None:
    trigger = str(GOLDENS["ltx2_19b_dev"]["trigger_key"])
    probe = str(GOLDENS["ltx2_19b_dev"]["absent_probe_key"])
    assert trigger == f"{LTX_AUDIO_CONNECTOR_PREFIX}transformer_1d_blocks.0.attn1.to_q.bias"
    assert probe == f"{LTX_AUDIO_CONNECTOR_PREFIX}transformer_1d_blocks.2.attn1.to_q.bias"
    with_probe = _connector_geometries()
    with_probe[probe] = TensorGeometry((3840,), BFLOAT16)
    with pytest.raises(GemmaTextDetectError, match="unsupported"):
        detect_ltx_text_connectors(with_probe)
    without_trigger = _connector_geometries()
    del without_trigger[trigger]
    with pytest.raises(GemmaTextDetectError, match="activation condition does not hold"):
        detect_ltx_text_connectors(without_trigger)
    wrong_width = _connector_geometries()
    wrong_width[trigger] = TensorGeometry((2048,), BFLOAT16)
    with pytest.raises(GemmaTextDetectError, match="unsupported"):
        detect_ltx_text_connectors(wrong_width)


def test_fired_detection_requires_the_complete_layout() -> None:
    missing = _connector_geometries()
    del missing[f"{LTX_VIDEO_CONNECTOR_PREFIX}learnable_registers"]
    with pytest.raises(GemmaTextDetectError, match="missing"):
        detect_ltx_text_connectors(missing)
    wrong_shape = _connector_geometries()
    wrong_shape[f"{LTX_VIDEO_CONNECTOR_PREFIX}learnable_registers"] = TensorGeometry(
        (64, 3840), BFLOAT16
    )
    with pytest.raises(GemmaTextDetectError, match="expected shape"):
        detect_ltx_text_connectors(wrong_shape)
    extra = _connector_geometries()
    extra[f"{LTX_AUDIO_CONNECTOR_PREFIX}transformer_1d_blocks.0.attn1.extra"] = TensorGeometry(
        (1,), BFLOAT16
    )
    with pytest.raises(GemmaTextDetectError, match="unexpected key"):
        detect_ltx_text_connectors(extra)


def test_config_validators_refuse_impossible_geometry() -> None:
    config = LTX_TEXT_CONNECTOR_CONFIG
    assert config.inner_dim == 3840
    assert config.ffn_dim == 15360
    with pytest.raises(ValueError, match="num_layers must be positive"):
        LtxConnectorConfig(30, 128, 0, 128, 10000.0, 4096)
    with pytest.raises(ValueError, match="must be even"):
        LtxConnectorConfig(30, 127, 2, 128, 10000.0, 4096)
    with pytest.raises(ValueError, match="positional_embedding_theta must be positive"):
        LtxConnectorConfig(30, 128, 2, 128, 0.0, 4096)
