"""Repository-wide byte limits classified by the resource they protect.

Format-integrity limits bound parser work on malformed input. Capacity limits
bound materialization working sets and move to governor reservations as those
call sites become governed. Store limits are configurable retention defaults;
exceeding them must become a miss or non-retention rather than execution
failure.
"""

MEBIBYTE = 1024 * 1024
GIBIBYTE = 1024 * MEBIBYTE

# Format-integrity limits.
CONDITIONING_HEADER_LIMIT_BYTES = 64 * MEBIBYTE
WORKER_FRAME_HEADER_LIMIT_BYTES = 64 * MEBIBYTE

# Materialization capacity limits retained until their owners reserve measured
# working sets through MemoryGovernor.
IMAGE_WORKING_SET_LIMIT_BYTES = 512 * MEBIBYTE
VIDEO_FRAME_WORKING_SET_LIMIT_BYTES = 512 * MEBIBYTE
VIDEO_AUDIO_WORKING_SET_LIMIT_BYTES = 256 * MEBIBYTE
ENCODED_MEDIA_LIMIT_BYTES = GIBIBYTE
VIDEO_VALUE_LIMIT_BYTES = GIBIBYTE
VIDEO_AUDIO_COMPONENT_LIMIT_BYTES = 256 * MEBIBYTE
TIMELINE_ACTIVE_FRAME_LIMIT_BYTES = 512 * MEBIBYTE
TIMELINE_AUDIO_WINDOW_LIMIT_BYTES = 128 * MEBIBYTE
VIDEO_DECODE_WORKING_SET_LIMIT_BYTES = 512 * MEBIBYTE
IMAGE_DOCUMENT_RESOURCE_LIMIT_BYTES = 512 * MEBIBYTE
IMAGE_DOCUMENT_DECODE_RESERVATION_LIMIT_BYTES = 2 * GIBIBYTE
INT8_BACKWARD_TEMP_LIMIT_BYTES = 128 * MEBIBYTE
AIMDO_VBAR_PAGE_BYTES = 32 * MEBIBYTE
TRELLIS2_SPARSE_DECODE_FIXED_BYTES = 6 * GIBIBYTE
TRELLIS2_SPARSE_DECODE_ALIGNMENT_BYTES = 256 * MEBIBYTE

# Store and retention configuration defaults.
CONVERSATION_CAS_BUDGET_BYTES = 512 * MEBIBYTE
RESUMABLE_RESULT_RETENTION_BYTES = 512 * MEBIBYTE
RESUMABLE_EVENT_RETENTION_BYTES = 64 * MEBIBYTE
SAVED_ARTIFACT_LIMIT_BYTES = GIBIBYTE
PEER_CACHE_BLOB_LIMIT_BYTES = 256 * MEBIBYTE
MEDIA_IMAGE_UPLOAD_LIMIT_BYTES = 256 * MEBIBYTE
MEDIA_AUDIO_UPLOAD_LIMIT_BYTES = GIBIBYTE
MEDIA_VIDEO_UPLOAD_LIMIT_BYTES = GIBIBYTE
MEDIA_MODEL3D_UPLOAD_LIMIT_BYTES = GIBIBYTE
LATENT_UPLOAD_HEADROOM_BYTES = GIBIBYTE
