"""Runtime-editable server settings and their HTTP surface."""

from __future__ import annotations

import json
import os
from collections.abc import Callable, Mapping
from copy import deepcopy
from pathlib import Path
from typing import Literal, cast

from aiohttp import web
from dinkster_memory import MemoryGovernor, parse_size
from dinkster_schema import (
    LOG_LEVEL_ENV,
    LOG_OVERRIDES_ENV,
    configure_logging,
)

from .p2p_plugin import P2PSettingsError, normalize_p2p_settings
from .queue import JobQueue

SettingsSource = Literal["cli", "persisted", "config", "default", "runtime"]

SETTINGS_CATEGORIES = (
    "memory-budgets",
    "memory-headroom",
    "aimdo-policy",
    "dtype-policy",
    "fp8-matmul",
    "worker-comfy-args",
    "jobs",
    "logging",
    "p2p",
)
_CATEGORY_SET = frozenset(SETTINGS_CATEGORIES)
_MUTABILITY = {
    "memory-budgets": "live",
    "memory-headroom": "live",
    "aimdo-policy": "on-worker-restart",
    "dtype-policy": "on-worker-restart",
    "fp8-matmul": "on-worker-restart",
    "worker-comfy-args": "on-worker-restart",
    "jobs": "live",
    "logging": "live",
    "p2p": "live",
}
_LOG_LEVELS = frozenset({"debug", "info", "warning", "error", "critical"})
_DTYPE_MODES = frozenset({"auto", "float16", "bfloat16", "float32"})
_COMFY_ARG_OWNERS = {
    "--listen": "Dinkster server",
    "--port": "Dinkster server",
    "--tls-keyfile": "Dinkster server",
    "--tls-certfile": "Dinkster server",
    "--enable-cors-header": "Dinkster server",
    "--max-upload-size": "Dinkster server",
    "--auto-launch": "Dinkster server",
    "--disable-auto-launch": "Dinkster server",
    "--front-end-version": "Dinkster server",
    "--front-end-root": "Dinkster server",
    "--enable-compress-response-body": "Dinkster server",
    "--multi-user": "Dinkster server",
    "--reserve-vram": "Dinkster memory/aimdo policy",
    "--gpu-only": "Dinkster memory/aimdo policy",
    "--highvram": "Dinkster memory/aimdo policy",
    "--normalvram": "Dinkster memory/aimdo policy",
    "--lowvram": "Dinkster memory/aimdo policy",
    "--novram": "Dinkster memory/aimdo policy",
    "--cpu": "Dinkster memory/aimdo policy",
    "--vram-headroom": "Dinkster memory/aimdo policy",
    "--enable-dynamic-vram": "Dinkster memory/aimdo policy",
    "--disable-dynamic-vram": "Dinkster memory/aimdo policy",
    "--fp16-unet": "Dinkster dtype policy",
    "--bf16-unet": "Dinkster dtype policy",
    "--fp32-unet": "Dinkster dtype policy",
    "--fp16-text-enc": "Dinkster dtype policy",
    "--bf16-text-enc": "Dinkster dtype policy",
    "--fp32-text-enc": "Dinkster dtype policy",
    "--fp16-vae": "Dinkster dtype policy",
    "--bf16-vae": "Dinkster dtype policy",
    "--fp32-vae": "Dinkster dtype policy",
}


class SettingsError(ValueError):
    """A settings file or runtime mutation is malformed."""


class ComfyArgumentError(SettingsError):
    """A ComfyUI argument collides with a Dinkster-owned control."""

    def __init__(self, flag: str, owner: str) -> None:
        self.flag = flag
        self.owner = owner
        super().__init__(f"ComfyUI argument {flag!r} is denied because it is owned by {owner}")


class _DinksterOwnedComfyArgument(str):
    """Mark an argv value generated by Dinkster after user input validation."""


def validate_comfy_args(value: object, *, require_tuple: bool = False) -> tuple[str, ...]:
    """Validate the argv-only ComfyUI argument contract."""
    expected = tuple if require_tuple else (list, tuple)
    if not isinstance(value, expected):
        shape = "a tuple of strings" if require_tuple else "a JSON array of strings"
        raise SettingsError(f"worker-comfy-args must be {shape}")
    args = tuple(cast("list[object] | tuple[object, ...]", value))
    if not all(isinstance(item, str) for item in args):
        raise SettingsError("worker-comfy-args must be a JSON array of strings")
    for argument in cast("tuple[str, ...]", args):
        if isinstance(argument, _DinksterOwnedComfyArgument):
            continue
        flag = argument.partition("=")[0]
        owner = _COMFY_ARG_OWNERS.get(flag)
        if owner is None and flag.startswith("--"):
            owner = next(
                (
                    candidate_owner
                    for denied, candidate_owner in _COMFY_ARG_OWNERS.items()
                    if denied.startswith(flag)
                ),
                None,
            )
        if owner is not None:
            raise ComfyArgumentError(flag, owner)
    return cast("tuple[str, ...]", args)


def _size(value: object, where: str) -> int:
    if isinstance(value, bool):
        raise SettingsError(f"{where} must be integer bytes or a K/M/G/T size")
    if isinstance(value, int):
        if value < 0:
            raise SettingsError(f"{where} must be >= 0")
        return value
    if isinstance(value, str):
        try:
            return parse_size(value)
        except ValueError as exc:
            raise SettingsError(f"{where}: {exc}") from None
    raise SettingsError(f"{where} must be integer bytes or a K/M/G/T size")


def _object(value: object, where: str) -> dict[str, object]:
    if not isinstance(value, Mapping):
        raise SettingsError(f"{where} must be an object")
    return {str(key): item for key, item in cast("Mapping[object, object]", value).items()}


def _exact_keys(body: Mapping[str, object], expected: set[str], where: str) -> None:
    actual = set(body)
    if actual != expected:
        raise SettingsError(
            f"{where} must contain exactly {sorted(expected)}, got {sorted(actual)}"
        )


def _memory_budgets(value: object) -> dict[str, int]:
    body = _object(value, "memory-budgets")
    budgets: dict[str, int] = {}
    for device, raw in body.items():
        if not device or device != device.strip() or any(ch.isspace() for ch in device):
            raise SettingsError(
                f"memory-budgets device names must be non-empty and whitespace-free: {device!r}"
            )
        budgets[device] = _size(raw, f"memory-budgets[{device!r}]")
    return budgets


def _aimdo(value: object) -> str:
    if not isinstance(value, str) or value not in ("auto", "on", "off"):
        raise SettingsError("aimdo-policy mode must be one of ['auto', 'off', 'on']")
    return value


def _boolean(value: object, where: str) -> bool:
    if not isinstance(value, bool):
        raise SettingsError(f"{where} must be a boolean")
    return value


def _dtype_policy(value: object) -> dict[str, str]:
    body = _object(value, "dtype-policy")
    _exact_keys(body, {"diffusion", "textEncoder", "vae"}, "dtype-policy")
    policy: dict[str, str] = {}
    for component, mode in body.items():
        if not isinstance(mode, str) or mode not in _DTYPE_MODES:
            raise SettingsError(f"dtype-policy.{component} must be one of {sorted(_DTYPE_MODES)}")
        policy[component] = mode
    return policy


def comfy_dtype_args(policy: Mapping[str, str]) -> tuple[str, ...]:
    """Translate serve dtype policy into ComfyUI's process-wide flags."""
    normalized = _dtype_policy(policy)
    suffixes = {"float16": "fp16", "bfloat16": "bf16", "float32": "fp32"}
    flags = {
        "diffusion": "unet",
        "textEncoder": "text-enc",
        "vae": "vae",
    }
    return tuple(
        _DinksterOwnedComfyArgument(f"--{suffixes[normalized[component]]}-{flags[component]}")
        for component in ("diffusion", "textEncoder", "vae")
        if normalized[component] != "auto"
    )


def comfy_cpu_args() -> tuple[str, ...]:
    """Select ComfyUI's CPU device through Dinkster's owned worker policy."""
    return (_DinksterOwnedComfyArgument("--cpu"),)


def _jobs(value: object) -> dict[str, int]:
    body = _object(value, "jobs")
    _exact_keys(body, {"maxRunningJobs"}, "jobs")
    count = body["maxRunningJobs"]
    if isinstance(count, bool) or not isinstance(count, int) or count < 1:
        raise SettingsError("jobs.maxRunningJobs must be an integer >= 1")
    return {"maxRunningJobs": count}


def _logging(value: object) -> dict[str, object]:
    body = _object(value, "logging")
    _exact_keys(body, {"level", "overrides"}, "logging")
    level = body["level"]
    if not isinstance(level, str) or level.strip().lower() not in _LOG_LEVELS:
        raise SettingsError(f"logging.level must be one of {sorted(_LOG_LEVELS)}")
    overrides_raw = _object(body["overrides"], "logging.overrides")
    overrides: dict[str, str] = {}
    for name, raw_level in overrides_raw.items():
        if name != "dinkster" and not name.startswith("dinkster."):
            raise SettingsError(f"logging override outside the 'dinkster' tree: {name!r}")
        if not isinstance(raw_level, str) or raw_level.strip().lower() not in _LOG_LEVELS:
            raise SettingsError(f"logging override {name!r} must be one of {sorted(_LOG_LEVELS)}")
        overrides[name] = raw_level.strip().lower()
    return {"level": level.strip().lower(), "overrides": overrides}


def normalize_setting(category: str, value: object) -> object:
    if category == "memory-budgets":
        return _memory_budgets(value)
    if category == "memory-headroom":
        return _size(value, "memory-headroom")
    if category == "aimdo-policy":
        return _aimdo(value)
    if category == "dtype-policy":
        return _dtype_policy(value)
    if category == "fp8-matmul":
        return _boolean(value, "fp8-matmul")
    if category == "worker-comfy-args":
        return validate_comfy_args(value)
    if category == "jobs":
        return _jobs(value)
    if category == "logging":
        return _logging(value)
    if category == "p2p":
        try:
            return normalize_p2p_settings(value)
        except P2PSettingsError as exc:
            raise SettingsError(str(exc)) from exc
    raise SettingsError(f"unknown settings category: {category!r}")


def load_settings(path: Path) -> dict[str, object]:
    """Load and validate settings.json; a missing file means no overrides."""
    if not path.exists():
        return {}
    try:
        raw = json.loads(path.read_text("utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SettingsError(f"{path}: invalid settings JSON: {exc}") from exc
    body = _object(raw, str(path))
    unknown = set(body) - _CATEGORY_SET
    if unknown:
        raise SettingsError(f"{path}: unknown settings categories {sorted(unknown)}")
    try:
        return {category: normalize_setting(category, value) for category, value in body.items()}
    except SettingsError as exc:
        raise SettingsError(f"{path}: {exc}") from exc


class RuntimeSettings:
    """Effective values, provenance, permissions, and durable runtime edits."""

    def __init__(
        self,
        values: Mapping[str, object],
        sources: Mapping[str, SettingsSource],
        *,
        granted: frozenset[str] = frozenset(),
        path: Path | None = None,
        persisted_values: Mapping[str, object] | None = None,
    ) -> None:
        category_set = set(SETTINGS_CATEGORIES)
        if set(values) != category_set or set(sources) != category_set:
            raise ValueError("runtime settings must initialize every category")
        self._values = {
            category: normalize_setting(category, value) for category, value in values.items()
        }
        self._sources = dict(sources)
        self._granted = frozenset(granted)
        if not self._granted <= _CATEGORY_SET:
            raise ValueError("granted contains an unknown settings category")
        self._path = path
        self._runtime_values = {
            category: normalize_setting(category, value)
            for category, value in (persisted_values or {}).items()
        }
        self._governor: MemoryGovernor | None = None
        self._queue: JobQueue | None = None
        self._memory_headroom_changed: Callable[[int], None] | None = None
        self._p2p_changed: Callable[[dict[str, object]], None] | None = None

    @property
    def aimdo_policy(self) -> str:
        return cast("str", self._values["aimdo-policy"])

    @property
    def fp8_matmul(self) -> bool:
        return cast("bool", self._values["fp8-matmul"])

    @property
    def dtype_policy(self) -> dict[str, str]:
        return cast("dict[str, str]", deepcopy(self._values["dtype-policy"]))

    @property
    def memory_headroom(self) -> int:
        return cast("int", self._values["memory-headroom"])

    @property
    def memory_budgets(self) -> dict[str, int]:
        return cast("dict[str, int]", deepcopy(self._values["memory-budgets"]))

    @property
    def worker_comfy_args(self) -> tuple[str, ...]:
        return cast("tuple[str, ...]", self._values["worker-comfy-args"]) + comfy_dtype_args(
            self.dtype_policy
        )

    @property
    def p2p(self) -> dict[str, object]:
        return cast("dict[str, object]", deepcopy(self._values["p2p"]))

    @property
    def granted(self) -> list[str]:
        return [category for category in SETTINGS_CATEGORIES if category in self._granted]

    def bind(
        self,
        governor: MemoryGovernor | None,
        queue: JobQueue,
        *,
        memory_headroom_changed: Callable[[int], None] | None = None,
    ) -> None:
        self._governor = governor
        self._queue = queue
        self._memory_headroom_changed = memory_headroom_changed

    def bind_p2p(self, changed: Callable[[dict[str, object]], None]) -> None:
        self._p2p_changed = changed

    def section(self, category: str) -> dict[str, object]:
        if category not in _CATEGORY_SET:
            raise SettingsError(f"unknown settings category: {category!r}")
        source = self._sources[category]
        return {
            "value": deepcopy(self._values[category]),
            "source": source,
            "mutability": _MUTABILITY[category],
            "writable": category in self._granted,
            "persistence": {
                "available": self._path is not None,
                "persisted": source == "persisted"
                or (source == "runtime" and self._path is not None),
            },
        }

    def payload(self) -> dict[str, object]:
        return {
            "categories": {
                "granted": self.granted,
                "available": list(SETTINGS_CATEGORIES),
            },
            "settings": {category: self.section(category) for category in SETTINGS_CATEGORIES},
        }

    def update(self, category: str, body: object) -> dict[str, object]:
        value = normalize_setting(category, body)
        if category == "memory-budgets":
            value = {
                **cast("dict[str, int]", self._values[category]),
                **cast("dict[str, int]", value),
            }
        staged = {**self._runtime_values, category: value}
        if self._path is not None:
            self._write(staged)

        if category == "memory-budgets":
            if self._governor is None:
                raise RuntimeError("memory-budgets require a memory governor")
            for device, nbytes in cast("dict[str, int]", value).items():
                self._governor.set_budget(device, nbytes)
        elif category == "jobs":
            if self._queue is None:
                raise RuntimeError("jobs settings require a job queue")
            self._queue.set_max_running(cast("dict[str, int]", value)["maxRunningJobs"])
        elif category == "logging":
            logging_value = cast("dict[str, object]", value)
            level = cast("str", logging_value["level"])
            overrides = cast("dict[str, str]", logging_value["overrides"])
            configure_logging(level, overrides=overrides)
            os.environ[LOG_LEVEL_ENV] = level
            if overrides:
                os.environ[LOG_OVERRIDES_ENV] = ",".join(
                    f"{name}={override}" for name, override in overrides.items()
                )
            else:
                os.environ.pop(LOG_OVERRIDES_ENV, None)

        self._values[category] = value
        self._sources[category] = "runtime"
        self._runtime_values = staged
        if category == "memory-headroom" and self._memory_headroom_changed is not None:
            self._memory_headroom_changed(cast("int", value))
        if category == "p2p" and self._p2p_changed is not None:
            self._p2p_changed(cast("dict[str, object]", deepcopy(value)))
        return self.section(category)

    def _write(self, values: Mapping[str, object]) -> None:
        assert self._path is not None
        self._path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self._path.with_name(self._path.name + ".tmp")
        data = json.dumps(values, indent=2, sort_keys=True) + "\n"
        try:
            with temporary.open("w", encoding="utf-8") as handle:
                handle.write(data)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, self._path)
        finally:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass


async def handle_settings(request: web.Request) -> web.Response:
    settings = request.app[SETTINGS_KEY]
    return web.json_response(settings.payload())


async def handle_settings_update(request: web.Request) -> web.Response:
    settings = request.app[SETTINGS_KEY]
    category = request.match_info["category"]
    if category not in _CATEGORY_SET:
        return web.json_response(
            {
                "error": "invalid-settings",
                "category": category,
                "message": f"unknown settings category: {category!r}",
            },
            status=400,
        )
    granted_list = settings.granted
    if category not in granted_list:
        return web.json_response(
            {
                "error": "settings-changes-disabled",
                "category": category,
                "granted": granted_list,
            },
            status=403,
        )
    try:
        body = await request.json()
    except json.JSONDecodeError as exc:
        return web.json_response(
            {
                "error": "invalid-settings",
                "category": category,
                "message": f"invalid JSON: {exc}",
            },
            status=400,
        )
    try:
        section = settings.update(category, body)
    except SettingsError as exc:
        error: dict[str, object] = {
            "error": "invalid-settings",
            "category": category,
            "message": str(exc),
        }
        if isinstance(exc, ComfyArgumentError):
            error.update({"offendingFlag": exc.flag, "owner": exc.owner})
        return web.json_response(error, status=400)
    return web.json_response(section)


SETTINGS_KEY: web.AppKey[RuntimeSettings] = web.AppKey("dinkster_settings")


def add_settings_routes(app: web.Application, settings: RuntimeSettings) -> None:
    app[SETTINGS_KEY] = settings
    app.router.add_get("/api/settings", handle_settings)
    app.router.add_put("/api/settings/{category}", handle_settings_update)
