"""Dinkster's lightweight first-party logic, math, text, list, and utility nodes."""

from .basic import AddInts, ConcatStrings, JoinStrings, MultiplyFloats, SplitString
from .combo import COMBO_EDGE_NODES, ComboToString, StringToCombo
from .conversion import (
    CONVERSION_NODES,
    CurveEditor,
    CurveEvaluate,
    CurveFromValues,
    CurveSample,
    StringScheduleParse,
    ValueConvert,
)
from .expression import MathExpression
from .lists import (
    AppendToList,
    ConcatLists,
    CrossProduct,
    IntegerRange,
    ListElement,
    ListLength,
    MakeList,
    RepeatItem,
    ReverseList,
    SliceList,
)
from .numeric import (
    NUMERIC_NODES,
    BoolLogic,
    ValueClamp,
    ValueCompare,
    ValueRandom,
    ValueRemap,
    ValueSelect,
)
from .outputs import EntryFanOut, MathExpressions
from .primitives import (
    PRIMITIVE_NODES,
    BooleanPrimitive,
    FloatPrimitive,
    IntPrimitive,
    PreviewAsText,
    StringMultilinePrimitive,
    StringPrimitive,
)
from .routing import ROUTING_NODES, RouteGate, RouteSwitch, RouteSwitchByName
from .string_ops import (
    STRING_OPERATION_NODES,
    StringCsvEmit,
    StringCsvParse,
    StringFormat,
    StringJoin,
    StringJson,
    StringJsonEmit,
    StringLength,
    StringRegex,
    StringSplit,
    StringTest,
    StringTransform,
)
from .types import CURVE_TYPE, Curve, register_foundation_types

FOUNDATION_NODES = [
    AddInts,
    MultiplyFloats,
    MathExpression,
    MathExpressions,
    EntryFanOut,
    *NUMERIC_NODES,
    ConcatStrings,
    JoinStrings,
    SplitString,
    MakeList,
    AppendToList,
    ListLength,
    ListElement,
    ConcatLists,
    ReverseList,
    SliceList,
    IntegerRange,
    RepeatItem,
    CrossProduct,
    *PRIMITIVE_NODES,
    *COMBO_EDGE_NODES,
    *STRING_OPERATION_NODES,
    *CONVERSION_NODES,
    *ROUTING_NODES,
]

__all__ = [
    "COMBO_EDGE_NODES",
    "CONVERSION_NODES",
    "CURVE_TYPE",
    "FOUNDATION_NODES",
    "NUMERIC_NODES",
    "PRIMITIVE_NODES",
    "ROUTING_NODES",
    "STRING_OPERATION_NODES",
    "AddInts",
    "AppendToList",
    "BooleanPrimitive",
    "BoolLogic",
    "ComboToString",
    "ConcatLists",
    "ConcatStrings",
    "CrossProduct",
    "Curve",
    "CurveEditor",
    "CurveEvaluate",
    "CurveFromValues",
    "CurveSample",
    "EntryFanOut",
    "FloatPrimitive",
    "IntegerRange",
    "IntPrimitive",
    "JoinStrings",
    "ListElement",
    "ListLength",
    "MakeList",
    "MathExpression",
    "MathExpressions",
    "MultiplyFloats",
    "PreviewAsText",
    "RepeatItem",
    "ReverseList",
    "RouteGate",
    "RouteSwitch",
    "RouteSwitchByName",
    "SliceList",
    "SplitString",
    "StringCsvEmit",
    "StringCsvParse",
    "StringFormat",
    "StringJoin",
    "StringJson",
    "StringJsonEmit",
    "StringLength",
    "StringMultilinePrimitive",
    "StringPrimitive",
    "StringRegex",
    "StringScheduleParse",
    "StringSplit",
    "StringTest",
    "StringToCombo",
    "StringTransform",
    "ValueClamp",
    "ValueCompare",
    "ValueConvert",
    "ValueRandom",
    "ValueRemap",
    "ValueSelect",
    "register_foundation_types",
]
