"""Generated by tools/gen_extension_contribution_kinds.py; do not edit."""

FRONTEND_CONTRIBUTION_KINDS = (
    "widgetKind",
    "widgetView",
    "previewRenderer",
    "textEditorExtension",
    "menu",
    "command",
    "keybinding",
    "setting",
    "canvasLayer",
    "nodeDecoration",
    "hostUi",
    "searchProvider",
    "workflowObserver",
    "eventConsumer",
    "workflowImporter",
    "editor",
    "editorBinding",
    "panel",
)

IMPLEMENTED_FRONTEND_CONTRIBUTION_KINDS = (
    "widgetKind",
    "widgetView",
    "previewRenderer",
    "textEditorExtension",
    "menu",
    "command",
    "keybinding",
    "setting",
    "hostUi",
    "searchProvider",
    "eventConsumer",
    "editor",
    "editorBinding",
    "panel",
)
