"""Shared contracts retained outside the fork-backed inference runtime."""

from dinkster_values import GIBIBYTE, MEBIBYTE

from .conditioning_wire import (
    CONDITIONING_TYPE_ID,
    ConditioningCarrier,
    ResidentConditioningCarrier,
    register_conditioning_type,
)
from .devices import nvidia_compute_dtypes
from .generation import (
    GenerationEvent,
    GenerationFinishReason,
    GenerationMessage,
    GenerationMessageRole,
    GenerationProvider,
    GenerationProviderCapabilities,
    GenerationRequest,
    GenerationResult,
    GenerationSamplerChain,
    GenerationSamplerKind,
    GenerationSamplerStage,
    GenerationSessionBusyError,
    GenerationSessionClosedError,
    GenerationSessionError,
    GenerationSessionHandle,
    GenerationStats,
    GenerationStopConditions,
    GenerationStream,
    GenerationTerminalEvent,
    GenerationTokenEvent,
)
from .latents import (
    LatentDescriptor,
    LatentDimensions,
    LatentPackLayout,
    LatentPackStreamLayout,
    LatentStream,
    MultiStreamLatent,
    MultiStreamLatentDescriptor,
)
from .openai_generation import (
    OpenAICompatibility,
    OpenAIGenerationError,
    OpenAIGenerationProvider,
)
from .sampling_wire import (
    BuiltinSamplerSelection,
    NoiseSelection,
    SamplerSelection,
    SigmaSchedule,
    register_sampling_type,
)
from .sources import (
    MalformedSafetensors,
    SafetensorsSource,
    load_safetensors_header,
    load_safetensors_header_from_file,
)
from .sparse import (
    PBR_CHANNELS,
    SUBDIVISION_CHANNELS,
    DenseVoxelGrid,
    SparseLatent,
    SparseSubdivisionGuides,
    SparseSupport,
    SparseVolume,
    TexturedMesh,
    TriangleMesh,
    TriangleMeshBatch,
)
from .types import register_inference_types

__all__ = [
    "BuiltinSamplerSelection",
    "CONDITIONING_TYPE_ID",
    "ConditioningCarrier",
    "GIBIBYTE",
    "MEBIBYTE",
    "NoiseSelection",
    "ResidentConditioningCarrier",
    "SamplerSelection",
    "SigmaSchedule",
    "nvidia_compute_dtypes",
    "register_conditioning_type",
    "register_inference_types",
    "register_sampling_type",
    "DenseVoxelGrid",
    "GenerationEvent",
    "GenerationFinishReason",
    "GenerationMessage",
    "GenerationMessageRole",
    "GenerationProvider",
    "GenerationProviderCapabilities",
    "GenerationRequest",
    "GenerationResult",
    "GenerationSamplerChain",
    "GenerationSamplerKind",
    "GenerationSamplerStage",
    "GenerationSessionBusyError",
    "GenerationSessionClosedError",
    "GenerationSessionError",
    "GenerationSessionHandle",
    "GenerationStats",
    "GenerationStopConditions",
    "GenerationStream",
    "GenerationTerminalEvent",
    "GenerationTokenEvent",
    "LatentDescriptor",
    "LatentDimensions",
    "LatentPackLayout",
    "LatentPackStreamLayout",
    "LatentStream",
    "MalformedSafetensors",
    "MultiStreamLatent",
    "MultiStreamLatentDescriptor",
    "OpenAICompatibility",
    "OpenAIGenerationError",
    "OpenAIGenerationProvider",
    "PBR_CHANNELS",
    "SUBDIVISION_CHANNELS",
    "SafetensorsSource",
    "SparseLatent",
    "SparseSubdivisionGuides",
    "SparseSupport",
    "SparseVolume",
    "TexturedMesh",
    "TriangleMesh",
    "TriangleMeshBatch",
    "load_safetensors_header",
    "load_safetensors_header_from_file",
]
