"""Regenerate native-only manifests: uv run python tools/gen_native_comfy_manifests.py."""

from __future__ import annotations

from pathlib import Path

from dinkster_native.native_catalog import COMFY_RUNTIME_NODE_IDS


def native_manifest(source: str) -> str:
    omitted = {f'"{node_type}",' for node_type in COMFY_RUNTIME_NODE_IDS}
    text = "".join(line for line in source.splitlines(keepends=True) if line.strip() not in omitted)
    text = text.replace('name = "dinkster-compat-comfy"', 'name = "dinkster-native"', 1)
    text = text.replace(
        "# No interpreter requirements: this pack runs on the ComfyUI install's own\n"
        "# interpreter, which already has torch and every v1 dependency. Dinkster's\n"
        "# pure-stdlib packages ride in via PYTHONPATH.\n",
        "# Python requirements are supplied by the dinkster-native package environment.\n",
        1,
    )
    replacements = {
        "dinkster_compat_comfy.entry:COMFY_NODES": "dinkster_native.entry:NATIVE_NODES",
        "dinkster_compat_comfy.entry:ARM_NODES": "dinkster_native.entry:ARM_NODES",
        "dinkster_compat_comfy.entry:register_types": "dinkster_native.entry:register_types",
        "dinkster_compat_comfy.memory:plan_reservations": (
            "dinkster_native.memory:plan_reservations"
        ),
        "dinkster_compat_comfy.pool:memory_consumers": "dinkster_native.pool:memory_consumers",
        "dinkster_compat_comfy.devices:vram_telemetry_snapshot": (
            "dinkster_native.devices:vram_telemetry_snapshot"
        ),
        "dinkster_compat_comfy.entry:combo_choices": "dinkster_native.entry:combo_choices",
        "dinkster_compat_comfy.workgroup:create_single_job_workgroup_handler": (
            "dinkster_native.workgroup:create_single_job_workgroup_handler"
        ),
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = "".join(
        line
        for line in text.splitlines(keepends=True)
        if not line.startswith(("skips = ", "source_staging = "))
    )
    return (
        "# Generated by tools/gen_native_comfy_manifests.py; edit dinkster-pack.toml instead.\n"
        + text
    )


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    compat = root / "packages/dinkster-compat-comfy"
    source = (compat / "dinkster-pack.toml").read_text(encoding="utf-8")
    (root / "packages/dinkster-native/dinkster-pack.toml").write_text(
        native_manifest(source), encoding="utf-8"
    )
