"""Generate the backend and frontend extension contribution vocabularies."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT
    / "packages"
    / "dinkster-protocol"
    / "src"
    / "dinkster_protocol"
    / "extension_contribution_kinds.json"
)
BACKEND_OUTPUT = SOURCE.with_name("extension_contribution_kinds.py")


def _kinds() -> tuple[list[str], list[str]]:
    raw = cast("object", json.loads(SOURCE.read_text()))
    if not isinstance(raw, list):
        raise ValueError("contribution vocabulary must be an array")
    kinds: list[str] = []
    implemented: list[str] = []
    for item in cast("list[object]", raw):
        if (
            not isinstance(item, dict)
            or set(item) != {"kind", "implemented"}
            or not isinstance(item["kind"], str)
            or not item["kind"]
            or not isinstance(item["implemented"], bool)
        ):
            raise ValueError("each contribution kind needs a string kind and boolean implemented")
        kind = cast("str", item["kind"])
        if kind in kinds:
            raise ValueError(f"duplicate contribution kind: {kind}")
        kinds.append(kind)
        if item["implemented"]:
            implemented.append(kind)
    return kinds, implemented


def _python_tuple(name: str, values: list[str]) -> str:
    entries = "".join(f'    "{value}",\n' for value in values)
    return f"{name} = (\n{entries})\n"


def _typescript_array(name: str, values: list[str]) -> str:
    entries = "\n".join(f"  '{value}'," for value in values)
    return f"export const {name} = [\n{entries}\n] as const\n"


def _outputs(frontend_root: Path | None) -> dict[Path, str]:
    kinds, implemented = _kinds()
    outputs = {
        BACKEND_OUTPUT: (
            '"""Generated by tools/gen_extension_contribution_kinds.py; do not edit."""\n\n'
            + _python_tuple("FRONTEND_CONTRIBUTION_KINDS", kinds)
            + "\n"
            + _python_tuple("IMPLEMENTED_FRONTEND_CONTRIBUTION_KINDS", implemented)
        )
    }
    if frontend_root is not None:
        target = (
            frontend_root
            / "packages"
            / "core"
            / "src"
            / "extensions"
            / "contribution-kinds.generated.ts"
        )
        outputs[target] = (
            "// Generated by Dinkster/tools/gen_extension_contribution_kinds.py; do not edit.\n\n"
            + _typescript_array("FRONTEND_CONTRIBUTION_KINDS", kinds)
            + "\n"
            + _typescript_array("CONTRIBUTION_CATEGORIES", implemented)
        )
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--frontend-root", type=Path)
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in _outputs(args.frontend_root).items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        parser.error("generated contribution vocabulary is stale: " + ", ".join(map(str, stale)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
