"""dinkster-registry: the pure registry model.

Identities, namespace grants, immutable releases, review lifecycle, and
the deterministic admission gate - no server, storage, or network. The
future registry service composes these; publishers and CI can run the
identical predicates locally.
"""

from .admission import (
    AdmissionFinding,
    DoctorEvidence,
    Submission,
    Verdict,
    admit,
    record_acceptance,
)
from .artifact import (
    MANIFEST_FILENAME,
    ArtifactError,
    build_artifact,
    unpack_artifact,
    verify_artifact,
)
from .composition import (
    COMPOSITION_FORMAT,
    ComposedPack,
    CompositionGeneration,
    CompositionMode,
    CompositionRecordError,
    RequirementKind,
    ResolvedRequirement,
)
from .grants import ClaimStatus, Grant, GrantTable
from .install import (
    LOCKFILE_FORMAT,
    PLAN_FORMAT,
    SNAPSHOT_FORMAT,
    Generation,
    GenerationLedger,
    InstallError,
    InstallPlan,
    InstallStep,
    LockedPack,
    Lockfile,
    PlanRecord,
    SnapshotRecord,
    StepAction,
    VenvSpec,
    plan,
)
from .model import (
    ARTIFACT_DIGEST_PREFIX,
    RegistryError,
    Release,
    ReleaseIndex,
    ReleaseTemplate,
    RepoBindings,
    ReviewLog,
    ReviewTransition,
    Version,
    VersionState,
    artifact_digest,
    canonical_json,
    validate_artifact_digest,
    validate_version,
)
from .principals import (
    TOKEN_PREFIX,
    Action,
    AuditRecord,
    Membership,
    PrincipalDirectory,
    Role,
    TokenRecord,
)

__all__ = [
    "ARTIFACT_DIGEST_PREFIX",
    "COMPOSITION_FORMAT",
    "LOCKFILE_FORMAT",
    "MANIFEST_FILENAME",
    "PLAN_FORMAT",
    "SNAPSHOT_FORMAT",
    "TOKEN_PREFIX",
    "Action",
    "AdmissionFinding",
    "ArtifactError",
    "AuditRecord",
    "ClaimStatus",
    "ComposedPack",
    "CompositionGeneration",
    "CompositionMode",
    "CompositionRecordError",
    "DoctorEvidence",
    "Generation",
    "GenerationLedger",
    "Grant",
    "GrantTable",
    "InstallError",
    "InstallPlan",
    "InstallStep",
    "LockedPack",
    "Lockfile",
    "Membership",
    "PlanRecord",
    "PrincipalDirectory",
    "RegistryError",
    "SnapshotRecord",
    "Release",
    "ReleaseIndex",
    "ReleaseTemplate",
    "RequirementKind",
    "ResolvedRequirement",
    "RepoBindings",
    "ReviewLog",
    "ReviewTransition",
    "Role",
    "StepAction",
    "Submission",
    "TokenRecord",
    "Verdict",
    "VenvSpec",
    "Version",
    "VersionState",
    "admit",
    "artifact_digest",
    "build_artifact",
    "canonical_json",
    "plan",
    "record_acceptance",
    "unpack_artifact",
    "validate_artifact_digest",
    "validate_version",
    "verify_artifact",
]
